### ISSUE TITLE
Erro ao Criar um novo serviço

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#102]
**Erro ao Criar um novo serviço**
Ao clicar no botão para criar um novo serviço aparece a tela de erro conforme imagem abaixo, peço correção , por favor.
![image](https://user-images.githubusercontent.com/60766925/92633754-9f0c4e00-f2a9-11ea-9211-d6a17d38f740.png)

**Comment by fullcontent** [comment]
@castroli resolvido
