### ISSUE TITLE
A vencer - incluir novo botão

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#103]
**Incluir botão**
Temos documentos com validade que não fazem parte das "licenças de operação" que tambem está indo para tela de "a vencer", muito dificilmente teremos que renovar um documento que não estão dentro do grupo "licenças de operação". Neste caso, como normalmente o documento não será renovado, precisamos incluir um botão no qual irá **desconsiderar** esta licença/documento deste campo. 
Atualmente temos o botão de excluir, mas se clicar nele, irei excluir o serviço (ja fiz o teste). 

![image](https://user-images.githubusercontent.com/60766925/94149395-364ad700-fe4e-11ea-9b61-649587eddf55.png)

**Comment by castroli** [comment]
Bom dia @fullcontent .
Consegue incluir este botão ainda esta semana? estamos acumulando muitos serviços em nossa dashboard aguardando a inserção deste botão.

Abraço.

**Comment by fullcontent** [comment]
@castroli 

Bom dia...
Fiz um ajuste na listagem, filtrando somente as licenças de operação a vencer. Veja se dessa forma que fiz resolve esse problema ou se precisaremos criar o botão.

**Comment by castroli** [comment]
@fullcontent  bom dia!
Não resolve, pois por exemplo, temos serviços que realizamos a renovação no ano passado, porém, neste ano não será feito pela nossa empresa, com isso não tenho a opção de desconsiderar do sistema a renovação desta licença. 
Outro ponto é que neste periodo notamos que temos alguns acasos (raros) que precisamos renovar alguns documentos que estão no tipo "Licenças/Projetos não renováveis". O ideal seria manter ilgual estava (puxando tanto os "Licenças/Projetos não renováveis" e "Licença de Operação") e incluir um botão para desconsiderar estas licenças/documentos que não vamos trabalhar na renovação, porém, diferente do botão excluir, ele permanecesse em nosso banco de dados mesmo vencido.

**Comment by castroli** [comment]
@fullcontent conseguimos evoluir com esta pendência?

**Comment by castroli** [comment]
@fullcontent precisamos evoluir com este caso. A opção de desconsiderar alguns serviços de renovação se torna a cada dia mais necessário.

**Comment by fullcontent** [comment]
A fazer:

Usar o campo tipoLicenca para inserir uma opção NÃO RENOVADA.

Inserir um botão DESCONSIDERAR na listagem de serviços a vencer.


- [ ] Inserir botão desconsiderar
- [ ] Filtro na listagem a vencer com tipoLicenca
- [ ] Opção NÂO RENOVADA na edição do serviço

**Comment by fullcontent** [comment]
@castroli

Peço testar e finalizar esse chamado se estiver tudo ok.

**Comment by castroli** [comment]
@fullcontent , exatamente isso que precisavamos, peço apenas dois ajustes:

- [ ]  Substituir a palavra "Não renovado" para "Stand by";
- [ ] Na tela detalhes da unidade temos o campo que mostra a situação (a licença está vigente fica verde, vencida vermelho), peço ajustar de modo que a situação "Stand by" apareça neste mesmo formato.

![image](https://user-images.githubusercontent.com/60766925/114455349-0aa4f980-9bb2-11eb-82d6-fd18c404be8c.png)

**Comment by fullcontent** [comment]
@castroli

Peço testar e finalizar esse chamado se estiver tudo ok.

**Comment by castroli** [comment]
@fullcontent 

Para o serviço 98 deu certo, porem acabei de fazer para outro serviço (103) e ficou igual estava antes, peço verificar.
**Serviço 98:**
http://sistemacelic.net/admin/unidades/98
![image](https://user-images.githubusercontent.com/60766925/114621398-07c60980-9c83-11eb-9614-5934d4d2dee8.png)

**Serviço 103:**
http://sistemacelic.net/admin/unidades/103
![image](https://user-images.githubusercontent.com/60766925/114621608-478cf100-9c83-11eb-892d-7376b7378f73.png)
![image](https://user-images.githubusercontent.com/60766925/114621662-5a9fc100-9c83-11eb-8ab5-383626e67763.png)
