### ISSUE TITLE
Erro ao criar novo serviço

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#104]
**Erro ao criar novo serviço**
Boa tarde Bruno. 
Ao criar uma nova O.S., após salvar, aparece a tela de erro (abaixo), porém, mesmo assim, a O.S é criada. 
Peço correção, por favor.

![image](https://user-images.githubusercontent.com/60766925/94464174-813d5500-0194-11eb-83a2-2317b5f3c72a.png)

**Comment by fullcontent** [comment]
Olá @castroli, bom dia!

Pode me passar o passo a passo de como surge o erro?
Em qual unidade está, e qual tipo de serviço está cadastrando...

**Comment by castroli** [comment]
Bom dia @fullcontent 
Este erro esta ocorrendo em uma nova empresa que criamos a "BRF Foods Brasil". Como descrito anteriormente, após criado a nova O.S gera uma tela de erro, porém, retornando a tela da unidade, nota-se que a O.S foi criada.

Imagem com os dados da undiade:
![image](https://user-images.githubusercontent.com/60766925/94684305-3f302280-02fe-11eb-8030-1eca1249b5e1.png)

Imagem criando a O.S.
![image](https://user-images.githubusercontent.com/60766925/94684402-671f8600-02fe-11eb-8257-60e6a9a55fd2.png)

Imagem do erro:
![image](https://user-images.githubusercontent.com/60766925/94684433-7272b180-02fe-11eb-8ec0-3c782d9a11f3.png)

Imagem da O.S criada mesmo após a tela de Erro.
![image](https://user-images.githubusercontent.com/60766925/94684608-a8179a80-02fe-11eb-9487-e19d30a28c22.png)

**Comment by fullcontent** [comment]
@castroli 

Pelo que vi na sua tela de cadastro, o campo valor total não foi preenchido. Pode ser que o problema esteja aí. 

Consegue fazer um teste preenchendo esse campo?

**Comment by castroli** [comment]
Bruno,
Vocês está correto, se incluir o valor da certo. E esta lógica esta corretissima, o valor é algo que não podemos dexar de preencher.
Creio que para não ocorrer mais isso, necessário fazer com que o sistema não crie a O.S sem o valor, mas ao tentar criar uma sem o preenchimento do campo, gere uma notificação, informando da necessidade.

**Comment by castroli** [comment]
@fullcontent , este chamado foi concluído, pode encerrar, por favor.
