### ISSUE TITLE
[BUG] Erro ao criar nova unidade 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#105]
Bruno, não estamos conseguindo criar uma unidade nova

Clicamos em "Unidades" > "Cadastrar" Selecionamos empresa "Renner" > Preenchemos todos os dados e ele dá a página de erro conforme abaixo:

Obs: Tentamos umas 3x ao longo do dia e com usuários diferentes e mesmo assim não deu. 

![image](https://user-images.githubusercontent.com/60766925/94621911-8af3b500-0287-11eb-81b9-4b6f6dc7502f.png)

**Comment by fullcontent** [comment]
@castroli 

O erro pode ter sido causado por falta de preenchimento em algum campo.

Já estou trabalhando na verificação dos Campos para cadastro e precisaria saber quais dados são indispensáveis para cadastrar a unidade. Conforme tínhamos conversado no início do projeto, era para se preencher todos os campos, se houver necessidade de alterar essa obrigatóriedade é só me passar quais campos devem ser obrigatório o preenchimento.

**Comment by castroli** [comment]
Entendi.
Os campos abaixo algumas vezes não temos a informação no momento de criar a empresa/ unidade, então pode alterar no sistema como opcional (tanta na criação da empresa como de unidades), para os demais campos, o preenchimento mantem obrigatório.

Inscriçao Estadual
Inscrição Municipal
Inscrção Imobiliária
Complemento
Matricula RI
Tipo do Imóvel
Área

**Comment by fullcontent** [comment]
@castroli 

Foi inserido a validação dos dados, peço testar por gentileza.

**Comment by castroli** [comment]
@fullcontent 
Realizei testes e esta correto, pode encerrar este chamado. 
Agradeço.
