### ISSUE TITLE
[BUG] Erro de permissão para usuário cliente

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#106]
Bom dia Bruno,
Ocorre que o sistema não está liberando acesso para visualizar as unidades da empresa citada, está liberando acesso apenas para visualizar os dados da empresa. 

Usuário: 
ClienteEspaçolaser Depilação | renata.molina@espacolaser.com.br

Tela listagem de unidades:
![image](https://user-images.githubusercontent.com/60766925/94688932-9df89a80-0304-11eb-9a06-b5d433af2a56.png)

Tela detalhes da empresa:
![image](https://user-images.githubusercontent.com/60766925/94688833-815c6280-0304-11eb-85b0-396782cfe30f.png)

Tela detalhes da unidade: Após clicar em qualquer undiade aparece a permissão.
![image](https://user-images.githubusercontent.com/60766925/94688950-a2bd4e80-0304-11eb-823b-ea983656017e.png)

**Comment by fullcontent** [comment]
@castroli 

Bom dia,

Fiz uma modificação na lógica que libera o acesso para os clientes e a principio resolveu esse problema de permissão.
Tive que alterar a senha do usuario para 123456, peço que mude novamente e faça um teste pra verificar se está tudo ok.

**Comment by castroli** [comment]
Boa tarde @fullcontent,
Fiz o teste e a princípio está tudo correto, agradeço.

**Comment by castroli** [comment]
@fullcontent , este chamado foi concluído, pode encerrar, por favor.
