### ISSUE TITLE
Melhoria no faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#109]
Bruno, 

- [x] Valor faturar x valor em aberto: 

Conforme falamos, para não gerar erros quanto ao valor a ser faturado, sugerimos criar uma lógica onde o "Valor Faturar" não pode ser supeirior ao "Valor em Aberto", caso seja incluido um valor superior, emitir um aviso e impossibilitar a sequência.

![image](https://user-images.githubusercontent.com/60766925/95128908-82402a80-0730-11eb-8007-85a2b2f436f5.png)

**Comment by castroli** [comment]
- [ ] Na listagem de resultado de busca do faturamento incluir uma coluna com o nome "Finalizado" que irá a data de finalização do serviço, incluir antes da coluna "COD".
![image](https://user-images.githubusercontent.com/60766925/102259437-debc8480-3eed-11eb-836a-6c2ecc758f39.png)

**Comment by castroli** [comment]
- [ ] Incluir a opção de filtro em todas as colunas no resultado da busca:
![image](https://user-images.githubusercontent.com/60766925/102259642-204d2f80-3eee-11eb-8ffd-498857467f95.png)

**Comment by castroli** [comment]
- [ ] Incluir um campo de pesquisa no resultado da busca.
![image](https://user-images.githubusercontent.com/60766925/102259836-61454400-3eee-11eb-8037-58956d9d8741.png)

**Comment by castroli** [comment]
- [ ] Incluir botão de editar o fatuamento ja gerado. O ideal seria dentro da opção de editar poder incluir e excluir itens e tambem editar os campos "Relatório de faturamento:" e "Referência".

![image](https://user-images.githubusercontent.com/60766925/105076232-8f77ef80-5a69-11eb-98bc-adca145d5d29.png)
![image](https://user-images.githubusercontent.com/60766925/105076643-12994580-5a6a-11eb-86ff-050c74f04539.png)

**Comment by fullcontent** [comment]
@castroli 

Peço testar por gentileza.

A função de editar os faturamentos é um pouco mais trabalhosa, vou abrir um novo chamado pra tratar somente dela. Dessa forma se o restante desse chamado estiver ok, pode fechar.

**Comment by castroli** [comment]
@fullcontent bom dia!
Testamos e esta apresentando um erro, segue abaixo. 

Ante a listagem estava aparecendo tudo em uma unica página (muito mais facil), agora esta aparecendo 10 por página, porém quando selecionamos alguns casos na página um e passamos para pagina seguinte, os itens anteriormente selecionados não vão para o relatório "resumo do faturamento". 
Peço corrigir e se possivel deixar 100 linhas por página. 
Pág 01
![image](https://user-images.githubusercontent.com/60766925/115252417-d37a9f00-a101-11eb-996f-865f9ab70a8f.png)

Pág 02
![image](https://user-images.githubusercontent.com/60766925/115252354-c8c00a00-a101-11eb-8648-0deca56e559a.png)
 Resumo do faturamento 
![image](https://user-images.githubusercontent.com/60766925/115252458-decdca80-a101-11eb-92f1-124ae57de837.png)
