### ISSUE TITLE
Arquivar e notificar serviço secundário

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#11]
- Quando finalizar um serviço secundario:

1. Criar um arquivo digital com o nome da OS + Nome do Serviço e salvar a licença.

2. Enviar um email notificando do arquivamento para o administrador e responsável

**Comment by fullcontent** [comment]
@castroli 

Escreva aqui pra mim o conteúdo que você quer no email!

**Comment by castroli** [comment]
O serviço foi finalizado e esta pronto para faturar.

**Comment by fullcontent** [comment]
Está funcional e aguardando testes.

**Comment by castroli** [comment]
Bruno, realizei teste e não funcionou nem o arquivamento automático nem o email informando a finalização do processo.

**Comment by fullcontent** [comment]
Vou refazer a lógica e testar novamente.

**Comment by fullcontent** [comment]
Diego, refiz os testes aqui e está arquivando o serviço no arquivo digital e gerando um novo serviço com o mesmo nome.

![image](https://user-images.githubusercontent.com/6120413/76271988-da758380-6258-11ea-81fd-30b725e972c6.png)
![image](https://user-images.githubusercontent.com/6120413/76272031-f711bb80-6258-11ea-9fcf-921548b8fe11.png)


Os envios de e-mail vão ser instalados na próxima atualização(v.1.2) que estou trabalhando. Previsão de instalação dessa versão é 02/04.

**Comment by castroli** [comment]
Ótimo, obrigado.
