### ISSUE TITLE
Usuário desconhecido

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#111]
@fullcontent , bom dia!

Notamos que ao criar/alterar uma pendência, na listagem de usuários esta aparecendo um nome desconhecido, peço verificar por favor.

![image](https://user-images.githubusercontent.com/60766925/99539318-d9baf280-298c-11eb-8269-70d711fbf195.png)

**Comment by fullcontent** [comment]
@castroli 

Como estamos com o formulário de login aberto a registro, é possível qualquer um acessar o sistema e criar um usuário. Esses usuários são criados com o perfil "Cliente" portanto não tem acesso aos dados do sistema.


Proponho as seguintes soluções:

1. Não habilitarmos o formulário de registro mais. Quando houver um cliente novo que deseja utilizar o sistema, terá que ser enviado um link para registro.

2. Os cadastros ficarão por conta de algum administrador e não disponibilizamos nenhum link ou acesso para registro.

**Comment by castroli** [comment]
@fullcontent , eu acho que o correto seria sempre a gente (adm da Castro) realizar o cadastro de novos usuários. Se for mais seguro via link, pode ser, mas de forma que o registro seja realizado pelo adm da Castro, se necessário, pode deixar apenas o meu usuário.
