### ISSUE TITLE
Erros com usuário Caroline

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#112]
@fullcontent bom dia!

- [ ] **ERRO 01:**
Ao acessar o sistema com o usuário "caroline@castroli.com.br" o sistema não carrega, fica o link "http://sistemacelic.net/admin/home" e uma tela em branco (imagem 01), este erro começou hoje.
Fiz um teste copiando o link "http://sistemacelic.net/admin/usuarios", nesta tela o usuário dela entra.
Com o meu usuário (diego@castroli.com.br) consegui acessar normalmente. 

- [ ] **ERRO 02:**
O usuário da Carol não esta acessando a pagina de "**Unidades**" (http://sistemacelic.net/admin/unidades) (imagem 02) e a **Dashbord** (http://sistemacelic.net/admin/home) (imagem 03), abaixo segue as telas.

IMAGEM 01
![image](https://user-images.githubusercontent.com/60766925/99801345-aacf8880-2b14-11eb-9a07-3504064c7a4f.png)

IMAGEM 02
![image](https://user-images.githubusercontent.com/60766925/99803327-03545500-2b18-11eb-8b53-bef2d90fff77.png)

IMAGEM 03
![image](https://user-images.githubusercontent.com/60766925/99803480-4b737780-2b18-11eb-9e34-78dcc25b8385.png)

**Comment by fullcontent** [comment]
![image](https://user-images.githubusercontent.com/6120413/99808427-9c3a9e80-2b1f-11eb-888b-f680f1c9e8ed.png)

Olá...
Foi solucionado o erro. 
Tive que alterar a senha dela para celic1234, peço que resete a senha antes de continuar utilizando.
