### ISSUE TITLE
REEMBOLSO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#113]
**Erro resutado da busca**
Ao realizar a busca por periodo, não está aparecendo o total de taxas pagas no periodo. Abaixo envio a relação das taxas pagas para empresa "Adiser Burger King" para usar como base.

![image](https://user-images.githubusercontent.com/60766925/101404087-e7410980-38b4-11eb-8f94-896baaa7d62d.png)

**Comment by fullcontent** [comment]
@castroli 

Foi alterado no passo um a inclusão das taxas mesmo que o serviço não esteja finalizado. Peço testar.

**Comment by castroli** [comment]
@fullcontent testamos e agora esta correto, agradeço.
