### ISSUE TITLE
Faturamento - Erro 02

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#114]
@fullcontent boa tarde!
Notamos que esta surgindo um novo erro no sistema de faturamentos. Ocorre que quando criamos uma O.S devemos preencher o campo com o "valor do serviço" (inclusive é o unico campo referente ao faturamento que aparece na tela de criação da O.S). Quando finalizamos a O.S e vamos faturá-la o valor em aberto esta ficando R$ 0.00. Estamos tendo que voltar no serviço, incluir manualmente o campo "Valor em aberto"  (que surge apenas após a criação da O.S) para somente depois de preenchido ao valor em aberto, que conseguimos realizar o faturamento. O ideal seria, ao criar a O.S, o sistema já copiar o valor total do serviço e jogar para o valor em aberto. Peço ajustar, por favor.

![image](https://user-images.githubusercontent.com/60766925/102241974-54b5f100-3ed8-11eb-954c-f7bf98c97856.png)
![image](https://user-images.githubusercontent.com/60766925/102242767-313f7600-3ed9-11eb-9f64-b797a62f4373.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido... peço testar por gentileza.

**Comment by castroli** [comment]
@fullcontent Teste realizado e erro corrigido. Agadeço.
