### ISSUE TITLE
[BUG] Erro ao criar uma O.S 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#115]
Bom dia @fullcontent ,
Abrindo uma nova O.S. escolho a opção do campo Tipo de "Licenças/Projetos não renovaveis", porém, na proxima tela ele passa automaticamente para "Licenças de Operação". O mesmo acontece se escolhermos "controle de taxas", peço verificar e corrigir por favor. 

Abraço.

![image](https://user-images.githubusercontent.com/60766925/103536700-c519b780-4e71-11eb-97a5-2548fd615e16.png)
![image](https://user-images.githubusercontent.com/60766925/103536742-d95db480-4e71-11eb-9447-5eaedc3d3706.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido
