### ISSUE TITLE
Maximizar "Taxa"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#116]
Bruno, 
Por gentileza, dentro de cada serviço, maximixar o botão "taxa". Atualmente ele está minimizado, sendo necessário clicar no "+" para abrir os detalhes das taxas. 

![image](https://user-images.githubusercontent.com/60766925/103799270-a2320380-5029-11eb-9b69-5575a0e46a19.png)

Obrigada!

**Comment by fullcontent** [comment]
@castroli

pode checar se está tudo certo com essa pendência?

**Comment by castroli** [comment]
@fullcontent era exatamente isso, agradeço. 
Vou encerrar este chamado.
