### ISSUE TITLE
Erro no Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#118]
@fullcontent 
Hoje notei um erro. 
Ocorre que ao montar o faturamento para o Banco Santander (periodo 31/10/20 a 19/01/21) ele esta constando um serviço de AVCB da Ag 3131 para faturar, porém este serviço esta em andamento. pode verificar por qual motivo eles esta indo para o relatório de faturamento.

![image](https://user-images.githubusercontent.com/60766925/105078615-05318a80-5a6d-11eb-8df4-0ff08c471908.png)

![image](https://user-images.githubusercontent.com/60766925/105078593-fcd94f80-5a6c-11eb-8b3b-bc31d65876d5.png)

**Comment by fullcontent** [comment]
@castroli 

Diego, ocorreu um erro de usabilidade... 

Quando discutimos a lógica dessa parte, tinhamos que utilizar uma variável que nos informasse a data em que o serviço foi finalizado. Essa variável está vindo das interações. No momento em que é alterado o status para finalizado.

Ocorreu que no serviço BS0217, a Diandra alterou o status para Finalizado e em seguida para Andamento.
Isso acabou dando um erro não previsto na lógica do faturamento.

![image](https://user-images.githubusercontent.com/6120413/105126552-c841b400-5abd-11eb-8f3e-804b7157df61.png)


Manualmente eu vou excluir essa interação, mas vamos ter que pensar em alguma outra maneira de não permitir que esse erro aconteça novamente.

**Comment by castroli** [comment]
@fullcontent Imagino que a lógica deve fixar um serviço apareça na listagem de faturamento somente quando o campo situação for igual a "Finalizado".

**Comment by castroli** [comment]
@fullcontent 
Hoje identifiquei mais um erro no faturamento, a O.S. BS0313 esta aparecendo - R$ 250,00 na coluna "em aberto", porém la na tela do serviço o valor esta R$ 0,00 (o correto). Peço verificar, por favor.
![image](https://user-images.githubusercontent.com/60766925/106671281-00042d80-658d-11eb-9552-2dbf19aae152.png)
