### ISSUE TITLE
Erro serviço OA0063 - PPCI

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#120]
@fullcontent 
Acorreu o mesmo erro que ja tivemos, meu acesso tinha expirado e como não sabia, cliquei na pendência para concluir.
Link da pagina com erro: http://sistemacelic.net/admin/servicos/1710

![image](https://user-images.githubusercontent.com/60766925/106953321-04595380-6711-11eb-86f2-c827de06e9c5.png)
![image](https://user-images.githubusercontent.com/60766925/106953728-792c8d80-6711-11eb-9011-2f7788c1f63f.png)

**Comment by fullcontent** [comment]
@castroli 

Foi resolvido o problema adicionando uma regra pra evitar esse tipo de erro futuro.
