### ISSUE TITLE
Reembolso - Erros / Melhoria 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#125]
- [x] 01 MELHORIA:

@fullcontent 
Identificamos uma situação que necessita de de ajustes/melhoria, segue detalhamento.
Geramos o reembolso citados abaixo. 
[Oceanic Restaurantes - 002-2021.pdf](https://github.com/fullcontent/sistemacelic/files/6079359/Oceanic.Restaurantes.-.002-2021.pdf)

Após reembolso gerado, se selecionarmos o mesmo periodo, não consta em local algum a informação que estes valores já entraram em um relatório de reembolso (imagem abaixo). 
No faturamento por exemplo, quando acorre o detalhado acima, o valor em aberto fica zerado, isso é uma forma de identificarmos que ja foi faturado. Imagino que no reembolso poderia usar a mesma lógica.

![image](https://user-images.githubusercontent.com/60766925/109876612-c0466980-7c50-11eb-88df-f15696270d3c.png)

**Comment by castroli** [comment]
ERRO REEMBOLSO:

- [ ] Identificamos o seguinte erro:

Conforme tela abaixo este serviço (Ordem de serviço: AC0577) possui 4 taxas de publicidades, todas vencidas (imagem 01) sem pagamento. Ocorre que ao gerar o relatório  de reembolso (imagem 02) estas taxas estão sendo listadas, isso esta errado, pois como não foram pagas, não devem ir para reembolso. 
Outra coisa que me chamou atenção neste caso é que mesmo sem carregar o comprovante o campo "Data de Pagamento" esta preenchido e sempre com a data do dia de hoje (imagem 03), exemplo, na imagem 03 esta constando o dia de hoje 03/03, se entrar amanha, irá constar 04/03. 
Peço corrigir, por favor.
**Imagem 01**
![image](https://user-images.githubusercontent.com/60766925/109878330-e836cc80-7c52-11eb-8a95-8b4ecf94ca24.png)
**Imagem 02**
![image](https://user-images.githubusercontent.com/60766925/109878565-321fb280-7c53-11eb-9637-f603ff1aa04a.png)
**Imagem 03**
![image](https://user-images.githubusercontent.com/60766925/109878878-9e9ab180-7c53-11eb-9ed6-325ae31e797c.png)

**Comment by castroli** [comment]
ERRO REEMBOLSO 02:
- [ ] Identificamos o seguinte erro:
Na Ordem de serviço: AC0572 ocorreu que foi carregado comprovante e esqueceram se preencher o campo "Data de pagamento". Ocorre que o sistema preencheu automaticamente, porém com a data do dia atual. Resumindo, se eu entrar no sistema hoje 03/03 ira constar a data de hj, se eu entrar amanha, irá contar a data de 04/03. Para resolver este problema, imagino que o ideal seria criar uma lógica onde anexar o comprovante o campo data de pagamento se torne obrigatório, sem ele, não é possivel sequenciar (excluir a opção do sistema incluir automaticamente). 
![image](https://user-images.githubusercontent.com/60766925/109879906-043b6d80-7c55-11eb-88a2-6034f3ca319b.png)

**Comment by castroli** [comment]
ERRO REEMBOLSO 03: 
- [ ] Identificamos o seguinte erro:
Ainda na "Ordem de serviço: AC0572", inserimos na data de hoje o boleto e comprovante com data de pagamento de 02/02/2021. Ao gerar o relatório de reembolso com periodo de 01/02/2021 a 28/02/2021, notamos que esta taxa não foi incluida na listagem, porem ressalto que no campo data de pagamento incluimos o dia de 02/02/2021. Resumindo, imagino que o sistema não esta puxando desta data, correto? Caso positivo, informo que o correto é puxar combase a data do pagamento. Peço corrigir.
![image](https://user-images.githubusercontent.com/60766925/109880382-9fccde00-7c55-11eb-863a-e4138158ded9.png)
![image](https://user-images.githubusercontent.com/60766925/109880389-a22f3800-7c55-11eb-9bc5-4a256ef49974.png)
![image](https://user-images.githubusercontent.com/60766925/109880488-c1c66080-7c55-11eb-9e30-f5eb9d842b08.png)

**Comment by fullcontent** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Melhorias](https://trello.com/c/vPGoZqfo/1-melhorias)

**Comment by fullcontent** [comment]
- Foi retirado da listagem as taxas que já foram incluídas em algum relatório de reembolso.
- O filtro de busca foi corrigido para não listar taxas que não tenham sido pagas.
- Corrigido a busca pela data de pagamento das taxas

**Comment by castroli** [comment]
@fullcontent 
Esta apresentando o seguinte erro:
Se quando cadastro uma nova taxa e incluo o comprovante ja no momento do cadastro, e manualmente incluo a data do pagamento, ele vai para o relatório de reembolso, porém, se cadastrarmos primeiramente a taxa com o boleto em anexo, e depois retornar para apenas anexar o comprovante verificamos dois erros:

- [ ] Não salva a data do pagamento, e sim a data de =hoje;

- [ ] Ao gerar o relatório do reembolso, esta taxa não aparece.

**Taxa teste 01:** Cadastrarmos primeiramente a taxa com o boleto em anexo, e depois retornei para apenas anexar o comprovante, resultado, não aparece no relatório de reembolso.
![image](https://user-images.githubusercontent.com/60766925/116316474-62ce2500-a788-11eb-95ef-4a5ac1f9f125.png)
![image](https://user-images.githubusercontent.com/60766925/116316490-68c40600-a788-11eb-9ed3-66464f7884c3.png)


**Tela taxa 02:** Inclui o comprovante já no momento do cadastro e manualmente incluí a data do pagamento, resumindo, aparece no relatório de reembolso.
![image](https://user-images.githubusercontent.com/60766925/116316511-724d6e00-a788-11eb-8221-0232e5509926.png)

**Comment by fullcontent** [comment]
@castroli 

Feita as correções conforme o vídeo enviado.
Funcionando com meu usuario... 

Caso esteja tudo ok, podemos encerrar esse chamado.

**Comment by castroli** [comment]
@fullcontent testei e e foi corrigido, apenas surgiu um novo erro, conforme tela abaixo no, após salvo ao entrar na tela de taxas novamente não esta aparecendo a data do pagamento, peço ajustar.

Teste 01- Não mostra o dia do pagamento:
![image](https://user-images.githubusercontent.com/60766925/116762247-3583b000-a9f0-11eb-98e1-b2cdc575393a.png)

**Comment by fullcontent** [comment]
@castroli 

Foram feitos algumas modificações na lógica e acrescentado algumas melhorias.

Quando há um comprovante ou boleto, pode-se remover.
A data de pagamento está ajustando corretamente agora.

Peço testar por gentileza. Caso tenha alguma melhoria, favor reabrir esse chamado.

**Comment by castroli** [comment]
@fullcontent não consegui reabrir este chamado, então criei um novo com o numero 155.
