### ISSUE TITLE
Disparo de email quando um usuário for mencionado nas interações.

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#128]
Quando indicar um responsável diferente do seu na pendência, disparar um email padrão informando da pendência criada, o ideal seria que neste email ja tenha um link direto para a tela da pendência no CELIC. (@castroli irá criar o modelo de email desejado)

**Comment by fullcontent** [comment]
- [ ] Configurar servidor de email Locaweb
- [ ] Testar disparo de emails via sistema
- [ ] Configurar mensagem automática na notificação
- [ ] Testar

**Comment by fullcontent** [comment]
@castroli 

Finalizado no ambiente de testes, favor testar em campo com os usuários.

**Comment by fullcontent** [comment]
Erro servidor locaweb...

**Comment by fullcontent** [comment]
Corrigido erro locaweb;

**Comment by fullcontent** [comment]
@castroli 

Implementado o disparo de emails... Favor testar com os usuários...

**Comment by castroli** [comment]
@fullcontent 
Testes realizados e com suscesso, a princípio não apresentou erros.

**Comment by castroli** [comment]
@fullcontent 
Notei apenas um erro, os usuários "cliente" não estão conseguindo mensionar niguem na interação, coloco o @ e ele não puxa nenhum usuário. Se eu escrever algo e enviar da tela de erro.

![image](https://user-images.githubusercontent.com/60766925/113730285-226e1080-96ce-11eb-8155-7c22e6a4de73.png)

Tela erro:
![image](https://user-images.githubusercontent.com/60766925/113730649-724cd780-96ce-11eb-84a0-d7e0e5b9c46d.png)
