### ISSUE TITLE
Anexar mais de um arquivo na pendência.

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#129]
image
 Incluir a opção de anexar mais de 1 aquivo no campo pedência.

**Comment by fullcontent** [comment]
- [ ] Ao anexar voltar para a pagina do serviço
- [ ]

**Comment by fullcontent** [comment]
@castroli peço testar por gentileza.

**Comment by castroli** [comment]
@fullcontent 
Testei com o usuário da Aline e foi possivel anexar mais de um arquivo, porem com o usuário cliente apareceu a pagina de erra citada abaixo. 
http://sistemacelic.net/cliente/arquivo/anexar
![image](https://user-images.githubusercontent.com/60766925/116313339-06690680-a784-11eb-8b33-f268b29f9c2a.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido

**Comment by castroli** [comment]
@fullcontent estou fazendo o teste com um usuário cliente e apresenta o seguinte erro, na Daschboard do usuário cliente até aparece a pendencia (imagem 01) porém, ao clicar nela é direcionado para a tela do serviço, porem o quadro de pendências não aparece (imagem 02). Peço corrigir.

**Imagem 01**
![image](https://user-images.githubusercontent.com/60766925/116761946-54357700-a9ef-11eb-92da-f576d5a206b9.png)


**Imagem 02**
![image](https://user-images.githubusercontent.com/60766925/116762044-9f4f8a00-a9ef-11eb-98c4-0aaf30d3b5dd.png)

**Comment by fullcontent** [comment]
@castroli

Corrigido

**Comment by castroli** [comment]
Bruno,
Confirmo que foi corrigido o erro apontado anteriormente, porém, gerou um novo problema, novamente apenas com o usuário cliente. Ocorre que após anexado o primeiro arquivo a opção de anexar não aparece mais. Para solucuionar isso creio que deveria corrigir a lógica apenas no sentido de manter a opção de anexar, mesmo que a pendencia ja não é mais dele (lembrando que após anexar o 1º arquivo, automaticamente o sistema devolve a pendência para o responsavel pela criação dela).

Imagem 01:
![image](https://user-images.githubusercontent.com/60766925/117190210-85c68d80-adb5-11eb-9e95-a148e6ae5d97.png)

**Comment by fullcontent** [comment]
@castroli

corrigido e liberado para anexo.
Pode encerrar o chamado se estiver tudo ok.!

**Comment by castroli** [comment]
@fullcontent agora sim, estou encerrando este chamado.
