### ISSUE TITLE
Ajustar exibição de relatório completo de serviços.

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#131]
Erro no servidor Locaweb na exibição do relatório completo.

**Comment by castroli** [comment]
@fullcontent,

- [ ] **Peço incluir mais estes campos no relatório, por favor.**

1. Situação
2. Valor Total
3. Valor em Aberto
4. N. Protocolo
5. Emissão Protocolo
6. Tipo de Licença

- [ ] **Peço manter o relatório com a seguinte ordem de colunas:**

1. Razão Social
2. Código
3. Nome
4. CNPJ
5. Status
6. Imóvel
7. Ins. Estadual
8. Insc. Municipal
9. Inscrição Imobiliária
10. Matricula RI
11. Área da Loja
12. Endereço
13. Número
14. Bairro
15. Complemento
16. Cidade/UF
17. CEP
18. Tipo
19. Ordem de serviço
20. Situação
21. Responsável
22. Serviço
23. Solicitante
24. N. Protocolo
25. Emissão Protocolo
26. Tipo de Licença
27. Emissão Licença
28. Vencimento Licença 
29. Valor Total
30. Valor em Aberto

**Comment by fullcontent** [comment]
@castroli 

Peço testar por gentileza.

**Comment by castroli** [comment]
Showww, vou encerrar esta.
