### ISSUE TITLE
Editar Faturamento

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#135]
Incluir botão de editar o fatuamento ja gerado.
O ideal seria dentro da opção de editar poder incluir e excluir itens e tambem editar os campos "Relatório de faturamento:" e "Referência".

- [ ] Inserir botão de edição
- [ ] Recuperar dados dos faturamentos gerados com seus respectivos serviços
- [ ] Habilitar inclusão e exclusão de serviços (Estudar melhor forma)
- [ ] Salvar edição

**Comment by fullcontent** [comment]
- [ ] Excluir os dados e o faturamento e direcionar para o passo 2 com o periodo e os serviços já selecionadas;

**Comment by castroli** [comment]
@fullcontent 
Penso que como está hoje não precisamos de novas alterações, caso necessário abro um novo chamado no futuro, vou encerrar este.
