### ISSUE TITLE
Redirecionar para criação de pendência ao criar um novo serviço.

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#136]
@fullcontent 
Voltando com este tema, não seria possivel criar uma regra que após criado a demanda o sistema direcione para página de "cadastrar pendência" (imagem 03). Com isso creio que já iremos minimizar um possivel esquecimento. 
Atualmente esta direcionando da imagem 01 para imagem 02.
**Imagem 01**
![image](https://user-images.githubusercontent.com/60766925/106676236-3fcf1300-6595-11eb-96ec-ea60e9d8c7d1.png)
**Imagem 02**
![image](https://user-images.githubusercontent.com/60766925/106676264-4bbad500-6595-11eb-8fae-b63569cc4966.png)
**Imagem 03**
![image](https://user-images.githubusercontent.com/60766925/106676318-69883a00-6595-11eb-9656-dd6d5253017a.png)

_Originally posted by @castroli in https://github.com/fullcontent/sistemacelic/issues/79#issuecomment-772089294_

**Comment by fullcontent** [comment]
@castroli 

Finalizado, qualquer problema é só reabrir o chamado.

**Comment by castroli** [comment]
@fullcontent Fiz o teste e após criar um novo serviço, o sistema continua direcionando da para imagem 02. O solicitado é que após criado a pendencia o sistema direcione para página de "cadastrar pendência" (imagem 03)
