### ISSUE TITLE
Erro serviços a vencer

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#137]
@fullcontent
Notamos o quadro de "Serviços a vencer" esta sempre com 0"zero", porem, ao clicar constam alguns serviços, isso ocorre para todos os usuários, peço corrigir.

Imagem 01
![image](https://user-images.githubusercontent.com/60766925/116247379-2b885580-a741-11eb-905c-f178ae175192.png)

Imagem 02
![image](https://user-images.githubusercontent.com/60766925/116247407-32af6380-a741-11eb-9a28-99bbd59a97f1.png)

**Comment by fullcontent** [comment]
@castroli 

Acredito que esse problema já tinha sido resolvido em outro chamado. Caso nao tenha sido solucionado é só reabrir.
