### ISSUE TITLE
Botão de cadastro Laudo

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#139]
Inserir botões de cadastro de laudo, protocolo e licença diretamente na tela do serviço, sem precisar editar.

**Comment by castroli** [comment]
@fullcontent
pensando em minimizar possiveis erro interno, peço desconsiderar quando ao botão para incluir licença. Manter apenas , "Inserir botões de cadastro de laudo e protocolo diretamente na tela do serviço, sem precisar editar".

**Comment by fullcontent** [comment]
@castroli 

Inserido botões de cadastro. Peço testar e reabrir o chamado para qualquer problema!
