### ISSUE TITLE
Notificações de pendências

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#14]
- [ ] Quando o responsável pela pendência for o cliente, o mesmo recebe uma notificação sobre a pendência.

- [ ] O cliente responde se a pendência foi resolvida ou não e a resposta vai para o responsável sobre a pendência em forma de notificação.

- [ ] Notificar o cliente caso ocorra alguma mudança na data limite da pendência.

### Respostas possíveis:

> Sim,
> 
> Resolvido e enviado por email.
> Resolvido e não enviado

> Não.
> 
> Aguardando terceiros.
> Será resolvido em breve.
> Necessito auxilio
>

**Comment by castroli** [comment]
A princípio creio ser apenas estas opções mesmo.
