### ISSUE TITLE
Nomear arquivos

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#141]
Corrigir download de arquivos com essa sintaxe:

"Código da unidade" "Nome da unidade" - "Nome da O.S" Vencimento licença".

**Comment by fullcontent** [comment]
@castroli 

A princípio o download está funcionando corretamente.


Podes enviar novamente esse print por gentileza, mas de forma que eu consiga ver o endereço na barra do navegador?
![image](https://user-images.githubusercontent.com/6120413/116610643-e2383180-a90b-11eb-8158-3684e8d6bb7e.png)

**Comment by castroli** [comment]
@fullcontent quanto ao download não ha problemas, peço uma melhoria quanto a "nomenclatura". Lembro que no inicio do CELIC quando iamos salvar um arquivo/anexo do sistema, ele ja vinha com uma nomenclatura padrão, hoje está vindo uma numeração(tela abaixo), seria possivel ajustar isso. O ideal seria se seguisse a seguinte lógica:
"Código da unidade" "Nome da unidade" - "Nome da O.S" Vencimento licença".
Exemplo:
001 Aquário BC - Alvará Sanitário 31-12-2020
![image](https://user-images.githubusercontent.com/60766925/116761187-539be100-a9ed-11eb-9e9a-fbbf9400aee5.png)

**Comment by fullcontent** [comment]
@castroli 

Em qual momento está sendo gerada essa nomenclatura?

De fato, o nome do arquivo que é guardado no servidor tem essa nomenclatura em código para evitar repetições, porém quando é clicado no botão download, o arquivo automaticamente é salvo com a logica pedida.

Peço que envie os passos que foram feitos até chegar nesse momento do nome do arquivo em codigos.

**Comment by castroli** [comment]
@fullcontent 
Notei que esta nomeando automaticamente apenas quando feito o download do campo "arquivo digital". Se por exemplo, fizer um download de um documento que esta no quadro de "Projetos/Licenças - não renováveis" ou "Licenças de Operação" vai vir com a numeração apenas. 
Segue telas:

Imagem 01- 
![image](https://user-images.githubusercontent.com/60766925/117190992-7136c500-adb6-11eb-9705-3751c63663d3.png)

Imagem 02
![image](https://user-images.githubusercontent.com/60766925/117191023-798f0000-adb6-11eb-9650-30c4b7b5fb87.png)

Imagem 03 
![image](https://user-images.githubusercontent.com/60766925/117191032-7dbb1d80-adb6-11eb-9db9-3c4e8356ec9b.png)

Imagem 04 
![image](https://user-images.githubusercontent.com/60766925/117191048-827fd180-adb6-11eb-8d5f-735af66b807d.png)

**Comment by fullcontent** [comment]
@castroli

Foi ajustado a nomenclatura dos arquivos dentro da tela do serviço.

Os arquivos serão nomeados inserindo o prefixo "Laudo, Protocolo ou Licença".

Peço testar e caso precise algum ajuste, só reabir esse chamado.
