### ISSUE TITLE
Detalhes do serviço

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#145]
@fullcontent 
Anteriormete haviamos solicitado para que quando o "Tipo da licença" for "Não aplicado", remover tambem o campo "Emissão da licença", ok vi que providenciou, porém agora não esta aparecendo nada quanto ao "Tipo da licença". Assim como quando é definitiva, peço fazer neste caso aparecer o campo "Tipo da licença: Não aplicado".

![image](https://user-images.githubusercontent.com/60766925/116759978-1da92d80-a9ea-11eb-8012-84d669256d13.png)

**Comment by fullcontent** [comment]
@castroli 

Ficou um pouco confuso a explicação:

"Assim como quando é definitiva, peço fazer neste caso aparecer o campo "Tipo da licença: Não aplicado"."

Atualmente se o tipo da licença for Não Aplicado, nao será exibida a data de Emissão.
Se for renovável, vai aparecer a Validade.


Me explica melhor qual é a necessidade...

**Comment by castroli** [comment]
@fullcontent 
Ocorre que quando trata-se de uma licença que o "Tipo de Licença" é "Não aplicada" na tela de "Detalhes do serviço" não consta o campo com a informação "Tipo de Licença: Não aplicada", (_exemplo tela 01_), peço fazer constar.
Por exemplo, quando "Tipo de Licença" é "Renovável" ou "Definitiva" na tela de "Detalhes do serviço" aparece o campo "Tipo da Licença: Renovável" ou "Tipo da Licença: Definitiva" (_exemplo tela 02 e 03_).
Gostaria de fazer constar o mesmo para "Não aplicada".

-Tela 01
![image](https://user-images.githubusercontent.com/60766925/121931095-87229880-cd19-11eb-854f-742afb83c48c.png)

-Tela 02
![image](https://user-images.githubusercontent.com/60766925/121931879-8f2f0800-cd1a-11eb-84da-1f1d05e103fc.png)

-Tela 03
![image](https://user-images.githubusercontent.com/60766925/121932309-1ed4b680-cd1b-11eb-9640-e08bd3a6f9c3.png)

**Comment by fullcontent** [comment]
@castroli 

Entendido... atualização feita... qualquer coisa só reabrir o chamado.
