### ISSUE TITLE
Erro campo histórico

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#150]
@fullcontent 
Inclui hoje uma informação no campo histórico e automaticamente esta informação passou também para o campo "interação", creio que seja devido ao @. Peço corrigir, por favor.

http://sistemacelic.net/admin/servico/2897/interacoes
Encaminhado email a FAMAB (famab@bombinhas.sc.gov.br) solicitando a “consulta prévia de viabilidade ambiental“ , com base neste documento teremos ciencia quanto a necessidade do licenciamento ambiental.
![image](https://user-images.githubusercontent.com/60766925/118858365-782dff00-b8af-11eb-83aa-1fdee7e119b1.png)

**Comment by fullcontent** [comment]
@castroli 

Peço testar e reabir o chamado caso o problema persista.
