### ISSUE TITLE
Usuário cliente

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#151]
@fullcontent 
Estou com o usuário cliente "leandro.sena@espacolaser.com.br" e ao tentar acessar um serviço que não tem pendência cadastrata (um serviço finalizado por exemplo) está apresentando tela de erro, peço corrigir.

Tela 01
![image](https://user-images.githubusercontent.com/60766925/119052331-d4218200-b99a-11eb-8b0b-ac09cf131483.png)
Tela 02 - Erro
![image](https://user-images.githubusercontent.com/60766925/119052349-d84d9f80-b99a-11eb-8f7f-6ef499ee94a3.png)

**Comment by fullcontent** [comment]
@castroli 

Peço testar, caso o problema persista é só reabrir o chamado!
