### ISSUE TITLE
Ajuste nos botões 

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#154]
Relizar o seguinte um ajuste visual:
Alterar botão "editar" para "salvar" na tela de edição do serviço, unidade, empresa, pendência, taxas, relatórios, etc.

**Comment by castroli** [comment]
- [ ] Tela "**Editar serviço**": Alterar de "SALVAR" para "Salvar".
![image](https://user-images.githubusercontent.com/60766925/124832226-b7dda280-df52-11eb-8eab-afe98996de3c.png)

- [ ] Tela "**Editar empresa**" ainda pendente: Alterar botão "editar" para "salvar"
![image](https://user-images.githubusercontent.com/60766925/124832163-9e3c5b00-df52-11eb-8ba1-0aff1ad0d5b0.png)

- [ ] Tela "**Editar unidade**" ainda pendente: Alterar botão "editar" para "salvar"
![image](https://user-images.githubusercontent.com/60766925/124832394-01c68880-df53-11eb-8047-9ebd87d578e9.png)

- [ ] Tela "**Editar pendencia**" ainda pendente: Alterar botão "editar" para "salvar". 
- [ ] Aproveita e corrigi também a palavra "**pendencia**" para  "**pendência**".
![image](https://user-images.githubusercontent.com/60766925/124832508-291d5580-df53-11eb-82f5-97e1c225b947.png)

- [ ] Tela "**Cadastrar taxa**" ainda pendente: Alterar botão "editar" para "salvar"
![image](https://user-images.githubusercontent.com/60766925/124832588-3e927f80-df53-11eb-828d-572dfde1f763.png)

**Comment by castroli** [comment]
@fullcontent 
Vi que alterou a nomenclatura dos botões, porém incluiu td em caixa alta (SALVAR), peço corrigir e manter todos como "Salvar" (seguindo o mesmo padrão dos demais).

**Comment by fullcontent** [comment]
@castroli Corrigido

**Comment by castroli** [comment]
Agora sim, obrigado.
