### ISSUE TITLE
Erro taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#155]
@fullcontent 

- [x] O Erro citado no chamado 125 "03 ERRO REEMBOLSO" permanece.

Na Ordem de serviço: BS0380 ocorreu que foi carregado comprovante e esqueceram se preencher o campo "Data de pagamento". Ocorre que o sistema preencheu automaticamente, porém com a data do dia atual. Resumindo, se eu entrar no sistema hoje 27/05 ira constar a data de hj, se eu entrar amanha, irá contar a data de 28/05. 
Creio que o melhor a ser feito é, quando anexado o comprovante, este campo se torne obrigatório o preencimento (assim como fez quando vamos cadastrar um novo serviço é obrigatório o valor) de forma manual. Exclua a opção do sistema completar a data automaticamente.

http://sistemacelic.net/admin/taxas/1086

![image](https://user-images.githubusercontent.com/60766925/119905986-a9e43d00-bf23-11eb-8934-b0312e4e94d9.png)

- [x] **IMPORTANTE:** Quanto as taxas que o sistema esta atualmente preenchendo automaticamente, peço colocar uma data aleatória (retroativa), para não ficar constando a data de hoje, pois isso irá gerar erros nos futuros reembolsos.

**Comment by castroli** [comment]
@fullcontent Teste realizado, era isso mesmo, obrigado.

**Comment by fullcontent** [comment]
@castroli 

Corrigido
