### ISSUE TITLE
Melhoria tela serviço e unidade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#158]
@fullcontent 
Peço realizar as seguintes melhorias:
- [x] Estou na tela do serviço, ao clicar no nome da unidade fazer voltar para a tela "Detalhes da unidade"

Tela 01
![image](https://user-images.githubusercontent.com/60766925/119907439-a69e8080-bf26-11eb-9bf9-8e753e35e98b.png)
Tela 02
![image](https://user-images.githubusercontent.com/60766925/119907490-c59d1280-bf26-11eb-9c4e-9854ccc7011e.png)

- [x] Na tela de "Detalhes da unidade" incluir a opção de editar unidade.
![image](https://user-images.githubusercontent.com/60766925/119907583-f9783800-bf26-11eb-8913-79271eeccac1.png)

**Comment by fullcontent** [comment]
@castroli 

Feito!
