### ISSUE TITLE
Melhoria lista de unidades

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#159]
@fullcontent 

- [ ] Incluir na tela "Listagem de unidades" coluna com a descrição "Empresa" com o nome fantasia das empresas (antes da coluna "cod.").

![image](https://user-images.githubusercontent.com/60766925/119907798-74d9e980-bf27-11eb-80e9-fe40348ff356.png)

**Comment by fullcontent** [comment]
@castroli 

atualizado

**Comment by castroli** [comment]
@fullcontent 
Notei que mudou a coluna "Nome fantasia", na verdade não era isso, gostaria de manter esta coluna onde estava e incluir antes da coluna "Cod."uma coluna com o nome da "Empresa" (Santander, Pague Menos, Espaçolaser, Adiser Burger King e etc.). Qualquer duvida me chame no Whatsapp.

**Comment by fullcontent** [comment]
@castroli 

Corrigido.
