### ISSUE TITLE
Arquivar serviços primários

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#16]
Quando iniciar uma renovação de uma demanda primária já existente, passar o arquivo digitalizado (licença) e as taxas vinculadas a esta licença (O.S) automaticamente para o arquivo digital. 
A ideia disso é que quando olhamos a lista dos "serviços primários" as licenças não se repetem e também com isso não perderemos o arquivo digital da ultima licença.

- Exemplo: 
O BK 085 Floripa Airport tem hoje 4 serviços primários (Alv. de Funcionamento, Sanitário, AVCB e Polícia). Consideramos que iremos iniciar a renovação do AVCB, necessário o sistema automaticamente clonar e arquivar a O.S. atual e criar uma cópia da licença no arquivo digital.
Com isso ficará disponível para o cliente visualizar esta licença antiga e na O.S que estará em andamento ficará as informações e o arquivo digital da licença atualiza que iremos emitir.  

- [x] Duplicar o serviço

- [x] Arquivar a licença no arquivo digital

- [x] Arquivar as taxas

**Comment by fullcontent** [comment]
Testar a funcionalidade e fechar.

**Comment by fullcontent** [comment]
- [ ] Duplicar o serviço

- [ ] Arquivar a licença no arquivo digital

- [ ] Arquivar as taxas
