### ISSUE TITLE
Anexos

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#161]
@fullcontent 
Notamos que de alguns dias pra cá que ao clicar em qualquer arquivo anexado ao CELIC automaticamente ele faz o download, antes ele abria em outra aba para visualizar e se desejavel, faziamos o download, peço ajustar.

**Comment by fullcontent** [comment]
@castroli 

Foi feito o ajuste na aba de Arquivo Digital. 
Os demais links estão configurados para abrir em nova aba sempre, porém dependendo do navegador essa função pode não funcionar corretamente. 

Se caso tiver algum link com esse problema, pode reabrir esse chamado com um print pra eu analisar.

**Comment by castroli** [comment]
@fullcontent 
Fiz os testes e continua fazendo o download automatico, vou listar quais campos que estão fazendo o download automatico e quais não estão.

**Download automatico:**
Tela detalhes do serviço:
- Emissão Documento
- Laudo
- Protocolo
Arquivo digital
- Arquivos do arquivo digital

**Visualizando:**
Taxas (boleto e comprovante)


![image](https://user-images.githubusercontent.com/60766925/121972171-ccae8800-cd50-11eb-9e02-3552d044d39b.png)
![image](https://user-images.githubusercontent.com/60766925/121972203-dc2dd100-cd50-11eb-841f-80d0d15d2fb1.png)

**Comment by castroli** [comment]
Bruno, notei que este chamado foi atendido, irei encerrá-lo.
