### ISSUE TITLE
Botão de exclusão

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#163]
@fullcontent 
Notamos que quando carregamos arquivos nos três campos citados abaixo não temos a opção de excluí-los, peço incluir dentro da tela "editar serviço" um botão com esta opção (se possivel, ao lado de cada campo).

Tela "Editar serviço"
- Laudo de exigências;
- Protocolo;
- Documento Licença

![image](https://user-images.githubusercontent.com/60766925/120564379-24f49a00-c3e1-11eb-8355-3616e8c4d98c.png)

**Comment by fullcontent** [comment]
@castroli 

Peço testar por gentileza
