### ISSUE TITLE
Erro reembolso

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#165]
Bruno,

Identificamos mais este erro no reembolso, notamos que algumas taxas não estão aparecendo no reembolso, abaixo envio 2 exemplos.
**Espaçolaser loja 413 | Rio Pequeno**, temos uma taxa de AVCB paga em 24/05/2021 porém geramos um relatório comvários periodos e nenhum contam esta taxa, ressalto que a opção de reembolso esta "sim".
link:
http://sistemacelic.net/admin/servicos/2824
![image](https://user-images.githubusercontent.com/60766925/121237315-4d5f1700-c86d-11eb-8cb4-e553a46e5d05.png)
![image](https://user-images.githubusercontent.com/60766925/121237446-72538a00-c86d-11eb-95d6-4cc704c69b91.png)
![image](https://user-images.githubusercontent.com/60766925/121237361-5a7c0600-c86d-11eb-8272-5bbf5d2ab307.png)
 
**Espaçolaser loja B501 | Shopping São Luis**, taxa de RRT, paga em 17/05/2021, tambem não esta aparecendo no relatório.
http://sistemacelic.net/admin/servicos/2940
![image](https://user-images.githubusercontent.com/60766925/121237864-e130e300-c86d-11eb-9a2f-2264fc6b2287.png)

O mesmo esta acontecendo com as lojas B504 (http://sistemacelic.net/admin/servicos/2939) taxa de RRT e loja A803 (http://sistemacelic.net/admin/servicos/2772) taxa de AVCB.

**Comment by fullcontent** [comment]
@castroli 

Fiz o teste aqui com as unidades descritas, e pelo menos no meu usuário apareceu as taxas informadas:

Seriam essas taxas aqui?

![image](https://user-images.githubusercontent.com/6120413/121903203-70bb1380-ccfe-11eb-9675-27b18900dad9.png)

![image](https://user-images.githubusercontent.com/6120413/121903247-7c0e3f00-ccfe-11eb-9b55-57f76ee9739c.png)

![image](https://user-images.githubusercontent.com/6120413/121903667-e9ba6b00-ccfe-11eb-8a00-67c2943e60e8.png)



Tem algum outro momento em que acontece esse erro?
Pelo que analisei, o que está acontecendo é o lance do tempo de carregamento, do relatório. Estou trabalhando numa melhoria disso, fazendo uma nova lógica para pegar a data de captura da finalização do serviço. 

Está sendo feito no chamado #142 .

**Comment by castroli** [comment]
@fullcontent 
As taxas que aparece são outras, abaixo segue parecer detalhado.

- [ ] **Loja 413 Rio Pequeno**, a taxa que está aparecendo no relatório é referente ao serviço "RRT AVCB" (http://sistemacelic.net/admin/servicos/3084) , a taxa que não está aparecendo é do serviço de AVCB (http://sistemacelic.net/admin/servicos/2824).
![image](https://user-images.githubusercontent.com/60766925/121928758-dc10df80-cd16-11eb-99ce-a2967143f58b.png)

- [ ] **Loja b501 Shopping São Luis**, a taxa que está aparecendo no relatório é referente ao serviço "AVCB" (http://sistemacelic.net/admin/servicos/1760) , a taxa que não está aparecendo é do serviço de "RRT AVCB" (http://sistemacelic.net/admin/servicos/2940).
![image](https://user-images.githubusercontent.com/60766925/121929092-39a52c00-cd17-11eb-8431-7740f0e06fb2.png)

- [ ] **Loja b501 Shopping São Luis**, a taxa que está aparecendo no relatório é referente ao serviço "AVCB" (http://sistemacelic.net/admin/servicos/1760) , a taxa que não está aparecendo é do serviço de "RRT AVCB" (http://sistemacelic.net/admin/servicos/2940).

Quanto a ultima pergunta, acho que com esta explicação ja fica mais claro, pois continua não aparecendo as taxas citadas.

Abraço.

**Comment by fullcontent** [comment]
@castroli 

Consegui detectar o erro.

Acontece o seguinte: 

As taxas não estão aparecendo nessa listagem por já terem sidas adicionadas a um reembolso.
Isso foi pedido no chamado #125, para não constar as taxas que já foram reembolsadas.

Nesse caso precisamos definir uma nova lógica, ou simplesmente excluir o reembolso dessas taxas.

**Comment by castroli** [comment]
@fullcontent
Então esta certo, acho interessante apenas pensarmos em algo que consigamos deferenciar as taxas ja reembolsadas. Mas a lógica neste caso está correta.

**Comment by fullcontent** [comment]
@castroli 

Implementei uma nova funcionalidade que mostra e esconde as taxas que já foram incluídas em algum relatório de reembolso.
Vou encerrar esse chamado e reabriremos outro para ajustar essas funcionalidades.
