### ISSUE TITLE
ERRO REEMBOLSO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#166]
Bruno, 
Estava fazendo o reembolso da empresa "Adiser BK", e selecionei o período 01/01/2021 à 31/01/2021.
O sistema no entanto "puxou" 3 taxas que são de 2020 e 1 taxa do mês de Fevereiro.

Peço verificar.

![Sem título](https://user-images.githubusercontent.com/60766925/122116512-17390e80-cdfc-11eb-8b83-83088215e159.png)

**Comment by fullcontent** [comment]
@castroli 

Foi feita uma alteração na exibição, peço testar por gentileza e reabrir o chamado caso o problema persista.
