### ISSUE TITLE
Pendências - Campo prioridade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#167]
Bruno,
Solicitamos incluir no quadro de pendências um icone de prioridade, segue detalhamento a baixo.

- [x] Na dashboard incluir coluna com a opção de prioridade sendo ilustrada pelo sinal de exclamação (igual utilizado no outlook), sendo se se clicar sobre ele, desmarca ou marca a opção. Manter tambem a opção de organizar.
![image](https://user-images.githubusercontent.com/60766925/122267028-d18a4d80-ceb0-11eb-838c-5a0cec9e681b.png)
![image](https://user-images.githubusercontent.com/60766925/122267163-f41c6680-ceb0-11eb-9326-f7638cbb76e7.png)

- [x] Na pagina do serviço fazer apenas constar um sinal de exclamação (exemplo na imagem a baixo), sendo se se clicar sobre ele, desmarca ou marca a opção.

![image](https://user-images.githubusercontent.com/60766925/122265375-0ac1be00-ceaf-11eb-8544-31666058a43a.png)

**Comment by fullcontent** [comment]
- [ ] Inserir coluna "prioridade" no banco de dados de Pendências
- [ ] Inserir coluna na tabela das prioridades
- [ ] Atualizar controlador para salvar as informações

**Comment by fullcontent** [comment]
@castroli 

Testar por gentileza.

**Comment by castroli** [comment]
@fullcontent 
No meu usuário, da Aline e da Aryane está certo, porém para os usuários da Caroline, Kauane e Mariene não esta aparecendo a coluna de prioridade e para estes usuários não esta aparecendo o campo de "pesquisa" e as abas (estão todas pendencias em uma unica tela, peço verificar, por favor.

Tela do usuário Caroline
![image](https://user-images.githubusercontent.com/60766925/128220079-471be55d-ee6b-429b-b77e-9ede0f82d61a.png)

**Comment by castroli** [comment]
@fullcontent 
Três coisas que notei, são elas:

- [ ] Nas pendências do dia não está aparecendo a coluna e a opção de prioridade, peço incluir. 
- [ ] Outro detalhe que nas pendências do dia sumiu o campo de "pesquisa" peço incluir 
- [ ] Sumiu tbm a opção de "ordenar", peço incluir tbm, por favor.

![image](https://user-images.githubusercontent.com/60766925/128274522-52a8450e-d3ee-4a28-aed7-c786dad9643f.png)

**Comment by castroli** [comment]
@fullcontent 

- [ ] Notamos que na tela de "Detalhes do serviço" conseguimos aplicar a opção de prioridade, porém não conseguimos desmarcá-la (remover), peço incluir esta opção, por favor.

![image](https://user-images.githubusercontent.com/60766925/128277629-a1227b03-fbc8-4299-9c65-1994a2b77fb6.png)

**Comment by fullcontent** [comment]
@castroli 

Feito as alterações... pode confimar se agora está ok?

**Comment by castroli** [comment]
@fullcontent 
Ficou pendente apenas o item citado abaixo:

- [ ] Notamos que na tela de "Detalhes do serviço" conseguimos aplicar a opção de prioridade, porém não conseguimos desmarcá-la (remover), peço incluir esta opção, por favor. 
![image](https://user-images.githubusercontent.com/60766925/128395612-bf58c2a1-2db3-4d34-bd7d-45b8b9e3da17.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido. Favor testar!
