### ISSUE TITLE
Incluir botão download

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#170]
Bruno,
Na tela de "Detalhes da unidade" dentro dos quadros "Licenças de operação", "Projeto/Licenças não renovavel", "Controle de certidão", "Controle de taxas" e "Facilities/Real estate" incluir ao lado do status um botão para realizar o download do documento, no caso seria uma forma de fazer o download sem precisar entrar primeiramente no serviço. Atualmente temos que entrar no serviço e clicar no botão apresentado na imagem 02.

Imagem 01
![image](https://user-images.githubusercontent.com/60766925/122567723-5bf0bf80-d01f-11eb-8eb6-1ccee226bfb1.png)

Imagem 02
![image](https://user-images.githubusercontent.com/60766925/122568418-1a144900-d020-11eb-9d64-db95aad3e808.png)

**Comment by fullcontent** [comment]
@castroli 

Inserido o botão para download. Peço testar por gentileza.

**Comment by castroli** [comment]
Showww...Obrigado.
