### ISSUE TITLE
Erro Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#171]
@fullcontent 
Identificamos um grave erro no faturamento, as unidades citadas a baixo (podendo haver mais casos) ja tiveram um faturamento (100% do valor) realizado, porém mesmo assim consta valor em aberto, peço verificar.
Como ocorreu com estes casos, creio que pode haver outros.

- [x] **Espaçolaser 01A7 | Rua Emilia Marengo** (Link http://sistemacelic.net/admin/servicos/1786)
Faturamento do dia 07/04/2021 - NF 551 (Link http://sistemacelic.net/admin/faturamento/show/338)
![image](https://user-images.githubusercontent.com/60766925/123142859-47059900-d430-11eb-8a7e-5cdb4aed49c2.png)

- [x] **Espaçolaser 8318 | Centro Palmas/TO**  (link http://sistemacelic.net/admin/servicos/2475)
Faturamento do dia  07/04/2021 - NF 546 (Link http://sistemacelic.net/admin/faturamento/show/343)
![image](https://user-images.githubusercontent.com/60766925/123145331-1a9f4c00-d433-11eb-9732-49c8b84eff8a.png)

- [x] **Espaçolaser 0106 | Pacaembu** (link http://sistemacelic.net/admin/servicos/2500)

Faturamento do dia  07/04/2021 - NF 572 (Link http://sistemacelic.net/admin/faturamento/show/357)
![image](https://user-images.githubusercontent.com/60766925/123145375-2723a480-d433-11eb-863d-12e30d227acd.png)

- [x] **Espaçolaser 0107 | Tatuapé** (Link http://sistemacelic.net/admin/servicos/2508)
Faturamento do dia  07/04/2021 - NF 578 (Link http://sistemacelic.net/admin/faturamento/show/359)
![image](https://user-images.githubusercontent.com/60766925/123145690-79fd5c00-d433-11eb-8fe0-24faa6c1c86d.png)

**Comment by fullcontent** [comment]
@castroli 

Você tem algum faturamento que foi feito fora do sistema?

Ou alguma planilha de controle que você utilize pra eu comparar os resultados?

**Comment by castroli** [comment]
@fullcontent 
Conforme falamos, não temos, ja faz alguns meses que usamos apenas o CELIC para realizar faturamentos.~

**Comment by fullcontent** [comment]
Listagem dos serviços que apresentaram o mesmo problema:

"http://127.0.0.1:8000/admin/servicos/55"
"http://127.0.0.1:8000/admin/servicos/57"
"http://127.0.0.1:8000/admin/servicos/155"
"http://127.0.0.1:8000/admin/servicos/469"
"http://127.0.0.1:8000/admin/servicos/556"
"http://127.0.0.1:8000/admin/servicos/559"
"http://127.0.0.1:8000/admin/servicos/560"
"http://127.0.0.1:8000/admin/servicos/685"
"http://127.0.0.1:8000/admin/servicos/720"
"http://127.0.0.1:8000/admin/servicos/739"
"http://127.0.0.1:8000/admin/servicos/1419"
"http://127.0.0.1:8000/admin/servicos/1463"
"http://127.0.0.1:8000/admin/servicos/1492"
"http://127.0.0.1:8000/admin/servicos/1518"
"http://127.0.0.1:8000/admin/servicos/1529"
"http://127.0.0.1:8000/admin/servicos/1901"
"http://127.0.0.1:8000/admin/servicos/1902"


Esses serviços acima foram todos alterados o valor aberto para zero. A listagem é para possivel correção de erros no futuro com alguns desses serviços.

**Comment by fullcontent** [comment]
@castroli 

Foi feito um teste local, e aparentemente o erro foi sanado.
Os serviços que localizei que tinham o mesmo problema foram corrigidos o valor para zero.

Seria necessário fazermos mais alguns testes com os dados reais afim de detectarmos se esse erro persiste.

**Comment by castroli** [comment]
Ok Bruno, vou acompanhar.
