### ISSUE TITLE
ERRO REEMBOLSO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#172]
Bom dia Bruno, 
Acabei de gerar um reembolso para a empresa Pague Menos, do período 01/06 à 30/06. Os valores fecharam certinho, porém, na hora de clicar para fazer o download, aparece o erro abaixo. Consegue verificar, por favor? 

![image](https://user-images.githubusercontent.com/60766925/124282739-89f6f900-db21-11eb-9cd9-1dc8dd472ca0.png)

**Comment by fullcontent** [comment]
Problema causado por uma atualização nas versões dos arquivos PDF gerados por outros sistemas.

Estudando a melhor forma de resolver.

Algumas opções:

### Opção 1:
Inserir um link para o arquivo original dentro do relatório. Ao invés de anexarmos o boleto ou comprovante, criaremos uma tabela e deixamos um link para o arquivo original.
Dessa forma, contornamos o erro de forma mais rápida.


### Opção 2:
Verificar e converter todos os arquivos dentro do servidor. Isso implicaria em várias horas de programação para desenvolver uma ferramenta que verifique a versão do arquivo PDF e converta ele para uma versão anterior.

**Comment by fullcontent** [comment]
### Sugestão para melhoria

![image](https://user-images.githubusercontent.com/6120413/124333576-03ffa000-db6b-11eb-9225-11c8c075562d.png)

**Comment by fullcontent** [comment]
@castroli 

Descrevi o problema e algumas idéias de solução pra esse problema... 
O que acha?
Como procedemos?

**Comment by castroli** [comment]
@fullcontent,

A opção 1 iria gerar muito trabalho, sendo fazer os downloads e depois juntar tudo para enviar ao cliente, creio que não seria prático.
Opção 2: Poderia ser uma opção, porem não podemos esperar muito tempo para ter a solução deste problema.
Opção 3: Como 99% dos arquivos que recebemos é no formato PDF, iriamos perder muito tempo em sempre que for anexar algo no CELIC ter que primeiramente converter.

- [ ] Surgiu uma nova ideia, desde juntar tudo em um único arquivo, pode juntar apenas o boleto e o comprovante em um PDF, resumindo, teríamos um PDF com o “recibo e relatório” e mais um PDF por cada “boleto e comprovante”. Para organizar, daria para colocar um coluna “Item” no relatório, exemplo o item 01 do relatório seria nomeado com “01”, item 02 nomeado com “02” e assim sucessivamente. O botão download permanece, porem quando clicamos ele gera uma pasta zipada com todos os PDFs organizados conforme citado anteriormente.

![image](https://user-images.githubusercontent.com/60766925/124506430-026bed00-dda2-11eb-9705-0b4671d0f984.png)
![image](https://user-images.githubusercontent.com/60766925/124506609-65f61a80-dda2-11eb-8954-e68bdbe98cee.png)


- [ ] Notamos que o **erro de datas** (citado no chamado #155) voltou, peço corrigir tbm. 

![image](https://user-images.githubusercontent.com/60766925/124502695-5246b600-dd9a-11eb-831e-6c350e280411.png)
![image](https://user-images.githubusercontent.com/60766925/124506792-c84f1b00-dda2-11eb-8c04-93204e3062e1.png)

**Comment by castroli** [comment]
@fullcontent 

- [ ] Notamos que ajustou a ordem (Recibo e relatório), porem , apresenta um erro, pois estão desconfigurados, ajustar, por favor.

![image](https://user-images.githubusercontent.com/60766925/124510479-495de080-ddaa-11eb-9f84-f3acd0ba3176.png)

**Comment by fullcontent** [comment]
@castroli 

Afim de agilizar o progresso desse chamado o relatório não anexará os arquivos PDF's incompatíveis.
Esse é um paliativo enquanto buscamos e melhor solução para esse problema.

**Comment by castroli** [comment]
Ok Bruno, 
Conforme falamos, seguir com apção citada no dia 05/07 deste chamado.

**Comment by fullcontent** [comment]
@castroli 

Foi atualizado a nova funcionalidade de Download em ZIP com os arquivos dentro.

Utilizei a nomenclatura da seguinte maneira

Relatório {NOME DO RELATORIO}

1C - Comprovante do Item 1
1B - Boleto do Item 1


Peço testar e reabrir o chamado caso tenha algum problema ou ajuste.
