### ISSUE TITLE
[BUG] CONTROLE DE TAXAS

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#174]
Bruno, 
Precisei alterar o campo "valor" dentro do controle de taxa, e ocorreu aquele problema da data de pagamento. Ao salvar a alteração, ele automaticamente mudou a data de pagamento para o dia de hoje 08/07.
Pelo que estou vendo, qualquer campo que a gente altere dentro da tela de controle de taxa, automaticamente coloca a data de pagamento para o dia de hoje. 
É possível corrigir esse erro? 

Tela atual (com a data correta que a taxa foi paga):
![image](https://user-images.githubusercontent.com/60766925/124947977-ae057f00-dfe6-11eb-8c52-0684fb7ae994.png)

Tela com a alteração de valor que precisei fazer (o sistema altera a data de pagamento para a data de hoje):
![image](https://user-images.githubusercontent.com/60766925/124948133-cecdd480-dfe6-11eb-9cc6-61b92506e5bd.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido, peço testar.
