### ISSUE TITLE
Erro Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#175]
Bruno, bom dia!
Estou tentando gerar um relatório de faturamento porem esta apresentando erro, peço verificar, por favor.

![image](https://user-images.githubusercontent.com/60766925/125460014-9d7bf410-89fe-4d30-8944-a9523769c6ff.png)
![image](https://user-images.githubusercontent.com/60766925/125460030-f154633e-40ac-4d98-b0aa-72c653c25a18.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido e já implementado uma melhoria de performance descrita no [chamado #142](#142)
