### ISSUE TITLE
Listagem de faturamentos

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#176]
Bruno, boa noite!
Peço realizar duas melhorias, são elas:

- [x] Organizar a lista de faturamentos mantendo sempre na parte superior da pagina o ultimo relatório gerado.
- [ ] Incluir opção de editar a coluna de numero de NF. Hoje o campo que cadastramos o numero da Nota Fiscal, após cadastrado não conseguimos mais editar. Exemplo, na imagem abaixo, inclui o numero da NF errada e atualmente não tenho como corrigir.

![image](https://user-images.githubusercontent.com/60766925/125535151-13daa6a1-95db-4737-a04d-d8b18a798f55.png)
![image](https://user-images.githubusercontent.com/60766925/125536005-41079d9f-c925-4695-8f45-fdc6d7e811f7.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido a ordem dos relatórios.


Foi criado um novo [chamado](#177) para a segunda alteração, que é mais detalhada pra fazer
