### ISSUE TITLE
Editar a NF em Faturamentos

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#177]
- [x] Formulário de edição de NF
- [x] Função salvar
- [x] Função Editar.

**Comment by fullcontent** [comment]
@castroli 

Testar por gentileza;

**Comment by castroli** [comment]
Bruno, testei a opção de editar o numero da NF e está tudo certo. 
Fiquei com uma duvida, hoje após gerado um faturamento, exemplo fiz um faturamento de 10 serviços, após gerado, não consigo editar e incluir ou excluir algum serviço expecífico, correto?

**Comment by fullcontent** [comment]
@castroli 

Essa funcionalidade está sendo desenvolvida no chamado #135.

**Comment by castroli** [comment]
Blz Bruno, chamado encerrado.
