### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#178]
Bruno,
Surgiram 2 erros no serviço 2616 (Link do serviço: http://sistemacelic.net/admin/servicos/2616)

- [x] Ao clicar em "Visualizar todo o histórico" da uma tela de erro .
![image](https://user-images.githubusercontent.com/60766925/125695480-a50aa241-6775-4af3-8b3f-6bb7fec271fc.png)
![image](https://user-images.githubusercontent.com/60766925/125695503-13e13966-132d-4320-bdf5-28b65ed9445c.png)

- [x] Serviço finalizado hoje, porem ao gerar o relatório de faturamento com o periodo de ontem a amanha, não aparece este serviço, isso é um erro que nunca pode acontecer, neste caso só identificamos por ser um serviço finalizado hoje. 
Tela faturamento:
![image](https://user-images.githubusercontent.com/60766925/125695591-0ed7f0f0-4908-42ec-ae84-a68655c7a0b0.png)

**Comment by fullcontent** [comment]
@castroli 

Os serviços finalizados ontem 15/07 já estão disponíveis na geração de faturamento.
Estou implementando agora a funcionalidade pra eles aparecerem nos próximos.

**Comment by fullcontent** [comment]
@castroli 

Corrigido o erro nas interações, foi a questão de ter expirado o login.
