### ISSUE TITLE
Listagem de serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#18]
- Remover o campo "responsável" na tela de listagem de serviços.
![image](https://user-images.githubusercontent.com/60766925/74158020-1a186380-4bf8-11ea-8f76-32a2890c6bac.png)

- Na tela "Listagem de serviços" deixar na seguinte ordem: OS, tipo, serviço, cód (codigo da unidade), unidade, situação (vigente ou vencido para os "serviços primário" (sendo vigente na cor verde e vencido na cor vermelha), e para os serviços "secundário" manter apenas um hifen), andamento (sim ou não) e por ultimo o botão detalhes.
![image](https://user-images.githubusercontent.com/60766925/74158786-72039a00-4bf9-11ea-8cf6-09e22bcefb15.png)

**Comment by fullcontent** [comment]
Situações-> Status:

1. Em andamento (desde o inicio do processo, até cadastrar a data de vencimento e o arquivo de licença)
2. Finalizado (quando é cadastrado o arquivo e o vencimento)
3. Arquivado (quando inicia o processo de renovação)


Situação:

Vigente (Vencimento Licença é igual ou maior que a data atual)
Vencido (Menor do que hoje)
