### ISSUE TITLE
Erro histórico

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#183]
Bruno, 
Encontramos mais um serviço apresentando o mesmo erro do citado no chamado 178, segue...

- [ ] Ao clicar em "Visualizar todo o histórico" da tela de erro .

http://sistemacelic.net/admin/servicos/2942
![image](https://user-images.githubusercontent.com/60766925/126348696-c95d78c2-ce8a-4437-a935-ba4ae5c54e04.png)
![image](https://user-images.githubusercontent.com/60766925/126348836-9d1cec69-1a76-4460-ac8e-2b874e369f8c.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido...

Vou implementar uma função no sistema para reparar automaticamente as interações que acontecerem quando expirar o login do usuário.

**Comment by castroli** [comment]
Ótimo, obrigado.
