### ISSUE TITLE
ERRO GERAL CELIC 28-07-21

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#185]
Bruno, boa tarde

Estamos desde as 14h30 (+ou-) com o CELIC instável. Ele entra, cai, dá erro, depois  a gente consegue logar, mas aí não conseguimos acessar nada, só a dashboard (o restante dá erro). Entrei no usuário da Caroline pra testar, ele entrou na dashboard mas agora não consigo fazer o logout pra acessar a minha, por exemplo.
Consegue verificar?

![image](https://user-images.githubusercontent.com/60766925/127370958-2567a0e1-caed-4963-a5fe-9923f1f04eee.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido, testei aqui e funcionou.
