### ISSUE TITLE
Ordenação de tabelas não ordenando por data

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#186]
Datatables incorrect date time sort order.

**Comment by fullcontent** [comment]
- [ ] Lista Reembolsos
- [ ] Lista Pendências
- [ ] Lista Faturamentos

**Comment by castroli** [comment]
Bruno, boa tarde!
Fiz o teste e continua fora da ordem, peço ajustar.
![image](https://user-images.githubusercontent.com/60766925/127932973-4c64778d-92be-40d5-adc2-6b36e33a409e.png)

**Comment by fullcontent** [comment]
@castroli 

Tenta agora, acho que tinha esquecido de corrigir essa tela.

**Comment by castroli** [comment]
Agora sim, show! ✌️
Obrigado.
