### ISSUE TITLE
Relatório de Reembolso - ajustes

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#187]
- [x] Mudar a ordem: (Recibo primeiro e listagem na segunda pagina)
- [x] Alterar fonte do documento para Calibri -> 12px;
- [x] Corrigir endereço da empresa (Rua 901, 400 | Sala 405)
- [x] Puxar nome RAZAO SOCIAL da empresa
- [x] Corrigir Endereço da empresa (Bairro, cidade / UF)
- [x] Corrigir caixa alta e baixa
- [x] Começar os itens do relatorio em 1 e não zero.
- [ ] Inserir links para Comprovante e boleto na listagem.
- [x] Não inserir arquivo zip no download
- [x] Data no topo do documento em por extenso tirar a hora
- [x] Texto do recibo Justificado
- [x] Inserir Dados Bancários (CAIXA ALTA, INSERIR CHAVE PIX acima (CNPJ) )
- [x] Tirar negrito
- [x] Inserir espaço entre texto e dados bancários
- [x] Inserir titulo (Demonstrativo de taxas Pagas)
- [ ] Deixar em paisagem o relatório de taxas (fonte menor 10px)
- [x] Ordenar por data de pagamento das taxas no relatorio.

**Comment by fullcontent** [comment]
@castroli 

A maioria dos ajustes foi feita ontem 02/08, porém tem duas alterações que vão demorar um pouco mais. Deixar o link dos arquivos e a segunda pagina como paisagem.

Com 85% concluído acredito que consigam ir utilizando a parte de relatórios de reembolso e já verificando se está tudo ok.

**Comment by castroli** [comment]
@fullcontent Hoje estivemos realizando vários testes e a princípio não tivemos mais nenhum erro. Aproveito para paranebilizar, ficou show. Obrigado

**Comment by castroli** [comment]
Quanto aos itens pedêntes, ok, vamos tentar finalzar ainda este mês.
