### ISSUE TITLE
Criação de Sub Serviços

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#188]
Criar um subserviço linkado a um serviço principal

- [x] Adicionar Coluna (servico_master_id)
- [x] Adicionar Tipo (Sub Serviço)
- [x] Listar os subserviços dentro do serviço principal identificar com um "S"
- [x] O nome do subserviço será (XXXX  XXXX )

- [x] Exibir dados do subserviço

Nome | OS | Situacao | Responsável

- [x] Ao faturar direto do Serviço, Direcionar para a tela de faturamento(passo2) com todos os serviços relacionados a esse serviço (principais e subserviços.

**Comment by fullcontent** [comment]
Exibir dados do subserviço

Nome
OS
Situacao 
Responsável

**Comment by fullcontent** [comment]
Inserir Simbolo "S" no nome da OS

**Comment by fullcontent** [comment]
Ao faturar direto do Serviço, Direcionar para a tela de faturamento(passo2) com todos os serviços relacionados.

**Comment by fullcontent** [comment]
@castroli 

Finalizado a implementação dos SubServiços.... 

Peço a gentileza de testar se está ok a funcionalidade do faturamento.

A principio ficou assim, quando faturar um serviço que tem um SubServiço, irá passar pra tela de Faturamento para selecionar quais Serviços deseja Faturar. 
Quando fatura um subServiço, irá direcionar diretamente para tela de Faturamento de um único serviço.

**Comment by castroli** [comment]
@fullcontent, 
Conforme falamos, o subserviço esta apresentando erro, não estamos conseguindo visualizá-lo, peço ajustar.

**Comment by fullcontent** [comment]
@castroli 

Inserido identificador de SubServiço nas listagens de serviços gerais.

Estou encerrando esse chamado, qualquer problema relacionado a SubServiços pode reabrir!
