### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#189]
Bruno,
Estou tentando anexar o comprovante de pagamento de uma taxa e está dando erro. 
Serviço 3188

Ao clicar na taxa:
![3188](https://user-images.githubusercontent.com/60766925/128024137-c6125906-e9e3-4537-b81c-b330df06af0e.png)

Aparece o erro abaixo:
![image](https://user-images.githubusercontent.com/60766925/128023784-86028820-59ce-4707-a0e8-24d49e768717.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.
