### ISSUE TITLE
Erro dashboard

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#192]
@fullcontent  

- [x]  Após as alterações que fez para atender o chamado 167 notei que para o meu usuário (possivel mente em outros tbm) não esta aparecendo a msg com a "quantidade de pendências" que tenho. Para facilitar vou colocar aqui um print da tela dashboard do usuário Caroline (com a msg) e do meu dashboard (sem a msg), peço corrigir, por favor. 
- [ ] #197

Tela Usuário Caroline- com msg, correto:
![image](https://user-images.githubusercontent.com/60766925/128429237-0b7c19d5-ca6a-4667-a4a5-1bf71bd92853.png)

Tela Usuário Diego - sem msg, errado:
![image](https://user-images.githubusercontent.com/60766925/128429211-35667297-6dc7-4cf2-b6bd-7f7f77793132.png)

**Comment by castroli** [comment]
@fullcontent Estou reabrindo este chamado pois novamente não esta aparecendo na minha dashboard a qtd de pendencias, este erro está acontecendo novamente apenas no meu usuário.

![image](https://user-images.githubusercontent.com/60766925/130677799-ed5bf340-f2bf-499a-aab0-719ebc4e8587.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!
