### ISSUE TITLE
Criar Novos Campos 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#196]
@fullcontent  bom dia!

- [x] Solicito incluir um campo de "Escopo" nas telas de "Editar serviço" e "Detalhes do serviço", segue abaixo o que imaginamos.

Tela 01
![Imagem 01](https://user-images.githubusercontent.com/60766925/128930808-b1eb12a1-7b3c-47dd-a3c1-d582c3ec55e4.jpg)

Tela 02
![Imagem 02](https://user-images.githubusercontent.com/60766925/128930845-816c2caf-ad73-46e6-923a-2b2fc51597d8.jpg)

- [ ] Solicito incluir um campo de "Proposta" nas telas de "Editar serviço" e "Detalhes do serviço".

**Comment by fullcontent** [comment]
@castroli 

Favor testar.

**Comment by castroli** [comment]
@fullcontent,
Conforme tela 01 o campo de **Proposta**, não cosnta no momento de criação do serviço. Apenas após o serviço já criado  (tela 02 e 03), peço ajustar, por favor.

Tela 01
![image](https://user-images.githubusercontent.com/60766925/129229964-e75a3f71-e67a-4429-bd63-3087c0487557.png)
 
Tela 02
![image](https://user-images.githubusercontent.com/60766925/129230477-d525f4b5-51de-4062-848b-8e67fb950b90.png)
Tela 03
![image](https://user-images.githubusercontent.com/60766925/129230658-43bd8695-cb89-4999-bfe9-a5a8327a4693.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido...
