### ISSUE TITLE
Pendências Vinculadas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#198]
@fullcontent 

- [x] Estamos utilizando a nova ferramenta surgiu a 1ª necessidade de melhoria. Abaixo criei uma tela com o q imaginamos, seria a opção de **vincular uma pendência a mais de um serviço**. Com isso, apenas após **todos** os serviços vinculados estiverem finalizados que  a pendência voltará a aparecer em nossa dashboard. Seria possível?
 
![Tela pendências](https://user-images.githubusercontent.com/60766925/131151567-77557540-bd88-4bf8-adf3-511dfaa69886.jpg)

- [x] Peço também fazer com que **para as pendências que possui vinculo** não ser necessário incluir uma data, pois acaba sendo desnecessário.

**Comment by fullcontent** [comment]
@castroli 

Sim, é possivel fazer essa melhoria... vou estudar a melhor maneira de fazê-la.

**Comment by fullcontent** [comment]
@castroli 

Esse campo de descrição do vinculo é para ser preenchido automaticamente com o nome do serviço ou deixar ele em aberto para preencher manualmente?

**Comment by castroli** [comment]
@fullcontent, preenchimento automatico, por favor.

**Comment by fullcontent** [comment]
### Criar pendência

- [ ] Criar Relacionamento de tabelas no banco de dados
- [ ] Inserir formulário dinâmico para adicionar e remover os vinculos
- [ ] Exibir nome do serviço na seleção do vinculo
- [ ] Cadastrar vinculos na tabela relacionada no cadastro
- [ ] Implementar modulo de remover vinculos já no formulario
- [ ] Retirar data limite caso haja algum vinculo adicionado

### Editar pendência

- [ ] Criar model de Relacionamento para recuperar os vinculos na edição
- [ ] Atualizar banco se for adicionado ou removido algum vinculo


### Funções

- [ ] Quando finalizado o serviço vinculado a pendencia, remover o vinculo e adicionar data limite do dia.

**Comment by castroli** [comment]
Bruno, bom dia!

- [ ] ERRO: Quando vamos criar uma nova pendência está dando tela de erro, porém ele cria a pendência.

![image](https://user-images.githubusercontent.com/60766925/132701387-f0277125-df1e-4446-827b-432e7c09f142.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!

**Comment by fullcontent** [comment]
@castroli 

Foi finalizado a parte de lógica das pendências vinculadas.
Peço que execute alguns testes por gentileza pra ver se está funcional e de acordo com as espectativas.


Ficou faltante apenas a exibição do nome do serviço na seleção do vinculo.

**Comment by castroli** [comment]
@fullcontent 
Estou realizando alguns testes e identifiquei o seguinte erro:

**Tela 01:** Abrindo uma nova pendência vinculada.
![image](https://user-images.githubusercontent.com/60766925/134595132-6af5935a-5e2c-49d7-a050-cecfcb96a77f.png)

**Tela 02:** Clicando em editar pendência. O vinculo está passando para linha de baixo, não sei se isso influencia em algo. 
![image](https://user-images.githubusercontent.com/60766925/134595216-681017b8-7b9c-4d8a-a440-de3eb6c5cd7c.png)
![image](https://user-images.githubusercontent.com/60766925/134595250-79e7ed9d-ddfe-462a-a8bd-ab43a8636253.png)

**Tela 03:** O fato é que mesmo vinculada, a pendência está sendo listada entre as pendências na dashboard, peço corrigir. 
![image](https://user-images.githubusercontent.com/60766925/134595509-99295d67-54ca-4d53-a2f9-76bd5c8fdb11.png)

**Comment by castroli** [comment]
@fullcontent 
Mais um erro detectado, 

Tela 01: Neste caso por exemplo, temos 2 serviços em "Andamento" (EP0511 e EP05112), porém conforme imagem 02, no momento do vinculo, consta apenas o serviço (EP0512).
![image](https://user-images.githubusercontent.com/60766925/134680960-2a17993b-2bc2-4bd6-80e8-8597af3632db.png)
Tela 02: No momento do vinculo, consta apenas o serviço EP0512, EP0511 não aparece. 
![image](https://user-images.githubusercontent.com/60766925/134687273-d2ae2d43-3caa-4032-a6d2-ec7c9b22b0e8.png)


Tela 03: Criei mais um serviço (Teste - EP0524)  para verificar se iria aparecer no vinculo e apareceu, resumindo apenas o Serviço EP0511 que não está aparecendo. Este mesmo erro está aparecendo em outros casos, peço verificar.
![image](https://user-images.githubusercontent.com/60766925/134687011-8b34af00-5743-4532-9624-c824ab1389fa.png)
![image](https://user-images.githubusercontent.com/60766925/134687050-1e8252cd-9651-4f03-8978-a64e3b26ca40.png)

**Comment by fullcontent** [comment]
- [ ] Não listar pendencias com vinculo na dashboard (Editar AdminController)
- [ ] Verificar exibição dos vinculos quando há mais que um vinculo. (FormPendencia)

**Comment by castroli** [comment]
Bruno, 
Referente este segundo erro, peguei a unidade teste (http://sistemacelic.net/admin/unidades/539) que possui 15 serviços em andamento, entrei no serviço O.S "CS0278" e listou apenas 14 serviços, assim como no erro anterior, não está listando a primeira O.S em andamento, neste caso a CS0089. Peço verificar.

![image](https://user-images.githubusercontent.com/60766925/135112933-74108c6e-fbd8-4769-a5c9-166c4fc4ef5c.png)
![image](https://user-images.githubusercontent.com/60766925/135112973-a83bc069-c850-4f2c-9892-1ccea85f97b8.png)

**Comment by fullcontent** [comment]
@castroli 

Era um erro no seletor, estava lá o serviço mas não estava listando. Creio que agora está ok.

**Comment by castroli** [comment]
@fullcontent Agora acho que deu boa, fiz alguns testes e deram todos certo, continuarei monitorando e caso surja algum erro, reabro o chamado. Obrigado.
