### ISSUE TITLE
ERRO FATURAMENTO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#199]
Bruno, está aparecendo a tela de erro abaixo quando clicamos no botão "cadastrar" dentro de faturamento:

![image](https://user-images.githubusercontent.com/60766925/131540167-146ac60b-55a3-4d7a-b8ed-14713039d55b.png)

Pode verificar, por favor?
Obrigada

**Comment by fullcontent** [comment]
@castroli 

Corrigido...

Favor testar também a questão dos SubServiços, pois esse erro tem relação com essa funcionalidade.
