### ISSUE TITLE
Erro pendências vinculadas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#200]
Bruno,
Notamos que todas as pendências que criamos, mesmo que eu não vincule a nenhum serviço, automaticamente o sistema esta vinculando, peço corrigir por favor.

**Comment by fullcontent** [comment]
@castroli 

Poderia encaminhar um print do vinculo por gentileza? Em qual tela está vinculando o serviço?

**Comment by castroli** [comment]
Bom dia Bruno,

Na vdd em qualquer pendencia nova criada está surgindo este erro. Conforme consta na tela 01, quando estamos criando a pendência, automaticamente ela já está com o campo "Vinculado a OS" preenchido com uma O.S , neste caso é a CS0089, pois é a primeira O.S da lista desta unidade. Detalhe, não temos como excluir esse vinculo neste momento, apenas após criada a pendência, temos que editar ela e clicar no botão "remover". 
O correto seria, no momento de criação da pendência a opção de vincular ela a algum serviço fique desmarcada (ou em branco, sem nenhum vinculo), e se for o caso de vincular, clicamos no campo e escolhemos a qual serviço que desejamos vincular. 
Tela 01: Criando pendência.
![image](https://user-images.githubusercontent.com/60766925/131847818-44f4d32b-2b18-46d6-b52a-a36684feffe5.png)

Tela 02: A pendência criada não foi para minha dashboard, pois com vinculou a um serviço, ja foi direto para listagem de pendências vinculadas.
![image](https://user-images.githubusercontent.com/60766925/131847890-a7717410-724c-4ad4-8220-8ea9efa5dcb0.png)

Tela 03: Pendencia dentro da listagem de pendências vinculadas.
![image](https://user-images.githubusercontent.com/60766925/131847994-2b1342fc-c4c2-4d7b-923c-65c3e3075117.png)

**Comment by fullcontent** [comment]
@castroli 

Foi corrigido...

Agora por padrão a opção vem desabilitada, e pode-se excluir a seleção caso tenha alguma.
