### ISSUE TITLE
Erro Campo Taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#202]
@fullcontent 
Quando cadastramos uma taxa o sistema não esta salvando o texto que incluimo no campo "Observações", abaixo segue duas telas a respeiro, peço ajustar, por favor.

Tela 01:
![image](https://user-images.githubusercontent.com/60766925/132560123-19b32335-da4f-4f26-8b0b-c23766ea61e2.png)

Tela 02:
![image](https://user-images.githubusercontent.com/60766925/132560233-256658cf-20f0-49ee-a4e4-5a48cd8befe0.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!
