### ISSUE TITLE
Erro edição de taxa

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#203]
@fullcontent 
Ao tentar editar uma taxa, passando o campo "Reembolso" de "Sim" para "Não", apresenta a tela de erro, não sendo possivel realizar esta alteração. peço corrigir, por favor.

Tela 01 - 
![image](https://user-images.githubusercontent.com/60766925/132777064-d4cd95e1-e755-4acd-9e5f-b91734e75179.png)

Tela 02 - Alterando o campo reembolso de "sim" para "não" .
![image](https://user-images.githubusercontent.com/60766925/132777090-a1b7aebd-434a-40c2-aa0d-b45ad37d381a.png)

Tela 03 - Erro
![image](https://user-images.githubusercontent.com/60766925/132777110-03a39941-ced2-451d-af72-efc73dab8143.png)

**Comment by fullcontent** [comment]
@castroli 

Feito uma alteração no formulário de edição. Já foi alterado para Reembolso = Não...

Peço testar por gentileza..

**Comment by castroli** [comment]
@fullcontent 
No caso citado anteriomente notei que foi alterado para "Não", está correto!
Fiz a criação de uma taxa teste e refiz todo o processo (criando como reemboslo "Sim" e após mudando para "Não") e notei que o erro permenesceu. Neste caso imagino que o ideal seria ajustar no sistema para q a gente (usuários) consiga fazer esta alteração sem a necessidade de solicitar pra vc, seria possivel?  

http://sistemacelic.net/admin/taxas/1755
![image](https://user-images.githubusercontent.com/60766925/133099186-8cea0382-5fca-4089-9d36-0e66a2d25008.png)

**Comment by fullcontent** [comment]
@castroli 

Feito mais uma alteração na lógica. Peço testar por gentileza.

**Comment by castroli** [comment]
Agora deu boa, obrigado cara. Vou encerrar o chamado.
