### ISSUE TITLE
[BUG] Pendências do dia

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#205]
Bruno, 
Notamos um erro na dashboard, com relação às pendências.
Hoje, 13/09 tem uma pendencia que deveria aparecer na listagem de "pendencias do dia", porém, está aparecendo como "pendências atrasadas".
Pode verificar pra nós, por favor? O código do serviço é 3357 

![Erro celic](https://user-images.githubusercontent.com/60766925/133132461-ff665b82-463f-4ef2-bb3d-395679dff6b1.png)

**Comment by fullcontent** [comment]
@castroli 

Poderia testar por gentileza? Fiz uma pequena atualização na listagem.

**Comment by castroli** [comment]
Correto Bruno, obrigado.
