### ISSUE TITLE
[BUG] Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#206]
Bruno, boa tarde

Notei há alguns dias um novo erro no faturamento. Ao selecionarmos a empresa e o período desejado, abre a listagem com os serviços finalizados, porém, na coluna "Finalizado", aparecia a data de finalizaço do serviço e essa informação é útil para nós. Atualmetne, conforme tela abaixo, aparece "Andamento" no lugar das datas. 
Pode verificar para nós?

![ERRO CELIC](https://user-images.githubusercontent.com/60766925/133504291-02db7b59-b17e-4fbe-bbcb-dfc2299445e9.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido, peço testar por gentileza..

**Comment by castroli** [comment]
Correto Bruno, obrigado.
