### ISSUE TITLE
Incluir campo no "Relatório Completo de Serviços"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#207]
@fullcontent 
Peço incluir no "Relatório Completo de Serviços" uma coluna com a data que foi finalizado o serviço.

Incluir esta coluna "Finalizado":
![image](https://user-images.githubusercontent.com/60766925/134514954-10613cf5-d72c-4d43-929b-2bf509f279fe.png)

Neste Relatório:
![image](https://user-images.githubusercontent.com/60766925/134515293-c5cafdec-2156-4e20-94cf-e0e0d08f0772.png)

**Comment by fullcontent** [comment]
@castroli 

Alteração concluída.
Qualquer problema é só reabrir o chamado.
