### ISSUE TITLE
Erro Pendências Dashboard

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#209]
Bruno
Identifiquei um novo erro na dashoboard, segue abaixo, peço corrigir

Imagem 01 - Tela da Dashboard da Aryane Ottoni. Esta aparecendo para ela uma pendência que é minha (Diego), ela neste caso é a responsavel pelo serviço, a pendência não deveria aparecer para ela.
![image](https://user-images.githubusercontent.com/60766925/137485779-f2cf0dee-690f-4a4b-a569-c93410b95249.png)

Imagem 02 - Tela mostrando que a pendência é minha.
![image](https://user-images.githubusercontent.com/60766925/137486229-678b1330-d8eb-43dd-aae6-fe6728906aa4.png)

**Comment by fullcontent** [comment]
@castroli 

Fiz um teste de exibição local aqui com o usuário da Aryane e a pendencia com ID 14252 não apareceu na listagem. A lógica das listagens das pendências parece ok, (Listar as pendências onde o responsável é o usuário logado)


Foi feita alguma alteração na pendência ou no serviço?

Pode checar novamente no usuario dela e enviar um print aqui por gentileza?
