### ISSUE TITLE
Interações

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#21]
- Incluir um botão para clicar e mostrar todas as interações do processo, não só as ultimas 3 que constam hoje.
![image](https://user-images.githubusercontent.com/60766925/74161141-3e2a7380-4bfd-11ea-9063-8b732aa568d1.png)

- Quando alterado a data limite da pendência, fazer constar automaticamente na interação.

- As datas das interações estão aparecendo em dias (ex. "há 6 dias", ou "há 10 dias"), peço fazer constar a data da interação no modelo 29/01/2020 (dd/mm/aaaa).

**Comment by fullcontent** [comment]
![image](https://user-images.githubusercontent.com/6120413/74243660-e8b69b00-4cbe-11ea-8c0b-ba2e61b3a477.png)
