### ISSUE TITLE
Criação de novos serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#213]
@fullcontent , bom dia!
Notamos que ao criar um novo serviço se o campo "Situação" for alterado para "Finalizado" (no caso criar o serviço com a situação finalizado) isso acarreta um erro na hora de gerar o relatório de faturamento, pois ele não puxa o serviço (fica sem data de finalizado). Para solucionar este erro pensei um duas opções, ou fazer o sistema reconhecer este serviço como finalizado, mesmo que ele nunca tenha tido a situação como "Andamento", ou bloquear o campo de "Situação" no momento de criação do serviço, fazendo forçar sempre na criação de serviço manter a "Situação" igual a "Andamento".  

Tela 01: Criando o serviço com a Situação igual a Finalizado.
![image](https://user-images.githubusercontent.com/60766925/140312456-de83036f-f8dc-4591-b933-3803fd340945.png)

Tela 02: Serviço criado:
![image](https://user-images.githubusercontent.com/60766925/140312697-55984215-2b99-4d1f-ad50-7a897aaeba66.png)

Tela 03: Na opção de Faturamento, geramos o relatório e não apresenta este serviço.
![image](https://user-images.githubusercontent.com/60766925/140313191-08c8ca8f-b60b-40a4-beb4-41d1c69b5f6a.png)

Tela 04: Geramos o "Relatório Completo de Serviços" e na coluna "Finalizado" vem sem data de finalizado.
![image](https://user-images.githubusercontent.com/60766925/140313691-911c90c1-e539-49b6-ac18-b59d5e03c739.png)

**Comment by fullcontent** [comment]
@castroli 

Foi deixado a situação de somente Andamento permitida na criação do serviço. Assim evitamos erros futuros.
