### ISSUE TITLE
[BUG] VINCULAR PENDÊNCIAS

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#215]
Bruno, boa noite

Preciso vincular 2 pendências mas o sistema não mostra o número da O.S. que eu preciso. 
Por exemplo:
Tenho a O.S. AC0106 que refere-se ao Alvará de Funcionamento. Possuo dois outros serviços que só poderão ser iniciados após finalização do serviço AC0106, são eles: AC0108 e AC0658.
O correto seria: Entrar na pendência das duas O.S's citadas acima e vincular ambas à O.S. AC0106. Mas na listagem suspensa não puxa. Vejamos abaixo:

1- O.S. AC0106 - Serviço "Alvará de Funcionamento" que está tramitando.
![image](https://user-images.githubusercontent.com/60766925/141388215-859bca4b-a727-4330-9227-8076b78f4739.png)

2- O.S. AC0108 - Serviço "Alvará de Pubicidade" - Só posso iniciar após finalização da AC0106
![image](https://user-images.githubusercontent.com/60766925/141388246-ac164710-660e-46ef-9f6e-724bec5e626f.png)

3- O.S. AC0658 - Serviço "Licença Ambiental" - Só posso iniciar após finalização da AC0106
![image](https://user-images.githubusercontent.com/60766925/141388261-e8ab4549-c934-4274-a334-7dd13fd71b10.png)

Abaixo, coloco as duas telas onde mostra a lista suspensa para vincular e NÃO CONSTAM a AC0106 que eu necessito.

1- O.S. AC0108 - Serviço "Alvará de Pubicidade" - Lista suspensa/vínculo de pendências
![image](https://user-images.githubusercontent.com/60766925/141388372-1667889f-c85e-4c83-8cb5-4cd399351a0f.png)

2- O.S. AC0658 - Serviço "Licença Ambiental" - Lista suspensa/vínculo de pendências
![image](https://user-images.githubusercontent.com/60766925/141388351-37a7686d-d50a-43a1-8a46-5eb7993ddc60.png)

Consegue verificar, por gentileza?
Obrigada!

**Comment by fullcontent** [comment]
@castroli 

Corrigido
