### ISSUE TITLE
Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#216]
Bruno, boa tarde!

A exemplo do chamado 214, seria possivel incluir uma coluna de "Prosposta" no faturamento? Nesta coluna deixar tambem a opção de organizar de A a Z.

![image](https://user-images.githubusercontent.com/60766925/142458109-e22c97e5-b62f-4067-a2dd-191e8541f052.png)

**Comment by fullcontent** [comment]
@castroli 

Inserido!
