### ISSUE TITLE
Serviços faturados

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#217]
Bruno, boa tarde!
Atualmente não consigo ver em qual faturamento foi faturado tal serviço, temos que abrir um por um até acha. Com base nisso, gostaria de solicitar duas melhorias:

- [x] Quando o serviço já foi faturado, incluir na tela do serviço um campo com um link para acessar este relatório de faturamento.
![image](https://user-images.githubusercontent.com/60766925/144297142-2790e731-aa09-4489-8467-c673b57ea0f4.png)
  

- [x] No campo de busca da tela "Listagem de faturamentos" ter a opção de buscar pelo nome da unidade, código ou número da proposta que está descrito no relatório de faturamento.
![image](https://user-images.githubusercontent.com/60766925/144297490-b1896ac7-9d4d-4cfd-b223-9ff380a916c9.png)

**Comment by fullcontent** [comment]
@castroli 

A busca pela unidade e código ainda está em desenvolvimento. Pode testar a busca pela proposta.

**Comment by castroli** [comment]
@fullcontent 
Testei pela proposta e tambem **não deu certo**. 
Fiquei com uma duvida, para realizar a busca pela proposta, não teria que constar o numero da proposta em algum lugar do relatório?

**Comment by fullcontent** [comment]
@castroli 

então, a proposta está sendo listada de forma escondida, somente para facilitar a busca.

A questão ali é a seguinte: 

Temos um relatório -> vários serviços, desta forma teria que ser listada todas as propostas dentro da coluna.

![image](https://user-images.githubusercontent.com/6120413/145116600-cd20c0c4-c4e1-4d62-bbef-9bf60d189c8e.png)


Quer que prossiga desta forma?

**Comment by castroli** [comment]
Só para ver se entendi, iria lista a proposta (quando possuir) porém, na hora de gerar o relatório, ela ficaria oculta, isso?

**Comment by fullcontent** [comment]
@castroli 

Ela fica oculta na pesquisa somente, se quiser podemos inserir ela no relatório.

**Comment by castroli** [comment]
Ok Bruno, obrigado, vou encerrar o chamado.
