### ISSUE TITLE
Histórico

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#218]
Bruno, 
Notei que algumas alterações que realizamos no serviço não ficam gravadas no campo "Histórico" (exemplo, "Valor Total" e ou "Valor em Aberto" entre outro). Peço alterar e dexar de modo que qualquer campo que seja alterado após a criação do serviço, passe a constar no histórico, por favor.

**Comment by fullcontent** [comment]
@castroli Feito....

A questão do faturamento também é interessante ir para o histórico?

**Comment by castroli** [comment]
@fullcontent se for possivel, seria bem interessante. Mas teria que constar se o faturamento foi feito sob o valor total (quando o valor faturado é igual ao Valor Total) ou parcial (quando o valor faturado é inferior ao Valor Total).
