### ISSUE TITLE
Fuxo de renovações

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#219]
Olá Bruno, bom dia!

Estamos tendo alguns problemas na hora de **renovar as licenças**, ocorre que aqui internamente estão "esquecendo" de completar os campos (inclusive o campo de valor, oq  nos causa um prejuizo) . 
Atualmente, quando clicamos em renovar (tela 01) o sistema direciona para tela de "Detalhes do Serviço" (Tela 02), no caso temos que clicar no botão "Editar" para então incluir as informações necessárias (Tela 03), buscando sanar estes erros, peço as seguintes alterações: 

- [x] Fazer com que ao clicar no botão "renovar" o sistema direcione diretamente para tela de "Editar serviço" (Tela 03 ).
- [x] Fazer com que os **campos** "Solicitante", "Valor Total" e "Valor em Aberto" se tornem **obrigatórios** (não sendo possivel salvar sem estas informações preenchidas.

- [x] Uma dúvida, quando cadastramos um **novo serviço**, o campo "Valor em Aberto" fica oculto, apenas após cadastrado o serviço e clicamos no botão "editar" q ele vai aparecer e com o mesmo valor do campo "Valor total". Fizemos isso no passado para minimizar erros de digitação (super funcionou). Neste caso de renovação, seria possivel deixar tbm desta forma (seria o melhor cenário)?

Tela 01:
![image](https://user-images.githubusercontent.com/60766925/144432587-bd7da58c-5436-464e-a175-659a14d70fd9.png)

Tela 02:
![image](https://user-images.githubusercontent.com/60766925/144433420-a4b46729-1eba-4670-90c4-e797bb78800a.png)

Tela 03:
![image](https://user-images.githubusercontent.com/60766925/144433665-61b5fc98-3591-4fd1-af44-1d60375cf6ab.png)

**Comment by fullcontent** [comment]
@castroli 

Feito.

Qualquer problema é só reabrir o chamado!

**Comment by castroli** [comment]
@fullcontent 
Bruno, fiz alguns testes e esta apresentando erro no campo "Valor em Aberto". Ocorre que o valor que inserimos no campo "Valor Total" não esta se repetino no campo "Valor em Aberto", isso consequentemente gera erro no nosso faturamento. Peço corrigir.

![image](https://user-images.githubusercontent.com/60766925/145082740-272f15f0-0d4a-4b4e-9e01-d92bb583eb03.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido. Peço testar.
