### ISSUE TITLE
Erro nº de O.S

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#220]
Bruno, bom dia!
Conforme tela abaixo, quando vamos abri novo serviço para empresa "Empreendimentos Pague Menos" o campo de "Ordem de serviço" paralisou em EP1000. Peço corrigir por favor.

![image](https://user-images.githubusercontent.com/60766925/144850579-0ac8815d-0a0a-464c-9fc2-528c88712452.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido. Testado com serviços locais e funcional. Peço testar por gentileza.

**Comment by castroli** [comment]
@fullcontent Teste realizado, td certo, orbigado.
