### ISSUE TITLE
Novo campo em "Detalhes da unidade"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#221]
Bruno, boa tarde!
Peço incluir um novo campo denominado "**Área do Terreno:**" . 
Incluir entre os campos "Área da Loja:" e "Imóvel:", por favor.

![image](https://user-images.githubusercontent.com/60766925/145041471-48775d8b-71ba-4e44-8e67-c89d2f34686e.png)

**Comment by fullcontent** [comment]
@castroli Inserido!
