### ISSUE TITLE
 Interações

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#222]
@fullcontent 
No campo de interação identificamos o seguinte erro, se eu escrever por exemplo "@Caroline Martins Ok" a msg é enviada, porém, caso coloque primeiro um texto qualquer (exemplo"Ok @Caroline Martins" ) ele até puxa o @ do usuário, este usuário recebe a notificação, porém, a msg não vai.  Peço verificar, por favor

**Comment by fullcontent** [comment]
@castroli 

As mensagens estavam indo para o usuario mencionado, porém não estavam sendo listadas. Corrigido.
