### ISSUE TITLE
Erro faturamento - subserviço

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#224]
@fullcontent 
Identifiquei um erro no faturamento de serviço que possui subserviços e nos subserviços, segue.
Quando vou faturar diretamente no botão faturar de um serviço que possui subserviços e nos subserviços aparece o erro citado na tela 03, peço verificar, por favor.

http://sistemacelic.net/admin/servicos/3554
Tela 01
![image](https://user-images.githubusercontent.com/60766925/145292190-897612c1-379d-47bd-8c3d-995c57b12ed1.png)

Tela 02
![image](https://user-images.githubusercontent.com/60766925/145292244-d5fc678e-b5fe-4854-9d8f-84a28db227ee.png)

Tela 03 - Erro
![image](https://user-images.githubusercontent.com/60766925/145292284-2ed50ff7-eba2-4d74-8b87-b24aac4fe326.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!
