### ISSUE TITLE
Erro campo "valor em aberto"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#225]
Olá Bruno, boa tarde!
Notamos que o erro citado no chamado 219 voltou a se repetir. Ocorre que o valor que inserimos no campo "Valor Total" não está se repetino no campo "Valor em Aberto", isso consequentemente gera erro no nosso faturamento. Peço corrigir.

![image](https://user-images.githubusercontent.com/60766925/148271100-95a47038-e988-462e-94be-f4e095ebec9f.png)

**Comment by fullcontent** [comment]
@castroli 

Inseri uma função que "Espelha" o valor digitado no campo Valor Total para o campo Valor em Aberto.
Veja se dessa maneira resolve o problema de vocês. Se caso não, vou pensar numa outra lógica pra implementar.

**Comment by castroli** [comment]
@fullcontent Problema resolvido. Obrigado. 
Vou encerrar o chamado.
