### ISSUE TITLE
Incluir novo campo

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#226]
@fullcontent bom dia!

Solicito incluir na tela de "Detalhes da unidade" novo campo "Área do terreno", incluir logo a baixo do campo ja existente "Área da loja".

![image](https://user-images.githubusercontent.com/60766925/148550820-ca19dc8e-d977-405f-bfde-adabd8342e63.png)

**Comment by fullcontent** [comment]
@castroli Feito no chamado #221

**Comment by castroli** [comment]
@fullcontent 
Notei que na tela de "Detalhes da unidade" (tela 01) tem o campo "Área do terreno", porem na tela onde incluímos/editamos a informação (Editar unidade - tela 02) não tem o campo, peço ajustar.

Tela 01:
![image](https://user-images.githubusercontent.com/60766925/152164527-23a570c6-4250-4342-8682-d323f07e4945.png)

Tela 02:
![image](https://user-images.githubusercontent.com/60766925/152164371-3b0d323f-05ea-4bb5-b04d-e2704dbfb66f.png)

**Comment by castroli** [comment]
Blz @fullcontent agora aparece, mas peço ainda mais um pequeno ajuste, na tela "Editar unidade", peço fazer constar o campo 
 "Área" como "Área da loja" (igual consta na tela Detalhes da unidade, (imagem 02)).

Imagem 01: Ajustar para "Área da loja".
![image](https://user-images.githubusercontent.com/60766925/153241568-b78f05dd-79e0-4975-871e-a9f699e74198.png)


Imagem 02: Nesta tela ja está correto.
![image](https://user-images.githubusercontent.com/60766925/153241627-f2f54c32-4c62-43ba-8311-fb417ad3e839.png)
