### ISSUE TITLE
Filtro de busca por Proposta no Relatorio de Faturamento

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#228]
Inserir a possibilidade de busca por proposta no relatório de faturamento.

**Comment by fullcontent** [comment]
![image](https://user-images.githubusercontent.com/6120413/148668229-7479a777-d2f2-4cc5-b1eb-ecf98c50f5e8.png)

Ao selecionar a empresa o campo de propostas é atualizado com as propostas dos serviços relacionados aquela empresa.

**Comment by fullcontent** [comment]
@castroli 

Favor verificar se a funcionalidade ficou de acordo com o que conversamos.

**Comment by castroli** [comment]
Bruno, 
Quando seleciono a empresa e o periodo e clico em avança (sem selecionar nenhuma proposta), aparece esta tela de erro, peço verificar, por favor.

![image](https://user-images.githubusercontent.com/60766925/148767357-d79f2e0c-f7fe-4298-95d3-ab8fe626277f.png)

**Comment by fullcontent** [comment]
@castroli 

Ajustado, peço testar.
