### ISSUE TITLE
Erro pendências vinculadas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#229]
Bom dia @fullcontent 

Não estou conseguindo vincular mais de um serviço na pendência, segue detalhamento abaixo:

Tela 01: Iniciando o vinculo da O. S 066.
![image](https://user-images.githubusercontent.com/60766925/149140604-1369029e-1877-452e-b921-e0992924343c.png)

- [ ] Tela 02: **Erro 01** 
Após clicado em adicionar o vinculo da O.S 066 o campo fica em branco, ta ai o **primeiro erro.**
![image](https://user-images.githubusercontent.com/60766925/149140622-22cd89e7-5f04-4771-9b3e-1e2027d5a167.png)

Tela 03: 
Iniciando o vinculo da segunda O. S , a 069.
![image](https://user-images.githubusercontent.com/60766925/149140642-e327398e-5df6-4f0e-a48d-ca1519ede5e6.png)

- [ ] Tela 04:  **Erro 02** 
Após clicado em adicionar o vinculo da segunda O.S (069) o campo tambem fica em branco.
![image](https://user-images.githubusercontent.com/60766925/149140654-134c0215-081c-4152-bd85-7c7651049bfa.png)

- [ ] Tela 05:  **Erro 03** 
Após salvar a pendência, retorno na mesma e apenas o ultimo vinculo feito (069) que consta como vinculado, o primeiro feito na tela 01 e 02 (O.S 066) não consta). 
![image](https://user-images.githubusercontent.com/60766925/149140706-67d97c75-404f-46d3-8e7b-162b0bc47eef.png)

- [ ] Tela 06:  **Erro 04** 
Apenas após salvo, consigo vincular um segundo serviço, porém note que após clicar no botão adicionar o campo do serviço vinculado fica em branco, apenas após salvar e retornando para tela de pendência, que é possivel constatar o vinculo (telas 07 e 08). Não era assim, antes conseguia vincular varios no mesmo momento.
![image](https://user-images.githubusercontent.com/60766925/149140965-8923ba7a-7aae-48fb-86ef-ac5a2fbd290d.png)

Tela 07:
![image](https://user-images.githubusercontent.com/60766925/149140983-a4ff4d6b-5459-48a9-848e-13c700d54915.png)

Tela 08:
![image](https://user-images.githubusercontent.com/60766925/149141014-79feb3df-4faf-48ef-8aa0-3ba317f48e65.png)

**Comment by fullcontent** [comment]
@castroli 

Repeti o teste aqui e a principio não encontrei o erro.
Pode mandar um vídeo explicando melhor, por gentileza?

**Comment by castroli** [comment]
@fullcontent 
Agora qu entendi a lógica, havia pensado que ao clicarem adicionar o campo com a O.S que criei passaria para baixo, mas agora que entendi que não, quando clico em adicionar eu não estou adicionando um novo vinculo de o.s, mas sim um novo campo. Agora ficou claro, erro meu. Chamado encerrado.
