### ISSUE TITLE
Erro ao excluir um serviço

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#230]
@fullcontent 
Criei um serviço teste para fazer alguns testes no faturamento e agora estou tentando excluir o serviço, porém não consigo, esta dando a erro conforme tela abaixo. 
Ressalto que o faturamento vinculado ao serviço ja foi excluído.
Link do serviço: http://sistemacelic.net/admin/servico/delete/5010

![image](https://user-images.githubusercontent.com/60766925/149145282-917220d2-26ec-4e55-9b81-c6c9289cc4ea.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido. Peço testar.
