### ISSUE TITLE
Listagem de Serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#231]
@fullcontent bom dia!

Peço realizar uma alteração na listagem de serviços, remover a coluna "Tipo" e incluir no lugar coluna "Cliente".
Esta culuna de cliente temos ela lá na "Listagem de faturamentos", até poderia ser a Razão social, porém, esta "cliente" colocamos de uma forma abreviada.

![image](https://user-images.githubusercontent.com/60766925/149515586-0eadbf78-03da-486c-807a-aa89f646be32.png)

**Comment by fullcontent** [comment]
@castroli 

Ajustado!
