### ISSUE TITLE
[BUG] ERRO "VALOR" NO CAMPO DE CONTROLE DE TAXAS

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#233]
Bruno, boa tarde
Notei hoje um erro no CELIC que até então não tinha acontecido. 
Quando estou na tela geral do serviço, no campo de "controle de taxas" aparece por ex. uma taxa de R$ 45,50. Porém, se eu entro dentro do "controle de taxas" ele muda esse valor para "4,55". Observei isso em 2 serviços que fui pagar taxas hoje, mas não lembro o código do outro. Abaixo coloco print do erro no serviço 4087 (taxas código 2591).

![1](https://user-images.githubusercontent.com/60766925/150210965-92d08bec-1304-4b26-9446-eee1ab819c34.png)

![2](https://user-images.githubusercontent.com/60766925/150210977-a46d3213-1c84-4efa-abb6-f3b2594d7f86.png)

**Comment by fullcontent** [comment]
@castroli Corrigido.

**Comment by castroli** [comment]
Bruno, 
Ainda está com erro o campo de valor. Está dando alguma interferência com relação ao ponto/vírgula.
Exemplo: Está lançada uma taxa com o valor de R$152,35.
Quando eu acesso o campo pra fazer alguma alteração (anexar o comprovante por ex.) e dou um salvar na tela, ele muda esse valor e deixa sem o ponto e sem vírgula. 
Fiz uma simulação abaixo:

![1](https://user-images.githubusercontent.com/60766925/152169464-d8d4d87f-7366-4267-9520-676d1cb912ef.png)

![2](https://user-images.githubusercontent.com/60766925/152169491-a67a4776-4c34-456c-b52f-4c715dc20360.png)

![3](https://user-images.githubusercontent.com/60766925/152169512-331d2df6-781d-4b22-a8fa-c273d1b4865c.png)

![4](https://user-images.githubusercontent.com/60766925/152169536-142bff2b-9e46-4463-8f45-c78fd7fca051.png)

![5](https://user-images.githubusercontent.com/60766925/152169561-eea1e322-5519-4fcf-82e4-f6d6f6a60241.png)

Simulando um relatório de reembolso para essa taxa do exemplo, o sistema geraria com o valor errado R$15,235.00 
![image](https://user-images.githubusercontent.com/60766925/152169955-fb023af0-65f5-441e-9ba9-951be9e73d29.png)

Consegue verificar, por favor? E seria possível o sistema utilizar a pontuação modelo BR? Pra não ter essa confusão de ponto e vírgula?

**Comment by fullcontent** [comment]
@castroli 

Foi criada uma função de ajustar os valores com formato BR na criação e edição.

Peço testar por gentileza;
