### ISSUE TITLE
[BUG] LOGO CASTRO - FATURAMENTO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#234]
Bruno, bom dia!

Notei hoje que no relatório de faturamento não está aparecendo o logo da empresa.
Peço corrigir, por gentileza.

![image](https://user-images.githubusercontent.com/60766925/152164190-4c7f8be8-90c2-4bcb-b2de-b1ed337221d5.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido

**Comment by castroli** [comment]
Bruno, 
O erro ainda permanece.
Peço verificar. 

![image](https://user-images.githubusercontent.com/60766925/152358745-a10eb4d7-5a4f-4c4c-996d-8a192331e7e6.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.

**Comment by castroli** [comment]
Bruno, bom dia!
Este erro está acontecendo novamente, tanto no relatorio de faturamento quanto no reembolso.
Peço verificar com urgencia.

![image](https://user-images.githubusercontent.com/60766925/173089338-7b7fe8b4-6b00-48b8-bbef-9b5042993042.png)
