### ISSUE TITLE
Alterações visuais na tela "Detalhe do Serviço"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#235]
@fullcontent 
Peço realizar a seguinte alteração:

- [x] Na linha detalhes, substituir o numero da O.S pelo nome do serviço , por exemplo, na imagem 01 está "**Detalhes do serviço DA0060**", no caso ficaria "**Detalhes do serviço: AVCB**", conforme ilustrado na imagem 02. 
- [x] Peço tambem deixar esta linha em negrito.
- [x] Ultimo pedido é colocar a linha do nome do serviço por primeiro, conforme ilustrado na imagem 3.

Imagem 01
![image](https://user-images.githubusercontent.com/60766925/152339581-ac85fb54-1c76-4b91-a446-8142cb8d8f78.png)

Imagem 02:
![image](https://user-images.githubusercontent.com/60766925/152341012-5fa48e75-1904-4bd4-969e-fc9a72c0b9fa.png)

Imagem 03:
![image](https://user-images.githubusercontent.com/60766925/152341075-cdb846c8-e559-411b-9df0-b7c7bad1ecf3.png)

**Comment by fullcontent** [comment]
@castroli 

Feito!
