### ISSUE TITLE
Erro visualizar histórico

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#236]
@fullcontent 
Estou tentando visualizar o histórico do serviço 4372, porém, esta dando tela de erro, segue.
http://sistemacelic.com/admin/servicos/4372
![image](https://user-images.githubusercontent.com/60766925/152347622-2f0fcac5-47b2-462e-804b-2bfd3ba7c152.png)

**Comment by fullcontent** [comment]
@castroli 

Resolvido.... 

Problema gerado por usuario concluir a pendencia depois de expirado o login.
