### ISSUE TITLE
DATA DE FATURAMENTO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#237]
@fullcontent 
Peço incluir na tela de  "**Resutado da busca**" de faturamento uma nova coluna com a data de faturamento, no caso, se o serviço ja foi faturado, informar a data, se ele ainda não foi, deixar campo em branco. Isso nos ajudará a detectar tanto o dia de faturamento, como possiveis erros.

![image](https://user-images.githubusercontent.com/60766925/152445663-2b0c9d2c-cf55-4fae-9978-64306db2e094.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar.

**Comment by castroli** [comment]
Ótimo, obrigado Bruno
.
