### ISSUE TITLE
Licenças de Operação

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#238]
@fullcontent 
Até alguns dias quando iamos criar um novo serviço onde o campo "Tipo" é "Licenças de Operação" o Campo "Serviço" aparecia uma lista suspensa com o nome das licenças, no momento não esta mais aparecendo, peço ajustar.

![image](https://user-images.githubusercontent.com/60766925/155196174-c20f2813-acff-4ba5-8075-2d3a466ba7e7.png)

**Comment by fullcontent** [comment]
@castroli 

Esse erro foi causado pelo avanço no desenvolvimento das propostas. Tivemos um conflito com o LPU antigo e já foi resolvido.
Qualquer problema é só reabrir esse chamado.
