### ISSUE TITLE
Campo Vencimento Licença

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#239]
@fullcontent boa tarde!
Notei que quando altero o campo "Tipo de Licença" para "Definitiva", o campo "Vencimento Licença" não esta mais bloqueado com a data "31/12/2059", peço bloquear como era feito até então.

**Comment by castroli** [comment]
Segue tela comprovando.
![image](https://user-images.githubusercontent.com/60766925/156412144-1c05aa3e-e2e2-4a1e-9860-cf13bce1141f.png)

**Comment by fullcontent** [comment]
@castroli 

Esse erro foi causado por um conflito com o novo módulo de propostas. Foi solucionado provisóriamente até finalizar o módulo.
