### ISSUE TITLE
Organizar lista suspensa

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#240]
@fullcontent 
No Relatório de faturamento - lista empresas, campo "Selecione a empresa:" peço:
 
- [x] organizar os nomes de forma A-Z.
- [x] Se possivel, incluir um campo de busca (Pesquisar).

![image](https://user-images.githubusercontent.com/60766925/157046616-960e4423-3133-449a-aef0-618f109a55cd.png)

**Comment by castroli** [comment]
@fullcontent 
No quadro de "Cadastrar pendência" campo "Responsável" peço:

- [ ] Organizar os nomes de forma A-Z.

![image](https://user-images.githubusercontent.com/60766925/157083377-b66a2158-32cb-4374-af44-b727a6321d3d.png)

**Comment by castroli** [comment]
@fullcontent 
No quadro "Propostas" peço:

- [ ] Organizar os numeros das propostas de forma A-Z.

![image](https://user-images.githubusercontent.com/60766925/158263022-b6bd5dfc-d644-4f7a-babf-df37ad8b4c61.png)

**Comment by fullcontent** [comment]
@castroli 

Inserido campo de buscar empresa no relatorio de faturamento. Peço testar por gentileza.

**Comment by castroli** [comment]
Muito bom, obrigado.
