### ISSUE TITLE
Módulo - Cadastrar solicitante

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#242]
@fullcontent 
Atualmente temos problemas com este campo, ao criar os Serviços , cada profissional coloca o nome de uma forma. Pensando em resolver este problema peço criar um novo módulo onde possamos cadastrar os solicitantes, penso em algo bem simples, com os seguintes campos:

- Solicitante:
- Empresa (listar as empresas cadastradas):
- Departamento:
- Email:
- Telefone:

Sempre que precisarmos informar o solicitante, puxar desta lista de cadastros e sempre vinculado a empresa que estamos tratando (exemplo, se escolhido a empresa Pague Menos, listar apenas os solicitantes desta empresa).

**Comment by fullcontent** [comment]
@castroli 

Feito as alterações e inserido banco de dados conforme a tabela.
Peço testar por gentileza.
