### ISSUE TITLE
[MELHORIA] FATURAMENTO

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#244]
Bruno, bom dia!

Solicito por gentileza inlcuir o campo "solicitante" no relatório de faturamento. Atualmente não temos esta coluna no relatório.
Peço incluir a coluna entre "serviço" e "total", conforme imagem abaixo:

![1](https://user-images.githubusercontent.com/60766925/159020006-e52c91a8-a861-4c26-9b75-f227b0260d69.png)

**Comment by fullcontent** [comment]
@castroli 

Feito
