### ISSUE TITLE
Campo Área do terreno 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#245]
@fullcontent 

Notamos que ao incluir a informação de área do terreno, após clicar no botão salvar a informação some, peço verificar.

![image](https://user-images.githubusercontent.com/60766925/161275157-42d3903b-d621-4029-92e5-b78def3dd410.png)
![image](https://user-images.githubusercontent.com/60766925/161275396-2a97296e-3efc-48ae-b5aa-4e21f94b97dd.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.
