### ISSUE TITLE
Botão "Todos os serviços"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#246]
@fullcontent 

- [x]  Na tela de "Detalhes da unidade" nos quadros de "Licenças de Operação", "Projetos/Licenças - não renováveis", "Controle de certidões", "Controle de taxas" e "Facilities e Real Estate" tem o botão "Todos os serviços", inicialmente a ideia é que ao clicar neste, apareça tambem os os serviços desta unidade que estão com a situação igual a "Arquivado". Peço ajustar por favor.

 
![image](https://user-images.githubusercontent.com/60766925/161340975-a65c78e5-a484-48e2-916d-a58c4ca75a72.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar por gentileza e reabrir o chamado se houver algum problema!
