### ISSUE TITLE
[MELHORIA] REEMBOLSO/INCLUIR ORGANIZADORES E CAMPO DE PESQUISA

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#247]
Bruno, boa tarde!

Por gentileza, precisamos incluir "organizadores" na tela de taxas que eu seleciono para gerar um reembolso e também o campo de "pesquisa"
http://sistemacelic.com/admin/reembolso/step2

Local a incluir os organizadores e campo de pesquisa:
![reembolso](https://user-images.githubusercontent.com/60766925/162054021-69411bea-6a15-4d5a-b30d-7ee28c86a611.png)

No faturamento, por exemplo, nós já temos esses filtros/organizadores e campo de pesquisa, precisamos deste mesmo fomato para o reembolso.
http://sistemacelic.com/admin/faturamento/step2

Tela faturamento com "organizadores" e "campo de pesquisa":
![faturamento](https://user-images.githubusercontent.com/60766925/162053768-9670511f-a1c1-401a-b966-301986ced148.png)

Obrigada

**Comment by fullcontent** [comment]
@castroli 

Ajustado! Qualquer problema é só reabrir o chamado!
