### ISSUE TITLE
Melhoria Plataforma - Cadastro de Solicitante

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#253]
@fullcontent 

- [x] Peço incluir opção de selecionar mais de uma empresa.

![image](https://user-images.githubusercontent.com/60766925/163806328-ad7d750e-79f8-4826-85f6-34186d720f61.png)

**Comment by castroli** [comment]
- [ ] No campo de telefone, incluir uma formatação padrão, exemplo (99) 99999-9999. Sempre o código de área entre parênteses. Depois a opção de 5 número, hífen, mais 4 números (não autorizando incluir mais números). Com isso deixaremos este campo padrão.
![image](https://user-images.githubusercontent.com/60766925/163806789-a076592a-7fa3-4555-a6b7-704e61975d45.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido, peço testar.
