### ISSUE TITLE
Erro - Cadastro de Solicitante

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#254]
@fullcontent 
Na tela do serviço não esta aparecendo a lista dos solicitantes cadastrados, peço verificar por favor.

![image](https://user-images.githubusercontent.com/60766925/163807438-7cd6d765-e245-470c-8918-caee4a45cc1f.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido paliativamente.

**Comment by fullcontent** [comment]
@castroli 

corrigido juntamente com o chamado #242.
Qualquer problema é só reabrir.
