### ISSUE TITLE
Melhoria - Cadastrar unidade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#255]
@fullcontent 
Pensando em minimizar erros de digitação, peço realizar a seguinte alteração na tela de "Cadastrar unidade". 

- [x] Ao preencher a campo "Empresa" peço automaticamente preencher o campo "Razão Social", puxando esta informação do banco de dados da empresa. Exemplo: Para empresa Camicado consta no banco de dados a Razão Social "Maxmix Comercial Ltda", desta forma na tela de "Cadastrar unidade", ao selecionar a empresa camicado, automaticamente preencher o campo Razão Social " da unidade como "Maxmix Comercial Ltda" (identico ao da emrpesa).

Atualmente ele puxa do banco de dados da receita federal, mas como vem tudo em caixa alta, a gente redigita passando para nosso padrão, com isso ocorre os descompassos e erros. 

![image](https://user-images.githubusercontent.com/60766925/163830558-528fc84a-08fe-4a5d-aeb0-b4d378eb24a7.png)

![image](https://user-images.githubusercontent.com/60766925/163830882-d6e7e72c-efe6-4511-b0bf-4c22489d4ac5.png)

**Comment by fullcontent** [comment]
@castroli 

Inserido função de formatar o texto na hora de puxar da receita. Qualquer problema é só reabrir o chamado.
