### ISSUE TITLE
Erro ao carregar arquivos - CELIC.NET

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#257]
@fullcontent 
No CELIC.NET não estamos conseguindo abrir nenhum anexo, peço verificar.
Msg de erro "Não foi possível encontrar a página deste sistemacelic.net".

http://sistemacelic.net/public/uploads/boletos/19581120220418625dc2d3c2a86.pdf
![image](https://user-images.githubusercontent.com/60766925/165085513-fa269d6a-1e06-48b5-9a5b-c182ea5bd7b4.png)

**Comment by fullcontent** [comment]
@castroli 

Estamos usando atualmante o servidor .com para arquivos. Basta mudar na barra de endereços.

Qual o serviço relacionado a esse arquivo? Vou avaliar se consigo implementar essa funcionalidade de maneira automatica. Isso se dá por conta da mudança de servidor, com isso alguns arquivos ficaram com o link antigo.
