### ISSUE TITLE
ERRO SOLICITANTE 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#258]
Bruno, boa tarde

Notei que ao gerar o relatório de reembolso e de faturamento, não está aparecendo o nome do "solicitante" para alguns casos, e sim o número/código. 
Consegue corrigir, por gentileza?

**Comment by castroli** [comment]
![1](https://user-images.githubusercontent.com/60766925/166824599-b8ef8a17-5e90-44dd-aff9-97d00ede2087.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!

**Comment by castroli** [comment]
Bruno, ainda não está funcionando. Veja exemplo abaixo
Reembolso > Pague Menos > mês de Abril

Aparecem alguns códigos (9 e 18, por ex.) no lugar do nome do solicitante.

![image](https://user-images.githubusercontent.com/60766925/167196109-a81e456c-84d2-4656-bcfd-f01570cf5db9.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!

**Comment by castroli** [comment]
Bruno, bom dia

Agora sumiram os códigos, porém, o nome do solicitante está errado. Veja na tela abaixo, o serviço 5216 (Pague Menos loja 1337) está como solicitante a Carlysandra Lima, mas quando gero a tela de reembolso, aparece em nome do Adriano Reis. Tem vários casos assim... Tentamos mudar pra outros solicitantes direto na tela de serviço, mas não muda, ao gerar relatório de reembolso sempre está puxando o Adriano Reis (que inclusive não é cliente da Pague Menos, é de outra empresa).

Peço verificar, por favor.

![1](https://user-images.githubusercontent.com/60766925/167421429-903d6541-8fd8-4ea2-b16f-7b57218dae75.jpeg)

![2](https://user-images.githubusercontent.com/60766925/167421716-722e9d81-debd-447d-bcc1-00fe1fc9043a.png)

**Comment by fullcontent** [comment]
@castroli 

Fiz um novo ajuste na logica de buscar solicitantes, aparentemente resolveu o problema agora. Vamos manter esse chamado aberto até que vocês chequem se está tudo ok.
