### ISSUE TITLE
Incluir novo campo - RIP

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#259]
@fullcontent 

- [ ] Na tela de Dados da unidade, peço incluir novo campo (aberto) com nome "RIP", pode diminuir um pouco o campo "Código" e incluir este novo campo na mesma linha, apóis a "Inscrição Imobiliária". Incluir tambem este campo no "Relatório Completo de Serviços"

![image](https://user-images.githubusercontent.com/60766925/166825689-e782e656-d7a7-4d0a-9e8d-110997365e32.png)

**Comment by fullcontent** [comment]
@castroli 

Feito!
