### ISSUE TITLE
Erro - solicitante

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#261]
@fullcontent 

- [x] Notei que ao alterar o solicitante no histórico do processo esta aparecendo "Diego Castro Alterou responsavel_id para 27". Peço alterar e fazer constar os nomes no lugar de codigos.

![image](https://user-images.githubusercontent.com/60766925/167516806-b3f71b2f-cdfc-4fcf-becc-8d0b3ee8f661.png)

**Comment by castroli** [comment]
@fullcontent 

- [ ] Ao criar uma proposta o campo "solicitante" não esta aparecendo a lista, esta um campo aberto ainda, peço ajustar.

![image](https://user-images.githubusercontent.com/60766925/167658755-60181eb7-8d54-4462-9399-9aa24c690def.png)

**Comment by castroli** [comment]
@fullcontent 

- [ ] O Relatório Completo de Serviço na coluna Solicitante não esta aparecendo o nome do solicitante, apenas um numero, consegue ajustar por favor.

**Comment by castroli** [comment]
@fullcontent 

- [ ] Na tela "Listagem de serviços" na coluna Solicitante não esta aparecendo o nome do solicitante, apenas um numero, peço ajustar por favor.

![image](https://user-images.githubusercontent.com/60766925/168297146-d742f64e-f774-46b9-a52f-d6e89b7e2e1f.png)

**Comment by fullcontent** [comment]
@castroli 

Todos corrigidos.

**Comment by castroli** [comment]
@fullcontent 
Na tela "Listagem de serviços " no campo de "Solicitante" esta aparecendo uma numeração no lugar do nome, peço ajustar, por favor.

![image](https://user-images.githubusercontent.com/60766925/168833405-d9f206d5-9580-489f-833d-72013c42a3d4.png)

**Comment by castroli** [comment]
> @castroli
> 
> Todos reparados.
@fullcontent 
A lista de serviços continua aparecendo (para alguns serviços) o código no lugar do nome, peço verificar. 

![image](https://user-images.githubusercontent.com/60766925/169869271-5acdb77d-e991-4456-a43c-5ada2a947403.png)

**Comment by fullcontent** [comment]
@castroli 

Revisado. Só reabrir se tiver algum problema
