### ISSUE TITLE
Erro Faturamento - Campo nº Proposta

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#263]
@fullcontent 
Bom dia Bruno.
Estou fazendo o faturamento da Pague Menos e na lista do faturamento não esta aparecendo o numero das propostas recentes, peço ajustar, por favor.

![image](https://user-images.githubusercontent.com/60766925/168821690-a69c01ef-16d9-4c1c-99b6-f3389e28547a.png)

**Comment by fullcontent** [comment]
@castroli Corrigido.

Qualquer problema é só reabrir o chamado.
