### ISSUE TITLE
Incluir novo campo - Departamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#264]
@fullcontent 
Na tela de Serviços, peço incluir novo campo "Departamento" no local mencionado na imagem abaixo. Apenas precisamos alinhar como este campo irá funcionar, uma vez que no cadastro do solicitante ja incluímos a informação do departemento do solicitante, porém, temos a questão de profissionais que trocam de departamento, conforme detalhei via WhatsApp.

![image](https://user-images.githubusercontent.com/60766925/168828203-72dabd70-f7e1-4a55-9560-4ef4517090b1.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar por gentileza.

**Comment by castroli** [comment]
@fullcontent 
Precisamos alinhar dois pontos:

- [ ] Incluir este campo no "Relatório Completo de Serviços";
- [ ] Incluir os departamentos em uma lista (para não ter erro de digitação), este caso quero falar contigo primeiro para alinharmos a melhor forma. Após alinharmos detalho melhor aqui.

**Comment by fullcontent** [comment]
@castroli 

Consegue me enviar uma planilha onde conste os departamentos que já foram utilizados? Assim posso gerar um banco de dados com esses departamentos e também incluir um botão de cadastro caso tenha necessidade.

**Comment by castroli** [comment]
Licenciamento
Permits
Regulatório
Obras
Expansão
Compras
Outros

**Comment by fullcontent** [comment]
@castroli Feito!
Reabrir o chamado para qualquer problema
