### ISSUE TITLE
Relatório Completo de Serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#266]
@fullcontent 
Atualmente apenas o meu usuário e o da Aline que consegue gerar o "Relatório Completo de Serviços", peço deixar disponivel mais estes usuários:
kauane@castroli.com.br
aryane@castroli.com.br
camille@castroli.com.br
caroline@castroli.com.br
andre@castroli.com.br

**Comment by fullcontent** [comment]
@castroli 

foi mudado de lugar o link para o relatorio:
![image](https://user-images.githubusercontent.com/6120413/169923786-e375ec51-1139-41c6-8f9f-7fcd8567ec10.png)


qualquer problema é só reabrir o chamado.

**Comment by castroli** [comment]
@fullcontent 
Ok, apenas uma correção, o usuário "franciele-santana@adiser.com.br" senha bk2021 tambem esta tendo acesso a este relatório completo. Este usuário é de um cliente que utiliza o sistema como admin, porém, ele não pode ter acesso a informações de outros clientes. Peço excluir a opção deste usuario ter acesso ao "Relatório Completo de Serviços" ou então limitar o relatório apenas as unidades da empresa "Adiser Burguer King" e "Adiser Burguer King-SP".

**Comment by fullcontent** [comment]
@castroli 

Voltado o menu para o lugar anterior, porém com a regra para não exibir para os usuarios mencionados.

qualquer problema é só reabrir o chamado.

**Comment by castroli** [comment]
@fullcontent 
Realizei o teste e para os usuários citados anteriormente não esta mais aparecendo mais o  "Relatório Completo de Serviços", e esta aparecendo os items abaixo que não podem aparecer para eles:
- Usuários
- Solicitantes
- Listagem geral do serviços
- Faturamentos
- Reembolsos

Preciso que eles (usuários citados abaixo) tenham acesso apenas no "Relatório Completo de Serviços".

kauane@castroli.com.br
aryane@castroli.com.br
camille@castroli.com.br
caroline@castroli.com.br
andre@castroli.com.br
