### ISSUE TITLE
Erro Propostas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#267]
@fullcontent 
Não estamos conseguindo criar novas propostas, esta dando tela de erro, peço verificar.

![image](https://user-images.githubusercontent.com/60766925/170326846-0675a5ef-f63e-4d2b-b392-c06a421b63ac.png)
![image](https://user-images.githubusercontent.com/60766925/170326873-dcab6b13-5a3a-43c1-9737-e5d2b122beba.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido...
Erro causado pela falta de preenchimento do campo responsável geral.

Posso retirar esse campo e deixar somente o responsavel pelo servico?

**Comment by castroli** [comment]
- [ ] Criamos a proposta de nº 1129 e ao clicar no serviço que ela criou automaticamente esta dando tela de eero, segue.http://sistemacelic.com/admin/servicos/5819
![image](https://user-images.githubusercontent.com/60766925/170511473-1eb8f21c-a0c7-4b11-9baa-dec36f19f6c4.png)
![image](https://user-images.githubusercontent.com/60766925/170511493-522c004e-78a7-4148-b681-c07b07f61bf5.png)

**Comment by castroli** [comment]
- [ ] Erro ao criar proposta para **loja 1258 Unidade: BOV10-Carana-RR da empresa Pague Menos**. Não sei se é coincidencia, mas a tela de erro esta dando apenas para proposta criada para esta loja.
http://sistemacelic.com/admin/proposta/pdf/1135

![image](https://user-images.githubusercontent.com/60766925/170513153-a85ea09e-df4a-40d5-a3f8-8709993b878e.png)
![image](https://user-images.githubusercontent.com/60766925/170513178-28654d72-b425-4737-87c5-931ca0845834.png)
![image](https://user-images.githubusercontent.com/60766925/170513192-692b2092-1e93-4853-b889-b8eaa134ac7c.png)

**Comment by fullcontent** [comment]
Os erros acima foram corrigidos.

Detalhe sobre o erro da proposta 1135:

Ele se deu por conta de colar os dados do campo de documentos obrigatórios. Por hora precisamos que seja preenchido diretamente no campo, sem copiar de outro lugar o texto. Vou implementar um componente para tratar esse texto antes de enviar ao banco de dados para evitar futuros erros.
