### ISSUE TITLE
Erro Propostas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#269]
@fullcontent 

- [x] Notamos que voltou a aparecer o Subtotal nas propostas, peço corrigir por favor.
Este item ja havia sido corrigido anteriormente via chamado nº 241, mas retornou a aparecer.

![image](https://user-images.githubusercontent.com/60766925/170722662-87cc1ed3-c52c-4238-a7a9-d109ea7870cb.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido
