### ISSUE TITLE
Erro - Serviço 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#270]
@fullcontent 
Erro ao clicar nos serviços citados abaixo: 
Estes serviços foram cadastrados automaticamente da proposta 1135. 
![image](https://user-images.githubusercontent.com/60766925/170776643-2d0b3398-8171-45b3-85c7-0af8c38f9a67.png)
http://sistemacelic.com/admin/servicos/5823
![image](https://user-images.githubusercontent.com/60766925/170776681-20e33bc2-0736-4ce3-a3a7-e85c1a252b03.png)
http://sistemacelic.com/admin/servicos/5824

**Comment by fullcontent** [comment]
@castroli 

Corrigido
