### ISSUE TITLE
Inserir regra de usuarios ativos

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#271]
USUARIOS INATIVOS NAO APARECEM NA LISTAGEM DE RESPONSAVEIS

**Comment by castroli** [comment]
@fullcontent 
Notei que os usuários inativos, ainda estão aparecendo nas listagem do campo "pendência", peço corrigir.

http://sistemacelic.com/admin/pendencia/create/6094
![image](https://user-images.githubusercontent.com/60766925/180878975-9834df40-0a22-4de0-8369-789d876f46d1.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!

**Comment by castroli** [comment]
@fullcontent 

Ao criar pendência esta tudo certo, mas ao **alterar o responsável de uma pendência já existente** (independente de quando foi criada esta pendência) a lista aparece com todos os usuários cadastrados, peço ajustar.

![image](https://user-images.githubusercontent.com/60766925/181376683-9826a5dc-352c-4581-9f73-d4199469e3ff.png)
