### ISSUE TITLE
[BUG] ERRO REEMBOLSO - DOWNLOAD ARQUIVO ZIP 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#273]
Bruno, bom dia!

Gerei um reembolso há pouco, e não estou conseguindo fazer o download no formato zip.

Reembolso Pague Menos:
![image](https://user-images.githubusercontent.com/60766925/184641952-a35fcd2e-39d0-4ba6-b737-6d7e327b5494.png)

Tela de erro:
![image](https://user-images.githubusercontent.com/60766925/184642146-35ae8052-893a-4e53-88fe-2a67bc759131.png)

**Comment by fullcontent** [comment]
@castroli 

Consegue fazer um teste de gerar novamente esse reembolso por gentileza?
