### ISSUE TITLE
Erro - Reembolso

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#275]
@fullcontent 
Bruno, verificando o relatório de reembolso, a coluna solicitante esta aparecendo um codigo no lugar do nome, peço corrigir, por favor.

![image](https://user-images.githubusercontent.com/60766925/185716589-53d8ea3e-1743-4c29-a2a2-c0ac97c6c22f.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, reabrir o chamado caso o problema persista
