### ISSUE TITLE
Erro - Relatório de Seviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#276]
@fullcontent 

- [x] Nos **campos de datas**, quando estão em branco no CELIC ao gerar relatório aparece a data do dia, peço ajustar.
- [x] Coluna **Finalizado** está aparecendo alguns campos como "N/A", esta errado, ou deve constar a data que foi finalizado o serviço ou se estiver com a situação diferente de finalizado, este campo deverá estar em branco. Ainda sobre este item, notei que tem casos que a na coluna **Finalizado**  esta como **N/A** e na coluna **Situação** como **Finalizado**, isso esta errado, deveria constar a data que foi finalzado.

**Comment by fullcontent** [comment]
@castroli 

Feito, solicito teste no excel para encerrar o chamado.

**Comment by castroli** [comment]
O outro item "**Coluna Finalizado**" esta correto.

**Comment by fullcontent** [comment]
Caso tenha algum problema é só reabrir o chamado.
