### ISSUE TITLE
Erro - Relatório Taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#277]
@fullcontent 

- [x] Na coluna de **Valor da taxa**, está aparecendo um valor inteiro, sem virgula, quando incluímos na coluna passando para "moeda" o valor fica errado, pois incluímos dois zeros a mais. Exemplo, na primeira linha, O.S EP2005, consta uma "Taxa RT Execução" no valor de 10869, quando incluímos na coluna para reconhecer como moeda, o valor apra R$ 10.869,00, sendo que o correto seria R$ 108,69.  
### Valor que aparece no importar do CELIC:
![image](https://user-images.githubusercontent.com/60766925/185979367-c0692019-e4e5-4507-bd76-3df9c0d138c3.png)

### Valor que aparece após formatar como moéda:
![image](https://user-images.githubusercontent.com/60766925/185979108-bb8a9e87-26c1-4926-8b15-febd2e7dc5c2.png)
![image](https://user-images.githubusercontent.com/60766925/185979158-b9beae89-ef68-4951-b75d-fdd1af3056df.png)

- [x] Campo de datas: O padrão de datas que enviamos ao cliente é (exemplo) 22-Ago-22, o problema que quando importamos do CELIC acredito que estas colunas de datas estão sendo reconhecidas como texto, pq altero o formado o modelo citado abaixo, mas não é reconhecido, porém, se eu clicar duas vezes no campo ai sim reconhece no formado que incluí, peço verificar. 
![image](https://user-images.githubusercontent.com/60766925/185979972-b187e356-4e4b-4cc5-a745-3b8d592fa8b6.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar no excel por gentileza.

**Comment by castroli** [comment]
Deu Certo @fullcontent , vou encerrar o chamado. Obrigado.
