### ISSUE TITLE
Melhoria - Listagem de faturamentos

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#278]
@fullcontent 
Peço inlcuir na tela de "listagem de faturamento" a opção de visualizar até 100 resultados por página.

http://sistemacelic.com/admin/faturamentos
![image](https://user-images.githubusercontent.com/60766925/186016185-216da2b5-9e29-42f8-a037-140899a5afda.png)

**Comment by fullcontent** [comment]
@castroli 

feito!
