### ISSUE TITLE
Melhoria - Faturamento - Em criação

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#279]
@fullcontent 

Diariamente sentimos falta de saber qual número da Nota Fiscal que foi cobramos tal serviço, seguindo esta necessiada, pensei em incluir um novo campo com o número da NF no faturamento e também no serviço, um vinculado ao outro, exemplo:

- [x] Tela "**Resumo do faturamento**" incluir coluna para colocarmos o numero da NF emitida para o serviço:

![image](https://user-images.githubusercontent.com/60766925/186017553-c2d2ba89-ba03-46a3-a22f-bcd3ee72fb14.png)
  

- [x] Tela "**Editar serviço**", incluir campo para visualizarmos ou colocarmos o número da NF emitida para o serviço. Digo visualizarmos ou colocarmos pq pode ser que não tenha sido colocado no momento de gerar o faturamento, então colocamos por aqui:

![image](https://user-images.githubusercontent.com/60766925/186019828-42596e3b-2c6f-4717-a5f4-3f7489eab9e1.png)

- [x] #281
![image](https://user-images.githubusercontent.com/60766925/186219252-06a418b7-5138-42a3-83e5-c4ede6569fea.png)

- [x] "**Relatório de Faturamento**": Incluir hiperlink com botão para acessar o documento que esta sendo faturado. Penso que o ideal seria um botão ao lado de cada serviço, segue uma imagem abaixo. Outro ponto importante é criar uma opção de salvar este faturamento com ou sem esta opção de hiperlink, isso pq não são todos os clientes que receberão desta forma.
![image](https://user-images.githubusercontent.com/60766925/186223538-ac46db14-93b2-4d13-8ba0-c38ab961b4bb.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar por gentileza!

**Comment by castroli** [comment]
@fullcontent boa tarde!
Conforme falamos ontem, na tela de "Resumo do faturamento" esta nova coluna que incluiu tem que ser aberta para edição, a idéia é incluir ali o número da NF emitida para o serviço, esta por sua vez irá aparecer la na tela de detalhes do serviço. O perfeito seria, se por um acaso não ser incluído o numero da NF no momento da elaboração do faturamento, pela tela de "Editar Serviço", poder tbm incluir o número da NF.
