### ISSUE TITLE
Listagem de serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#28]
Incluir subitem com:
- Lista geral de serviços: listagem com todas as informações que temos.
- Serviços em andamento;
- Serviços finalizados;
- Serviços vigentes;
- Serviços vencidos;

**Comment by fullcontent** [comment]
Filtrar exibição listando os serviços do usuário logado.

**Comment by fullcontent** [comment]
Inserir logica de exibição para administradores.

**Comment by fullcontent** [comment]
Inserir menu com filtro de empresas inativas
