### ISSUE TITLE
Melhoria - Propostas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#280]
@fullcontent 
Ainda não estamos no modelo ideal na plataforma de propostas, abaixo segue algumas alterações a realizar:

- [x] Incluir a opção de editar os itens (nome do serviço, escopo e valor) das propostas que estão com a situação "Em análise" e "Revisando" (após alterado para aprovado, não apresentar mais estas opções).
- [ ] Opção de organizar e alterar o número dos itens e dos subitens.

**Comment by fullcontent** [comment]
@castroli 

Inserido a opção de editar os itens na proposta. A parte de organizar a ordem e numero está sendo desenvolvida.

**Comment by castroli** [comment]
@fullcontent bom dia!
Temos alguma previsão de finalizar a parte de organizar e alterar o número dos itens e dos subitens?

**Comment by castroli** [comment]
@fullcontent finalizei este chamado e joguei este item para o chamado #313 , assim centralizamos todas as melhorias da plataforma de proposta naquele chamado.
