### ISSUE TITLE
Erro - Acesso Cliente

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#282]
@fullcontent bom dia!
Os usuários "cliente" não estão conseguindo acessar o sistema, segue tela de erro.

http://sistemacelic.com/cliente/home
![image](https://user-images.githubusercontent.com/60766925/187911818-f3e72a4a-67f9-45ce-9a5e-65295fb4bdef.png)

**Comment by fullcontent** [comment]
@castroli Resolvido!

Favor inserir as permissões para o usuário ao criar.
Agora será exibido pagina de "Sem Permissão" ao dar erro.
