### ISSUE TITLE
Melhoria - Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#284]
@fullcontent 
Seria possivel editar o campo "RELATÓRIO DE FATURAMENTO:" após gerar um relatório de fatuamento?

![image](https://user-images.githubusercontent.com/60766925/188206134-360a6c92-2b62-470c-9453-e7d43e787d87.png)

**Comment by castroli** [comment]
@fullcontent , testei e deu boa, apenas um ajuste, ao imprimir está aparecendo o botão "Editar", peço fazer que fique oculto ao imprimir.

![image](https://user-images.githubusercontent.com/60766925/200653051-c75707d0-ca60-49bb-8889-9f78a37b200e.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.
