### ISSUE TITLE
Erro Histórico

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#286]
@fullcontent 
Peço verificar, quando clicamos em "ver todo o histórico" deste serviço da tela de erro.

Link do serviço
http://sistemacelic.com/admin/servicos/6383

![image](https://user-images.githubusercontent.com/60766925/192803925-33ecb67a-e55a-4c6e-ab63-98de8ac4bcb6.png)
http://sistemacelic.com/admin/servico/6383/interacoes

**Comment by fullcontent** [comment]
@castroli 

Resolvido.
