### ISSUE TITLE
ERRO - Detalhes da unidade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#287]
@fullcontent 
Notei que na tela de "detalhes da unidades" esta aparecendo o texto "Detalhes da unidade test", peço corrigir para "Detalhes da unidade".
![image](https://user-images.githubusercontent.com/60766925/195892891-586a3965-7944-48ed-b692-e0d2038b5c51.png)

**Comment by fullcontent** [comment]
@castroli 

Feito!
