### ISSUE TITLE
Erro - Interações

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#288]
@fullcontent bom dia!

O sistema esta apresentando erro no momento de enviar uma interação, porém, se a pagina for atualizada, mesmo com a tela de erro, a intereção esta sendo postada.

![image](https://user-images.githubusercontent.com/60766925/197194540-7255d956-7532-4bdb-bbc4-6c4702497f82.png)
![image](https://user-images.githubusercontent.com/60766925/197194564-affa4ae6-72e5-477d-9030-521dbbe2db8e.png)
![image](https://user-images.githubusercontent.com/60766925/197195359-3d457e7f-7dd2-4a1b-804d-3fdc90b3771e.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.

Erro de configuração de email no servidor, causado por termos dois dominios .net .com

**Comment by castroli** [comment]
@fullcontent 
O erro voltou, segue tela.

![image](https://user-images.githubusercontent.com/60766925/202340357-00b3aa1d-7ede-4dc8-9e09-d8d370f8e21c.png)

**Comment by castroli** [comment]
@fullcontent 
Outro erro que notei (tbm ja ocorreu no passado) é que quando colocamos o @ em na pendencia ou no histórico, automaticamente vai para interação, segue tela abaixo como modelo.

![image](https://user-images.githubusercontent.com/60766925/202344854-6b4a2b46-5e86-4970-a0eb-db92c78e8f4d.png)

**Comment by castroli** [comment]
@fullcontent 
Fiz o teste e ainda apresenta erro, segue tela.
http://sistemacelic.com/admin/salvarInteracao
![image](https://user-images.githubusercontent.com/60766925/203843871-3b14855f-fb20-457d-9dd1-74dbed7be0aa.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido... 
O servidor está interpretando que os envios feitos automaticamente pelo sistema são Spans. Por isso foi bloqueado o email que tinha sido criado para responder automaticamente. Criei um novo email para esse fim, por hora vamos aguardar pra ver se bloqueia novamente. 


Aqui foi testado e está funcional. Peço que teste novamente por gentileza.

**Comment by castroli** [comment]
@fullcontent , o mesmo erro voltou, peço corrigir por favor.
Notei que este erro ja aconteceu diversas vezes, vc informou que é por conta de um conflito do servidor se não me engano, oq poderiamos fazer para isso não ocorrer mais? 
![image](https://user-images.githubusercontent.com/60766925/207963329-1fc228bc-9779-4ff9-8a8c-05e2101d6fc4.png)

**Comment by fullcontent** [comment]
@castroli 

De acordo com o servidor Hostinger, devido ao elevado numero de emails enviados nas notificações e lembretes, o servidor do Celic caiu em uma lista negra por conta de alguns recebimentos terem sido marcados como SPAM.

Fiz alguns testes recomendados pelo HOSTINGER e depois de um ou dois envios o email já é bloqueado de novo.

A solução que encontrei foi reativarmos o servidor antigo LOCAWEB somente para envio de emails. Já está configurado e testado. Por hora vamos aguardar alguns dias para vermos se irá cair novamente em alguma lista negra. Caso isso aconteça teremos que mudar a estratégia de envio, eliminando algumas interações.

**Comment by castroli** [comment]
Ok Bruno, só uma dúvida, teria como gerar uma lista dos emails que estão recebendo estes emails de notificações e lembretes? A princípio era apenas para nosso time aqui da Castro receber.
