### ISSUE TITLE
Melhoria - Dashboard

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#289]
@fullcontent 
Peço incluir na nossa dashboard mais uma campo de serviços em andamento, mas agora mostrando aqueles serviços que seu usuário esta como Co-Responsável.

![image](https://user-images.githubusercontent.com/60766925/199120688-1f4a15a6-9e88-477b-ab3c-125e83df8bbe.png)

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar por gentileza!
