### ISSUE TITLE
OPÇÃO DE ESCOLHER EMPRESA

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#290]
@fullcontent , 
Pensando em redução de impostos, abrimos um novo CNPJ (vamos manter os dois ativos), neste caso precisamos realizar algumas alterações nas plataformas citadas abaixo para fazerem constar a opção de escolher qual das duas empresas irão constar os dados:

- [x] Proposta:
![image](https://user-images.githubusercontent.com/60766925/199842639-d7b382d8-8550-4c41-981f-3678a4613c8f.png)
![image](https://user-images.githubusercontent.com/60766925/199842685-19cdf502-db49-4b2c-9f12-b4a8c14a8d63.png)

- [ ] Reembolso:
![image](https://user-images.githubusercontent.com/60766925/199842785-006a4771-83af-4522-aa63-8b9d4a838d6c.png)
![image](https://user-images.githubusercontent.com/60766925/199842888-3d4f6ad8-2653-411a-9ba3-54fc4351ae6c.png)
- [ ] Faturamento:
![image](https://user-images.githubusercontent.com/60766925/199843058-4b047cdf-0ec7-45b0-bf28-72d3551c2288.png)

**DADOS  DA NOVA EMPRESA:**
Castro Licenciamentos - Consultoria e Legalização Imobiliária
CNPJ: 48.132.048/0001-80
Endereço: Rua 901, nº 400, Sala 405 – Centro | Edifício Cataluña
CEP 88.330-725 – Balneário Camboriú/SC

**DADOS BANCÁRIOS:**
Chave PIX: CNPJ 48.132.048/0001-80
Banco Itaú Unibanco S.A (341)
Agência: 8490 - Conta Corrente: 0099207-3

**Comment by castroli** [comment]
@fullcontent Boa tarde!
Precisamos implementar a opção de escolher a empresa que esta solicitando o Reembolso ou faturamento com urgência, pois nosso cliente não esta mais aceitando da forma que está. Peço seu apoio urgentemente, por favor.

**Comment by fullcontent** [comment]
- [ ] Inserir banco de dados com os dados da Castro
- [ ] Criar API para buscar os dados via ajax
- [ ] Inserir as informações no Relatório de Faturamento
- [ ] Inserir as informações na Proposta
- [ ] Inserir as informações no Relatorio de Reembolso

**Comment by fullcontent** [comment]
@castroli 

Foi inserido um botao para alterar os dados da empresa na listagem 

![image](https://user-images.githubusercontent.com/6120413/227957127-ea8272ab-a1bb-48d8-9140-017f50204c83.png)
![image](https://user-images.githubusercontent.com/6120413/227957289-81dc73cc-4e33-4115-871a-41d66524fc9d.png)

**Comment by fullcontent** [comment]
@castroli 

Finalizado

**Comment by castroli** [comment]
@fullcontent 
Vi que encerrou este chamado porém, faltou a opção de escolher a empresa nas propostas, tem alguma previsão de finalizar?
