### ISSUE TITLE
Melhoria - Campo Taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#291]
@fullcontent 

- [x] No campo de taxas devemos incluir um novo campo **Responsável pelo pagamento**.
- Este campo deverá ser entre os campos "Valor" e "Reembolso" 
- Ter as opções "Castro" ou "Cliente". 
Possuir a seguinte regra: Se a opção do campo Responsável pelo pagamento for "**Castro**", no campo "Reembolso" (campo ja existente) deverá permanecer ativo para escolhermos entre a opção "sim" ou "não", porém se for optado por "**cliente**", o campo "Reembolso" deverá ### auomaticamente apresentar a opçãpo "Não" (tornar campo fechado, sem opção de alterar para sim).

- [x] Incluir este novo campo no relatório de taxas:
![image](https://user-images.githubusercontent.com/60766925/199993319-c9bfcfcc-c797-456a-8d7b-46f92c141b6d.png)

![image](https://user-images.githubusercontent.com/60766925/199988707-02ece1e1-5ed1-419d-9d6e-8817f27e2859.png)

- [x] Na tela de detalhes do serviço, no quadro de taxas substu=ituir a coluna "O.S" por "data do pagamento"

![image](https://user-images.githubusercontent.com/60766925/199998616-ad152207-a966-4762-941c-49b371fd5232.png)

**Comment by fullcontent** [comment]
@castroli 

Feito... Peço reabrir o chamado caso tenha qualquer problema relacionado a isso.
