### ISSUE TITLE
Melhoria - Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#292]
@fullcontent bom dia!
Peço incluir na tela "Selecione os serviços que deseja incluir no faturamento" uma coluna com o nome do departamento. Apenas nesta tela, na próxima e demais não precisa.
No chamado #285 vc fez algo parecido, porém, lá foi na plataforma de reembolso, mas a idéia é a mesma.

![image](https://user-images.githubusercontent.com/60766925/200840055-f5f29ce6-9d2c-47be-a93b-81ee8e20f779.png)

**Comment by fullcontent** [comment]
@castroli 

Feito.. Peço verificar por gentileza.
