### ISSUE TITLE
Melhoria - Proposta

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#294]
@fullcontent 

Atualmente ao salvar uma proposta a nomenclatura esta vindo da seguinte forma:
Exemplo: Proposta - Mercado Livre - 1631.pdf_

- [x] Peço remover o _ (underline) que vem após o PDF, pois devido a isso o arquivo não é reconhecido como um arquivo em PDF;

- [x] Peço seguir o seguinte padrão de nomenclaruta:
Proposta 1631 - Nome da empresa - Código da unidade Nome da Unidade
Proposta 1631 - Mercado Livre - 0053 Ebazar - São José

**Comment by fullcontent** [comment]
@castroli 

Feito.

Peço testar por gentileza!
