### ISSUE TITLE
Erro - Propostas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#295]
@fullcontent 
Quando aprovo uma proposta aparece o mensagem se desejo criar as demandas, ao clicar em ok ele aprova a proposta porém não cria as demandas, peço verificar. Fiz o teste na proposta 1636.

http://sistemacelic.com/admin/proposta

**Comment by castroli** [comment]
@fullcontent 
Porem tentei criar manualmente este serviços para esta unidade e deu uma tela de erro, imagino que uma coisa tem ligação com outra, segue tela.

![image](https://user-images.githubusercontent.com/60766925/201442613-272f0815-2d75-45d5-9768-c143bfd5161e.png)

**Comment by castroli** [comment]
@fullcontent 
Tentei criar estes serviços de forma manual e esta dando o mesmo erro, peço verificar, por favor.

**Comment by fullcontent** [comment]
@castroli 

Fiz a mudança da nomenclatura das OS da unidade para ficar no padrão que estamos trabalhando. Com isso o problema ficou resolvido.

Qualquer problema é só reabrir o chamado.
