### ISSUE TITLE
Melhoria - Relatórios

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#296]
@fullcontent 
Atualmente nos relatórios citados abaixo, o campo "Cidade/UF" estão na mesma na mesma coluna, peço separar cidade em uma coluna e UF em outra coluna, por favor.

- [x] Relatório de Serviços
- [x] Relatório de Taxas
- [x] Relatório Pendências

**Comment by fullcontent** [comment]
@castroli 


Feito, peço testar.
