### ISSUE TITLE
Melhoria - Relatório de Pendências 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#297]
@fullcontent 
Abaixo envio várias solicitações a implantar no relatório de Pendências:

**1. CORREÇÕES/ALTERAÇÕES:**

- [x] **Coluna Responsabilidade:**
Corrigir/alterar algumas nomenclaturas, são elas:
De "usuario" p/ "Castro"
De "op" p/ "Órgão"
De "cliente" p/ "Cliente"

- [x] **Coluna "Status"**:
Corrigir/alterar algumas nomenclaturas, são elas:
De “pendente” para “Pendente” (P maiusculo)

2. **RELATÓRIOS:**
Peço incluir as seguintes colunas no relatório de Pendências:

- [x] **Inserir nova coluna com o campo “Data criação pendência”**:
Incluir novo campo no relatório de pendências constando a data que foi criada a pendência.

- [x] **Inserir nova coluna com o campo “Etapa do processo”**:
Inserir no relatório de pendências uma coluna com a “Etapa do processo” (citada no chamado XXXXX).

- [x] **Inserir nova coluna com o campo “Tipo”**:
Inserir no relatório de pendências uma coluna com o campo “Tipo”. Esta coluna é aquela que temos dentro de cada serviço/O.S.

- [x] **Inserir nova coluna com o campo “Status unidade” que consta na tela de detalhes da unidade:**
Inserir no relatório de pendências uma coluna com o campo “Status unidade”.

- [x] **Inserir nova coluna com o campo “Data inauguração” que consta na tela de detalhes da unidade:**
Inserir no relatório de pendências uma coluna com o campo “Data inauguração” (citada no chamado XXXXX)

- [x] **Inserir nova coluna com o campo “Solicitante” que consta na tela de detalhes do serviço:**

Inserir no relatório de pendências uma coluna com o campo “Solicitante”.

**3. OPÇÕES PARA GERAR RELATÓRIO:**
- [x]  **Ao gerar o relatório ter a opção de gerar apenas das pendências com o compo "Status" igual a “pendente”.**

- [x]  **Ao gerar o relatório ter a opção de gerar apenas das pendências de uma ou mais empresas específicas.**

**Comment by castroli** [comment]
@fullcontent no item 2 deste chamado inclui mais pedido de inclusão de coluna no relatório (solicitante).

**Comment by castroli** [comment]
4. ORDEM DAS COLUNAS DO RELATÓRIO:

 - [ ] Peço organizar as colunas do relatório de serviço na seguinte ordem:
 Empresa
Serviço
Código
Unidade
CNPJ
Cidade
UF
Status da Unidade
Data Inauguração
OS
Tipo
Solicitante
Responsável
Co-responsável
Etapa do Processo
Pendência
Responsabilidade
Data Criação
Vencimento _(mudar para "Data Limite")_
Status

**Comment by fullcontent** [comment]
@castroli 

Feito os ajustes, peço testar por gentileza!
