### ISSUE TITLE
Melhoria - Relatório de Serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#298]
- [x] **Inserir nova coluna com o campo “Data inauguração” que consta na tela de detalhes da unidade:**
Inserir no relatório de serviços nova coluna com o campo “Data inauguração” (citada no chamado #299).

**Comment by fullcontent** [comment]
@castroli 

Feito no chamado #300

**Comment by castroli** [comment]
@fullcontent 
Ao gerar o relatório esta dando um erro, pelo que notei na coluna "Cidade/UF" está com o titulo na coluna P, porém os dados destas estão na coluna "Q" (CEP), no caso, consequentemente apartir desta coluna, todas as demais estão erradas.

![image](https://user-images.githubusercontent.com/60766925/202554790-86bd2bc1-0014-4ffd-802f-b5722088f85d.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido

**Comment by castroli** [comment]
@fullcontent 
Tentei gerar o relatório de serviços e esta dando erro, segue tela.

![image](https://user-images.githubusercontent.com/60766925/202802673-91afd992-a0c9-41dd-89da-c85650923483.png)
