### ISSUE TITLE
Melhoria - Dados da Unidade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#300]
@fullcontent 
Peço realizar as seguintes melhorias:

- [x] No campo “Status” incluir nova opção como “Inauguração”: 
No campo “Status” que fica na tela de Detalhes da Unidade incluir nova opção como “Inauguração”.
Obs. Fazer constar este campo no relatório de Pendencias e no relatório de serviços.
![image](https://user-images.githubusercontent.com/60766925/201771186-74874b83-e64f-43c5-bc3a-d10b6aa030c4.png)

- [x] Incluir novo campo “Data inauguração”: 
Na tela Detalhes da Unidade incluir novo campo (ao lado do campo status) com o título "Data inauguração".
Obs. Fazer constar este campo no relatório de Pendencias e no relatório de serviços.
![image](https://user-images.githubusercontent.com/60766925/201771209-ef117737-7191-4ee7-8c3f-5cb31e7b9c0c.png)

**Comment by fullcontent** [comment]
@castroli 

Feito. Peço testar por gentileza!

**Comment by castroli** [comment]
@fullcontent 
Fiz um teste e fiquei com uma dúvida, notei que se eu não preencher o novo campo "Data inauguração" da a tela de erro citada abaixo, seria por alguma regra? pq nem sempre teremos esta data, o ideal seria deixar um campo não obrigatório.

![image](https://user-images.githubusercontent.com/60766925/202286575-931ee68e-8e06-4dad-8e7d-647f091a81b5.png)

**Comment by fullcontent** [comment]
@castroli 

Fiz um ajuste no codigo pra não necessitar preencher o campo.
