### ISSUE TITLE
Erro - Relatório Taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#302]
@fullcontent 
O mesmo erro que citei ontem no chamado #298 agora ocorreu no relatório de taxas, ao gerar o relatório está dando um erro, pelo que notei na coluna "Cidade" está com o titulo na coluna G, porém os dados destas estão na coluna "H" (UF), no caso, consequentemente apartir desta coluna, todas as demais estão erradas.

![image](https://user-images.githubusercontent.com/60766925/202802986-650c086a-259f-4d0e-b2ae-e0f6395fffb6.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!
