### ISSUE TITLE
Erro - Relatório de Serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#303]
@fullcontent 
Tentei gerar o relatório de serviços e esta dando erro, segue tela.

![image](https://user-images.githubusercontent.com/60766925/202802673-91afd992-a0c9-41dd-89da-c85650923483.png)

_Originally posted by @castroli in https://github.com/fullcontent/sistemacelic/issues/298#issuecomment-1320523610_

**Comment by fullcontent** [comment]
@castroli 

Corrigido!

**Comment by castroli** [comment]
@fullcontent 
O erro retornou, peço verificar, precisamos gerar este relatório e o de pendencias para amanha de mãnha.
![image](https://user-images.githubusercontent.com/60766925/204367638-feef4629-1b09-4de8-bf23-50fb4e548022.png)

**Comment by fullcontent** [comment]
@castroli 

Resolvido/
