### ISSUE TITLE
Melhoria - Relatório de serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#305]
@fullcontent 
preciso incluir uma nova coluna (no fim) no relatório com o titulo "Vinculada" e quando for uma pendência vinculada preencher com o numero da OS que esta vinculada. 
Por exemplo, na tela abaixo a pendência é da O.S EP0392 é vinculada com o serviços de O.S nº EP0389, neste caso, precisamos que este número conste no relatório.

![image](https://user-images.githubusercontent.com/60766925/203171634-654965c1-6531-4998-9364-47bdd845d4d6.png)

**Comment by fullcontent** [comment]
@castroli 

Esse pedido é para qual dos relatórios?

- [ ] Relatório de Faturamento
- [ ] Relatório de Reembolso
- [ ] Relatorio completo de serviços

**Comment by fullcontent** [comment]
@castroli 

Feito. Peço verificar por gentileza.

**Comment by castroli** [comment]
@fullcontent 
Realizei o teste e não apareceu a nova coluna, peço verificar.

![image](https://user-images.githubusercontent.com/60766925/204005299-cc3eded1-d1a8-416e-9b8c-f8418cba332a.png)

**Comment by fullcontent** [comment]
@castroli 

Tinha inserido essa função somente no relatório de serviços. Agora está ok.
