### ISSUE TITLE
Correção de nomenclatura

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#306]
No campo Tipo corrigir o nome 
De **Projetos/Licenças não renováveis** para **Licenças não renováveis**.

![image](https://user-images.githubusercontent.com/60766925/203409418-00492544-9dbb-4f2d-93b7-e436f50c9f1d.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido!

**Comment by castroli** [comment]
@fullcontent 

Notei que a nomenclatura está errada também na tela de "Detalhes da unidade", peço ajustar também, por favor.
![image](https://user-images.githubusercontent.com/60766925/203844464-795ab0af-22fb-4e04-9f25-337389f2de77.png)
