### ISSUE TITLE
Erro - Relatório Pendências com filtro

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#307]
@fullcontent 
Notamos que o relatório de pendências com filtro não esta completo, exemplo, filtrando empresa "Pague Menos" e status "pendente", esta gerando um relatório com 461 linhas, o correto seria 860 linhas, imagino que para aas demais empresas tbm não está completo, peço verificar e corrigir, por favor.

![image](https://user-images.githubusercontent.com/60766925/204368583-39134d72-d48f-41c7-9bdc-75506123d495.png)

![image](https://user-images.githubusercontent.com/60766925/204369251-4d6ad8d4-c109-4cd3-b4e3-8763852c8696.png)

![image](https://user-images.githubusercontent.com/60766925/204369220-86afcb40-c174-4d43-9628-addf3ac0c81d.png)

**Comment by fullcontent** [comment]
@castroli 

Realizado testes aqui e a soma das pendências dessa empresa segue no mesmo numero (461). 

Pode anexar aqui por gentileza a tela que mostra essas 860 linhas para eu comparar com o resultado?

**Comment by castroli** [comment]
@fullcontent 
Geramos novo relatório e ainda não esta listando todas as pendencias existentes, peço verificar.

**Comment by fullcontent** [comment]
@castroli 

Descobri que o erro estava se dando por uma versão de um módulo diferente no servidor. Já foi corrigido e atualizado para a nova versão. Acredito que agora esteja tudo ok.
