### ISSUE TITLE
Erro - Interações

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#308]
@fullcontent 
Estamos com erro nas interações, elas estão sendo postadas, porém no campo "interação" não estão aparecendo, é possivel visualizar apenas no campo "histórico", peço corrigir, por favor.

![image](https://user-images.githubusercontent.com/60766925/205134970-38bf13cc-dd1d-4e0f-b712-d4dcf5992f48.png)
![image](https://user-images.githubusercontent.com/60766925/205134983-a387f623-7d52-481a-a84d-4abe5db23535.png)

**Comment by castroli** [comment]
@fullcontent uma informação extram notamos que este erro é apenas para esta unidade, as demais estão funcionando normalmente.

**Comment by castroli** [comment]
@fullcontent 
Mais uma informação, imagino que o problema na interação é apenas no serviço 7076, pois acabei de testar em outro serviço desta mesma unidade e deu certo. 
![image](https://user-images.githubusercontent.com/60766925/205137341-8d72c7ce-1ab3-4c59-a9dd-3396fc28d06a.png)

**Comment by fullcontent** [comment]
@castroli 

Feito uma atualização na listagem que traz as interações. Vamos experimentar dessa forma. Testado aqui e funcional. Peço testar por gentileza.
