### ISSUE TITLE
Erro - Taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#309]
@fullcontent 
Notamos que não estemos conseguindo mudar o campo "Resp. Pgto", por exemplo, se na criação foi incluido Castro, depois não esta sendo possivel mudar para Cliente, e assim ao contrário tbm, peço verificar, por favor.

![image](https://user-images.githubusercontent.com/60766925/206573605-15017b99-6e08-4742-b6fb-5ff2a6c0ba91.png)

**Comment by fullcontent** [comment]
@castroli Feito!
