### ISSUE TITLE
Correção - Projetos e Laudos

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#310]

**Comment by castroli** [comment]
@fullcontent 
Ao criar um serviço com o tipo "Projetos e Laudos" o mesmo não esta aparecendo na tela de "Detalhes da unidade", no caso o quadro "Projetos e Laudos" não está visivel, peço ajustar.

**Comment by fullcontent** [comment]
@castroli 

Feito! Peço testar!
