### ISSUE TITLE
ERRO DOWNLOAD REEMBOLSO FORMATO ZIP

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#312]
Bruno, bom dia!

Nao estou conseguindo fazer o download do formato zip, do reembolso da empresa Espaçolaser.
Peço verificar com urgencia.

![image](https://user-images.githubusercontent.com/60766925/211335352-7fd269ec-12a1-4adb-b0da-2b545de58d02.png)

![image](https://user-images.githubusercontent.com/60766925/211335160-9e4bba53-5e11-490e-b0fd-bae6bf34bc16.png)

**Comment by fullcontent** [comment]
@castroli 

Verificando no servidor, a pasta do reembolso não foi criada.
Peço que crie novamente o relatório por gentileza para fazermos um teste.

**Comment by fullcontent** [comment]
@castroli 

Encontrado o erro. Foi causado pelo nome da unidade conter caracteres especiais (ç) e isso não gerava o arquivo zip no servidor. Problema resolvido. Peço testar por gentileza.
