### ISSUE TITLE
Propostas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#314]
@fullcontent, boa tarde!
Precisamos tbm fazer algo (urgente) para melhorar o tempo de resposta desta plataforma, esta muito lento, demora aproximadamente 1 min pra mais para abrir.

**Comment by fullcontent** [comment]
@castroli 

Corrigido paliativamente. A coluna "FATURAMENTO" está demandando bastante uso do servidor ao momento de abrir. 
Vou implementar uma nova lógica na listagem para acelerar o processo, assim que pronto implemento novamente a coluna.

**Comment by fullcontent** [comment]
@castroli 

Implementado nova lógica. 

Novo tempo de resposta para a página é 8 segundos aqui no meu notebook. 

Peço testar por gentileza.

**Comment by castroli** [comment]
Ficou bemm melhorrrr. Obrigado Bruno.
