### ISSUE TITLE
Problema com aprovação da proposta e cadastro serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#315]
Aprovamos a proposta nº 1836 e só foi cadastrado no sistema os 6 primeiros serviços, os demais não foram cadastrados.
Link da unidade: http://sistemacelic.com/admin/unidades/1980
![image](https://user-images.githubusercontent.com/60766925/216076106-a1a629f4-b44d-4629-b18e-8f2dbf6a3333.png)
 Link da proposta: file:///C:/Users/diego/Desktop/Proposta%201836%20-%20Pague%20Menos%20%20IUT02-Platina-MG.pdf

**Comment by fullcontent** [comment]
@castroli 

Efetuado correção. O erro foi causado devido a atualização na tabela de LPU's. Alguns serviços relacionados na proposta estavam vinculados ao serviço da tabela LPU e por ele haver sido atualizado ocorreu o erro. 

Foi corrigido restaurando o item 154 da tabela de LPU. 

Se o erro persistir é só reabrir o chamado.
