### ISSUE TITLE
Melhoria - Filtros Relatório de Serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#321]
@fullcontent bom dia!
Na tela "Relatórios" no CELIC, peço criar uma espécie de filtros para gerar o relatório de serviços apenas com as informações que iremos utilizar. No caso manter a opção de gerar o relatório completo (com todos os dados do CELIC), mas tbm criar uma opção com filtros (igual fez para o relatório de pêndencias), abaixo envio uma lista e imagem com as colunas que gostariamos de ter os filtros.

**Relatório de Serviços:**
--
Nome Unidade
CNPJ
Status
Cidade
UF
Tipo
Situação
Responsável
Co-Responsável
Nome Serviço
Solicitante
Departamento
Proposta
Emissão Licença
Validade Licença
Finalizado
Criação

![image](https://user-images.githubusercontent.com/60766925/217793258-f505a066-1422-44b1-9335-40a1fd4d0f4b.png)

**Comment by fullcontent** [comment]
@castroli 

Feito.
