### ISSUE TITLE
Erro - Interação

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#330]
@fullcontent 
Voltamos a ter o erro citado no chamado #127, ocorre que se colocarmos o **@** no campo de pendência, observação (do serviço)  ou histórico automaticamente ele vai para a interação, peço corrigir. 
![image](https://user-images.githubusercontent.com/60766925/220125111-c94c531a-3e82-4342-81e5-e06d4007b057.png)

**Comment by castroli** [comment]
@fullcontent 
Erro permanece, peço ajustar.

![image](https://user-images.githubusercontent.com/60766925/221046451-88c4f1fa-30f9-4519-8816-a422b9e3da29.png)

**Comment by fullcontent** [comment]
@castroli 

Feito uma correção, pode checar por gentileza?
