### ISSUE TITLE
Melhoria - Relatório geral de serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#332]
@fullcontent 
Notei que mudou a tela de "Relatório geral de serviços", seria possivel deixar um link para que eu possa entrar no serviço desejado? 

http://sistemacelic.com/admin/servicos
![image](https://user-images.githubusercontent.com/60766925/221047451-592a31ec-4deb-4233-b750-68a8ab7f8be1.png)

**Comment by fullcontent** [comment]
@castroli 

Inserido link. 

Aproveitando, vou descrever aqui as novas funcionalidades dessa pagina.

Pensando na necessidade de montar relatórios personalizados, criei essa nova pagina para que vocês tenham autonomia na geração de relatórios personalizados.


Vocês podem organizar as colunas que serão mostradas clicando no botao EDITAR COLUNAS e clicando nas colunas que não desejam mostrar. Colunas invisíveis ficam em vermelho.

As colunas podem ser reordenadas. Pra isso é só clicar no titulo da coluna e arrastar pra posição desejada.
Há a possibilidade de criar filtros personalizados, podendo selecionar por qualquer campo. Caso queiram fazer isso antes de passar pro excel. Se já tem mais agilidade no excel, pode exportar o arquivo completo e fazer os filtros por lá também.


O relatório personalizado pode ser exportado em EXCEL, CSV e PDF.


Qualquer dúvida é só reabrir o chamado.

**Comment by castroli** [comment]
@fullcontent Ficou muiiito top este formato, muito prático mesmo, show de bola. 
Apenas no realizando os testes identifiquei alguns erros, seguem:

**- [ ] Erro no link:** Ao clicar sobre a linha do serviço esta constando a seguinte tela de erro:
![image](https://user-images.githubusercontent.com/60766925/221857430-60f6c6e7-0e3d-4026-971e-fe3a63ccc451.png)


**- [ ] Erro no filtro:** Se eu seleciono a coluna 1 "Serviço ID”, a lista do filtro “Volue” vai listar a coluna 2 “Razão Social” e assim por diante, sempre na lista está aparecendo a coluna seguinte, peço ajustar.

![image](https://user-images.githubusercontent.com/60766925/221852308-8d518227-4e51-4a95-b35a-833815ed4a3a.png)

- [ ] **Msg de Erro:** Esta aparecendo algumas msgs de erro durante o uso, peço verificar.

![image](https://user-images.githubusercontent.com/60766925/221852445-0c3a11f0-530c-4500-96f1-385dcf98e693.png)
"DataTables warning: table id=example - Requested unknown parameter '37' for row 470, column 37. For more information about this error, please see http://datatables.net/tn/4"

![image](https://user-images.githubusercontent.com/60766925/221853378-53bf83a1-8e0b-4f34-b41e-3c05de505ad2.png)
"DataTables warning: table id=example - Requested unknown parameter '37' for row 3232, column 37. For more information about this error, please see http://datatables.net/tn/4"

**- [ ] Traduzir palavras:** Os textos estão em inglês, peço traduzir para português, por favor.
- Custom Search Builder para Relatório Personalizado
- Volue para Lista
- Demais textos apenas traduzir
![image](https://user-images.githubusercontent.com/60766925/221854370-5497e1cc-c0db-4389-8e86-1617a5ded4c9.png)

**Comment by fullcontent** [comment]
@castroli 

Erros de listagem corrigidos.

**Comment by fullcontent** [comment]
@castroli 

Corrigido listagem e tradução de textos.

**Comment by fullcontent** [comment]
@castroli 

Ajustado exibição da listagem para os usuarios CLIENTE respeitando o acesso de cada um.

**Comment by castroli** [comment]
@fullcontent 
Correções:

- [ ] Fiz o teste com um usuário cliente e não esta aparecendo o relatório, peço verificar.
![image](https://user-images.githubusercontent.com/60766925/223747077-9d89f184-6685-4c8b-88db-550d8dca535e.png)

- [ ] Fiz o teste com os demais usuários "admin" e ao clicar no "Listagem geral de serviços" esta aparecendo tela de erro, peço verificar.
![Imagem do WhatsApp de 2023-03-08 à(s) 11 55 00](https://user-images.githubusercontent.com/60766925/223747395-1122ee7b-403e-475f-8b79-f7539ad4f1e0.jpg)

**Comment by fullcontent** [comment]
@castroli 

A listagem estava aparecendo na listagem geral de serviços. Alterei o link do menu para exibir a mesma tela se clicar em Relatórios.

**Comment by castroli** [comment]
@fullcontent 
Refiz os testes e os dois erros citados anteriormente permanecem, peço verificar.

**Comment by castroli** [comment]
@fullcontent 
Vou encerrar este chamado pois estas duas ultimas pendências estão listadas no chamado 358.
