### ISSUE TITLE
Melhoria - Aba de Serviço

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#334]
@fullcontent 
Nesta aba lateral "serviço" atualmente aparece apenas os serviço que o usuário esta cadastrado como "Responsável", peço fazer constar tbm se o usuário estiver cadastrado como "co-responsável".
![image](https://user-images.githubusercontent.com/60766925/221987043-36176ea1-4a25-4153-8858-cf515414e0b6.png)

**Comment by fullcontent** [comment]
@castroli 

Alterado!
