### ISSUE TITLE
Erro Histórico

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#335]
@fullcontent 

Coloquei um histórico e não esta aparecendo no topo da pagina (print 01), se eu entrar no histórico completo, dae sim eu consegigo visualizar (print 02). Peço ajustar.

![image](https://user-images.githubusercontent.com/60766925/222273820-7a4c67eb-0269-49d5-93b6-017dc4511ee7.png)

![image](https://user-images.githubusercontent.com/60766925/222273953-ba99bf01-8a81-4a25-8a2b-fb1bfdbc67fc.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.
