### ISSUE TITLE
Erro - Interação

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#336]
@fullcontent 

- [ ] Estou tentando enviar uma interação porém não esta aparecendo no campo de interação, está indo para compo de histórico, peço ajustar. Detalhe que no campo histórico da para visualaizar apenas se clicar em "visualizar todo o histórico".

![image](https://user-images.githubusercontent.com/60766925/223790251-c8b24b82-1b64-4d4e-8b99-1ecabe902f8a.png)

![image](https://user-images.githubusercontent.com/60766925/223790836-cb70f6ec-444a-4252-a982-58c35990bd16.png)

- [ ]  Aproveitando, nesta tela de visualizar todo o histórico o nome da tela esta como 'Interações da O.S. XXXXX", peço alterar para "Histórico da O.S. xxxx" 
![image](https://user-images.githubusercontent.com/60766925/223790939-45a5dd75-b1b1-4f90-ae40-3f55027bf51d.png)

**Comment by fullcontent** [comment]
@castroli 

Feito um ajuste na logica e aparentemente resolvido.
