### ISSUE TITLE
Melhoria - Cadastro de unidade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#337]
@fullcontent 

**- [ ] Campo "Razão Social":** Atualmente este campo preenche automático conforme consta na base da Receita Federal (vinculado ao CNPJ que incluímos). A idéia é que ele preencha automaticamente com a Razão Social da "Empresa" que escolhemos. Isso minimizaria descompassos nos textos. Digo isso pq 90% das vezes o campo a "Razão Social" da unidade é o mesmo da Razaão Social empresa. Mas é interessante deixar tbm a opção de alterar manualmente caso necessário. 
![image](https://user-images.githubusercontent.com/60766925/224118267-bcf7f38b-d3d4-49b9-8810-102014c480f4.png)

**Comment by fullcontent** [comment]
@castroli 

Ajustado. A partir de agora quando seleciona a empresa, o campo Razão social preeenche automaticamente com a Razão Social da Empresa selecionada. E quando preenche o CNPJ o campo razão social não é mais alterado.
