### ISSUE TITLE
Erro - Relatório de Taxas

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#338]
@fullcontent bom dia
Peço verificar a coluna "Resp. Pgto" que está em branco, necessário constar se o responsável pelo pagamento é Castro ou Cliente.
![image](https://user-images.githubusercontent.com/60766925/224706013-6824a408-0bd7-4109-8ebb-fddde2bb054b.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido
