### ISSUE TITLE
Área do Cliente

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#34]
- [x] Listagem dos serviços

- [x] Detalhes do serviço

- [x] Dashboard (Direcionar para os filtros)

- [x] Menu cliente (acesso a todos os filtros)

- [x] Widget Serviços (Tirar obs)

- [x] Widget Taxas (Comprovante e Boleto)

- [x] Listagem Unidades

**Comment by fullcontent** [comment]
Favor conferir as telas do cliente.
