### ISSUE TITLE
Melhoria - Dashboard

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#341]
@fullcontent 
Peço incluir a opção escolher a quantidade de linhas na dashboard, atualmente conseguimos visualizar apenas 10 pendências por tela, incluir a opção 10, 25, 50 ou 100 (identico consta em outras telas).

![image](https://user-images.githubusercontent.com/60766925/226380521-7a7750ba-5d30-494e-8b2a-9424ae9097ad.png)

**Comment by castroli** [comment]
@fullcontent veriifquei que no meu usuario e de outros esta aparecendo apenas no campo de "Todas as pendências". O campo "Pendências do dia" e "Pendências atrasadas" não está aparecendo, peço verificar.

Tela usuario Diego:
![image](https://user-images.githubusercontent.com/60766925/232921492-bdafc016-dabe-479e-9296-c14b2a08354d.png)
Tela usuario Camille:
![image](https://user-images.githubusercontent.com/60766925/232921814-f6cd0310-8e15-47c4-9761-11d27a5aff9c.png)
Tela usuario Caroline:
![image](https://user-images.githubusercontent.com/60766925/232921764-700d0971-bcc4-4f1a-9e41-fef5d481c99a.png)

**Comment by fullcontent** [comment]
@castroli 

Fiz uma alteração, favor checar novamente
