### ISSUE TITLE
Erro - Faturamento

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#342]
@fullcontent 

Ao tentar gerar um faturamento esta dando a seguinte tela de erro.
http://sistemacelic.com/admin/faturamento/step4

**Comment by fullcontent** [comment]
@castroli 

corrigido

**Comment by castroli** [comment]
@fullcontent o erro voltou, segue tela.
Lembrando que o erro é no ultimo passo da criação do faturamento, porém, ele cria o faturamento, apenas gera esta tela no lugar de mostrar o faturamento.
![image](https://user-images.githubusercontent.com/60766925/230504599-0603762c-a053-49e5-ba1c-64c0343a546a.png)

**Comment by fullcontent** [comment]
@castroli 

Corrigido.
