### ISSUE TITLE
Erro - Reembolso

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#343]
@fullcontent 
Ao tentar gerar uma pasta zip do reembolso esta apresentando o seguinte erro:

![image](https://user-images.githubusercontent.com/60766925/229889392-a1c5dc56-581b-4436-baf2-f22f1d788d87.png)

http://sistemacelic.com/admin/reembolso/4/downloadZip

**Comment by fullcontent** [comment]
@castroli 

Corrigido
