### ISSUE TITLE
Melhoria - Relatório de Pendências

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#346]
@fullcontent 
Incluir no "relatório de pendência" duas novas colunas com as seguintes informações:

- [x]  Deparamento (após a coluna Solicitante)
- [x]  Situação (situação do serviço que a pendência é vinculada)
- [x] Valor Serviço
- [x] Data e criação
- [x] Histório do serviço (incluir como ultima coluna)

**Comment by fullcontent** [comment]
@castroli 

Peço testar por gentileza.

**Comment by castroli** [comment]
@fullcontent 

Notamos que colocou a "Data de criação" da pendencia, que por sinal ja tinhamos neste relatório, precisamos que inlua a "Data de criação" do serviço, peço ajustar (remover a coluna que ficou em duplicidade e incluir "Data de criação" do serviço.

**Comment by fullcontent** [comment]
@castroli 

Corrigido
