### ISSUE TITLE
Erro - Tela "Editar unidade" Campos "Empresa" e "Data Inauguração"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#354]
@fullcontent 
Peço realizar as seguintes correções:

- [x] **Campo "Empresa"**: Sempre que entramos na de tela de "Editar unidade" este campo fica em branco, precisamos sempre incluir qual a empresa que esta unidade é vinculada, não era assim antes, peço fazer com que este campo fique fixo, e aberto para alteração como qq outro.

- [x] **Campo "Data Inauguração"**: Quando deixamos este campo em branco, sempre que entramos na de tela de "Editar unidade" este campo automaticamente muda para "NaN/NaN/NaN" e para conseguir salvar, temos que ir nele e apagar este texto (deixar em branco), peço corrigir de modo que, se não incluímos nenhuma data e permaneça em branco/vazio. 

- [x] **Campo "Data Inauguração"**: Outro problema neste mesmo campo é, se colocar uma data, por exemplo 16/06/2023, após salvar e entrar novamente na tela ele altera para 15/06/2023, se eu repetir (salvar e editar novamente) ele altera para 14/06/2023, resumindo, diminui um dia cada vez que eu entro na tela de editar unidade, peço corrigir, de modo que quando consta uma data ele seja fixo.

TELA 01:
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/c4c6d166-4dc1-40c3-8783-03d0473e6ed1)

TELA 02:
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/1179defd-9ad8-4af8-8501-f9ccf1e09ff1)

TELA 03:
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/3c916802-e458-4554-bd56-97acfd67ca8f)

TELA 04:
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/0d6fc4d3-1c03-4b11-961f-83b56b95436b)

**Comment by fullcontent** [comment]
@castroli 

Corrigido
