### ISSUE TITLE
Erro - reembolso

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#357]
@fullcontent 
Ao tentar gerar reembolso para empresa Pague Menos esta dando o erro citado abaixo, apenas para empresa Pague Menos, as demais esta funcionando corretamente.

http://sistemacelic.com/admin/reembolso/step2
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/ebd5f5ea-85da-4d2a-9231-61649af96916)

**Comment by fullcontent** [comment]
@castroli corrigido
