### ISSUE TITLE
Lembretes

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#36]
- [x] Taxa a vencer no dia e um dia antes

- [x] Pendência com data limite no dia e um dia antes 

- [x] Vencimento da licença 60 dias antes

- [ ]

**Comment by fullcontent** [comment]
- [ ] Enviar email para o usuário responsável

**Comment by fullcontent** [comment]
Notificações estão programadas para serem enviadas as 3am todos os dias.
Emails serão enviados as 2am todos os dias
