### ISSUE TITLE
Relatório de serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#363]
@fullcontent 

O relatório de serviços esta apresentando erro, ao baixar esta gerando apenas 5 serviços, peço verificar e corrigir por favor..

![image](https://github.com/fullcontent/sistemacelic/assets/60766925/2fa2e21c-58f3-4189-9af7-9601365060e8)

**Comment by fullcontent** [comment]
@castroli 

Alterado
