### ISSUE TITLE
Relaótio Geral de Serviços

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#369]
@fullcontent
Incluir neste relatório:
**- [ ] Pendências:**  Incluir nova coluna de pendência, para os casos que possuem mais de uma pendência, fazer com que elas sejam listadas no mesmo campo.
**- [ ] Responsável pela pendencia:** O nome da coluna séra "Responsável pela pendência" e irá completar com o campo "Responsabilidade" que encontra-se dentro da pendência. Para os casos que possuem mais de uma pendência, fazer com os responsáveis (responsabilidade) sejam listadas no mesmo campo.

**Comment by fullcontent** [comment]
@castroli 

Feito, peço testar por gentileza. Qualquer problema só reabrir o chamado

**Comment by castroli** [comment]
@fullcontent 
Pra mim ainda não esta aparecendo, peço verificar. 
Lembrando que o relatório que estou falando é este citado na imagem abaixo.
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/b7f1b94e-1135-4b6f-b228-8e25e76425a5)
