### ISSUE TITLE
Faturamento - Campo nº NF

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#370]
@fullcontent 
Estou fazendo o faturamento e notei que está dando um erro que nunca tivemos, conforme print abaixo (tela 01), no momento de elaborar o faturamento preencho o número das notas fiscais, porém após gerar ele completa todos os campos copiando o numero da NF preenchido nao ultimo campo (tela 02), peço verificar.
**Tela 01**
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/7f265ce0-6f9a-4c5a-9b1f-3b5a2a95f98a)
**Tela 02**
![image](https://github.com/fullcontent/sistemacelic/assets/60766925/f7e7e5cc-78e7-46ba-a290-5a55edaf53a4)

**Comment by castroli** [comment]
Segue mais duas telas do erro.

![image](https://github.com/fullcontent/sistemacelic/assets/60766925/921d5fdf-5358-4b02-80a4-1e4009166433)

![image](https://github.com/fullcontent/sistemacelic/assets/60766925/d67facad-ff51-4dde-b30b-b2fe5c663895)

**Comment by castroli** [comment]
@fullcontent 
Erro permanece.

![image](https://github.com/fullcontent/sistemacelic/assets/60766925/53c74f16-bf9e-4fdd-9b68-c1d03502d970)

![image](https://github.com/fullcontent/sistemacelic/assets/60766925/7e46bd36-08eb-4e91-a256-4c6593b86b3f)

**Comment by fullcontent** [comment]
@castroli 

Estou verificando aqui. parece que esse campo era pra vir o valor diretamente do serviço depois de salvar. 
Vou fazer um teste local aqui e ja atualizo.

**Comment by fullcontent** [comment]
@castroli 


atualizado. 

Agora os campos NF vem diretamente do serviço. Excluido a NF do faturamento.
Aguardando teste para fechar o chamado.
