### ISSUE TITLE
Corrigir dados no Banco de dados

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#39]
Limpar pendências e taxas que não tenham vinculo com Unidade, Empresa ou Serviço.

**Comment by castroli** [comment]
Informo que continua a constar as duas pendências sem vinculo com Unidade, Empresa ou Serviço, peço corrigir.

**Comment by fullcontent** [comment]
Não consegui encontrar as pendências diretamente no banco de dados... 
Pode enviar um print delas?

**Comment by fullcontent** [comment]
Encontrei os dados relacionados ao serviço 381 e foram removidos.

**Comment by castroli** [comment]
Bruno, entrei com o usuário da Aline e apareceu mais algumas pendências sem vinculo com Unidade, Empresa ou Serviço, peço corrigir, por favor.
![image](https://user-images.githubusercontent.com/60766925/76311982-db3a0400-62b0-11ea-9bdf-d9b9144e1046.png)

**Comment by fullcontent** [comment]
Corrigido.

**Comment by castroli** [comment]
Olá Bruno, boa tarde!
Com o usuário da Aline ainda aparece algumas pendências sem vinculo com Unidade, Empresa ou Serviço, peço corrigir, por favor.
![Uploading image.png…]()

**Comment by castroli** [comment]
Olá Bruno, boa tarde!
Com o usuário da Aline ainda aparece algumas pendências sem vinculo com Unidade, Empresa ou Serviço, peço corrigir, por favor.
![image](https://user-images.githubusercontent.com/60766925/78068875-95cc9c00-736f-11ea-849a-7e50f9688b68.png)

**Comment by fullcontent** [comment]
Corrigido.
