### ISSUE TITLE
Dashbord - Correção

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#41]
- [x] No usuário da Aline havia uma licença para renovar, foi iniciado o processo de renovação, mas continua aparecendo "1 licença a vencer", mas ao clicar não consta nenhuma unidade a mais.

![image](https://user-images.githubusercontent.com/60766925/74735141-d2648e00-522e-11ea-85b2-3ad87286fe7b.png)

![image](https://user-images.githubusercontent.com/60766925/74735210-f88a2e00-522e-11ea-9edb-7e5c770b2fa4.png)

- [x] Alterar a nomenclatura do dashborde de "Pendencias não resolvidas" para "Serviços em andamento".
![image](https://user-images.githubusercontent.com/60766925/74735333-3ab36f80-522f-11ea-92e4-ce8beeb45ce7.png)

**Comment by fullcontent** [comment]
Atualizado alguns detalhes. 
Pode testar com o usuario da Aline e me informar se corrigiu?

**Comment by castroli** [comment]
Problema resolvido. Agradeço.
