### ISSUE TITLE
Correção

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#45]
- [x] Quando iniciamos a renovação de uma licença a O.S antiga é arquivada, porém a mesma esta aparecendo em duplicidade na tela de "Unidades";
![image](https://user-images.githubusercontent.com/60766925/76152978-96418200-60a4-11ea-8710-a54592c23bbd.png)
 
- [x] O status da O.S que foi arquivada esta passando automaticamente de "Finalizado" para "Andamento" também, o correto é esta alteração de status ocorrer apenas da nova O.S criada. 
![image](https://user-images.githubusercontent.com/60766925/76152988-b6714100-60a4-11ea-9fb8-446c62186975.png)

- [x] O Serviço arquivado esta sendo mantido no quadro de primários, peço fazer com que não conste. Neste quadro precisamos apenas que conste apenas os serviços "Finalizados" e "Andamento".  Se necessário crie um novo campo para aparecer apenas os arquivados.
![image](https://user-images.githubusercontent.com/60766925/76153075-c3426480-60a5-11ea-8f73-c343920a170b.png)

- [x] No campo de "Pendência" quando incluo o "Responsável pela Pendência" sempre fica como Castro, mesmo colocando "Cliente" ou "Órgão Publico", ao salvar ele automaticamente salva como Castro.
![image](https://user-images.githubusercontent.com/60766925/76153709-7616c080-60ae-11ea-8131-4cf5b0b1a024.png)

**Comment by fullcontent** [comment]
Corrigido
