### ISSUE TITLE
Dashbord - Correção "quadro licenças a vencer"

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#52]
O número dentro do quadro de licenças a vencer não esta condizendo com a realizada, hoje por exemplo consta 1, porém na pratica não tem nenhum. Peço corrigir.

![image](https://user-images.githubusercontent.com/60766925/78300114-5d62c480-750d-11ea-81b1-06b18d472b79.png)

![image](https://user-images.githubusercontent.com/60766925/78300139-6784c300-750d-11ea-85de-34acdf4fce0d.png)

**Comment by fullcontent** [comment]
Corrigido

**Comment by castroli** [comment]
Bruno, continua constando uma licença a vencer, porem ao clicar não consta nenhuma.

![image](https://user-images.githubusercontent.com/60766925/78673016-e84e1100-78b7-11ea-9c91-56e8eb2163ac.png)

**Comment by fullcontent** [comment]
Corrigido a logica.
Estava buscando os serviços de Unidades Ativas e no dashboard não tinha esse filtro.
