### ISSUE TITLE
Incluir opções ao administrador

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#54]
Bruno, 
Incluir as seguintes opções aos administradores:

- [x] excluir empresa;

- [x] excluir unidades;

- [x] excluir usuários;

**Comment by fullcontent** [comment]
@castroli 

Algumas dúvidas

Quando exclui uma unidade ou uma empresa, o que faremos com os serviços que estiverem relacionados a elas?

**Comment by castroli** [comment]
@fullcontent 
A princípio vamos excluir apenas empresa/unidade que foram criadas erroneamente, estas não terão serviços atrelados.
Mas esta pergunta é bem relevante, temos que pensar uma forma, se futuramente gerar a necessidade de excluir uma empresa que tem serviços atrelados como faremos. Imagino a opção de apenas "arquivar", exemplo, se arquivarmos uma empresa, todas as unidades e serviços  relacionados serão arquivados também.

**Comment by castroli** [comment]
Bruno 
Ao tentar excluir uma empresa, esta apresentando o seguinte erro:

![image](https://user-images.githubusercontent.com/60766925/79169862-f7efbd00-7dc3-11ea-9936-2ee6c717c39f.png)

**Comment by fullcontent** [comment]
Corrigido
