### ISSUE TITLE
Controle de LPU

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#58]
- [x] Banco de dados de LPU
- [x] Inserir lista de LPU no cadastro do serviço
- [ ] Editar e inserir novas LPU's 
- [ ] Inserir menu LPU
- [ ] Importar csv Lpu

**Comment by castroli** [comment]
@fullcontent imagino que podemos fechar este chamado, creio que não será necessário vincular os serviços a uma LPU uma vez que para o mesmo cliente podemos praticar algum tipo de desconto ou acréscimo. Imagino que devemos manter a inserção dos valores manualmente.
