### ISSUE TITLE
Reembolso

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#60]
- [x] Alterar tabela Taxas no BD
- [x] Inserir informações no formulário de cadastro da taxa
- [x] Criar Reembolso
- [x] Relatorio de reembolsos

Na "navegação principal" do CELIC, dentro do Item "Financeiro" criar um subitem "Reembolso".								
Nesta pagina imaginamos um cenário para criação do reembolso com os seguintes campos:								
Empresa:	Selecionar a ou as empresas que constará no Reembolso.							
Periodo:	Selecionar o periodo desejado para emissão do Reembolso.							
O.S.:	Selecionar alguma O.S. específica (se for o caso) para incluir no pedido do reembolso.							
OBS 01:	Para gerar o relatório, não é necessário todos os campos preenchidos, fazer com que o sistema gere o Reembolso apenas com as informações informadas.							
								
Botão "Gerar Reembolso".	Este botão fará com que o sistema gere uma tela com a listagem das taxas a serem reembolsadas dentro do periodo e demais filtros selecionados.							
								
Botão "Gerar Reembolso Oficial".	Este botão estará dentro da tela citada acima e somente será clicado quando o Reembolso for realmente fechado para envio ao cliente. Este botão fará com que o sistema exporte o relatório para um arquivo Excel ou PDF.							

- [x] Inserir menu Reembolso

**Comment by fullcontent** [comment]
@castroli 

Atualizei a ultima versão do reembolso. Peço testar e ver se está funcional.
Está sendo gerado o recibo na parte final do relatório.

Ainda falta a parte do download do arquivo Zip com os boletos e comprovantes

- [ ] Download de Arquivos na parte final do relatório.

**Comment by castroli** [comment]
@fullcontent temos uma data prevista para finalizar esta etapa?
