### ISSUE TITLE
Notificações de Pendências

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#61]
Bruno,
Ao cadastrarmos uma pendência, no campo "Responsável" se optarmos por inserir o nome de algum cliente temos duas situações a corrigir:

- [x] não aparece na dashbord (do cliente) a "lista de pendências". Fazer constar;

- [x] O responsável pela Ordem de Serviço (funcionário Castro) não tem como controlar se a pendência foi sanada, pois não aparece na nossa lista de Pendencias que fica no dashbord. Fazer constar também na listagem do responsável do O.S..

![image](https://user-images.githubusercontent.com/60766925/80247350-4878dd00-8644-11ea-92aa-74df6a4544d0.png)

![image](https://user-images.githubusercontent.com/60766925/80248081-a22dd700-8645-11ea-9ccc-b8c92b52eded.png)

**Comment by fullcontent** [comment]
@castroli Foi adicionado a listagem das pendencias para o responsável pela pendencia e também no dashboard do usuario que é responsavel pelo serviço.

**Comment by castroli** [comment]
@fullcontent bom dia! Realizei o teste e para o acesso via cliente quando clica sobre a pendência (no dashboard) apresenta tela de erro (abaixo), creio que seja pq para o cliente ainda não esta aparecendo o campo de pendencias (dentro da O.S). Corrigir por favor.

![image](https://user-images.githubusercontent.com/60766925/82053205-5c3bc000-9693-11ea-8e6c-c9094de2fdda.png)

**Comment by fullcontent** [comment]
@castroli Corrigido e direcionado pra pagina do serviço quando cliente clica sobre a pendencia.
