### ISSUE TITLE
Incluir campo na O.S.

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#62]
Dentro a O.S. criar o campo "Tipo de licença" com as opções:

- **Renovável:** licenças que possui vencimento. Por ser a maioria, deixar sempre esta como opção automática, se enquadrar-se em uma das opções abaixo, inserimos manualmente.

Se a opção for "Renovável", deverá possuir os campos "Emissão da licença" e "Vencimento da Licença", tal qual como é hoje.

- **Definitiva:** Licença que possuem a data de emissão, porem, não tem vencimento.

Se a opção for "Definitiva", deverá possuir apenas o campo "Emissão da licença" (bloquear a edição do campo vencimento).

- **Não aplicada:** Quando não se aplica a licença, porem devemos manter este histórico no sistema.

Se a opção for "Não aplicada", deverá bloquear a edição dos campos "Emissão da licença" e "Vencimento da Licença".

- [ ] ocultar exibição de validade da licença se for selecionada n/a ou definitiva

**Comment by fullcontent** [comment]
Inserido os dados. Todos os serviços ficaram com esse campo como renovável.

**Comment by castroli** [comment]
Bruno, 
Realizei um teste de serviço "Não aplicada" e "Definitivo"  com as O.S nº PT0008 e PT0009, temos uma correção a ser feita. O botão que representa a licença está ficando na cor vermelha, como neste caso consideramos que a licença esta regular, os botões devem ficar na cor verde.

![image](https://user-images.githubusercontent.com/60766925/80404267-54a8a880-8897-11ea-8959-3d0f3014c422.png)
![image](https://user-images.githubusercontent.com/60766925/80404349-70ac4a00-8897-11ea-9783-b898ddd6bba9.png)

**Comment by fullcontent** [comment]
Corrigido. 
Ao efetuar o cadastro, se o campo for selecionado como Não Aplicado ou Definitivo, a data de validade será preenchida como 31/12/2059.

**Comment by fullcontent** [comment]
Vou deixar esse chamado em aberto com alguns detalhes de exibição a serem corrigidos posteriormente:

- [ ] Detalhes do serviço (se caso for definitivo ou n/a, ocultar a data de validade)
