### ISSUE TITLE
Correção hiperlink campo licenças 

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#63]
Na tela de "unidades" Campo "Licenças" temos as siglas das licenças que sinalizam quando o alvará esta vigente (verde) ou vencido (vermelho). Este campo possui um hiperlink que ao clicar ele direciona para a tela do serviço em questão, porém, como exemplo a loja 009 da empresa Adiser, o hiperlink do campo AF esta direcionando para o serviço que já está arquivado e não ao serviço que está em andamento (que é o de nosso interesse). Necessário corrigir e sempre que o sistema clonar um novo serviço para iniciarmos a renovação, o hiperlink deverá também se atualizar.

![image](https://user-images.githubusercontent.com/60766925/80249859-f6868600-8648-11ea-87e9-f73efd90e74f.png)

![image](https://user-images.githubusercontent.com/60766925/80250189-b542a600-8649-11ea-99d5-cee17f0e1606.png)

**Comment by fullcontent** [comment]
Corrigido. Na listagem das unidades aparecerá sempre o último serviço.
