### ISSUE TITLE
Correção - Tela erro

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#64]
Ao clicar na empresa Renner aparece a tela de erro.

**Comment by fullcontent** [comment]
Erro causado por nome do serviço estar em desacordo com as regras que haviamos inserido:

                                        case 'Alvará de Publicidade':
	              			$name = "AP";

	              			break;
	              			
	              			case 'Alvará Sanitário':
	              			$name = "AS";
	              			break;

	              			case 'Alvará da Polícia Civil':
	              			$name = "PC";
	              			break;

	              			case 'AVCB':
	              			$name = "CB";
	              			break;

	              			case 'Alvará de Funcionamento':
	              			$name = "AF";
	              			break;

	              			case 'Licença Ambiental':
	              			$name = "LA";
	              			break;


Foi corrigido provisoriamente inserindo um nome "n/a" para serviços que não estiverem em conformidade. O serviço em questão é o LR0016.

Futuramente vamos adequar essa lista para buscar os nomes de serviços diretamente de uma lista de LPU´s, minimizando este tipo de problema.
