### ISSUE TITLE
Correção acesso de cliente

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#66]
Bruno, 
Quando acessado com usuário de cliente a tela de unidades esta apresentando dois erros, sendo:

- [x] O quadro de "licenças" esta apresentando licenças repetidas:
![image](https://user-images.githubusercontent.com/60766925/80491662-68a4e680-8939-11ea-9cc4-bfb3703cba70.png)

- [x] Ao clicar em alguma licença (através do botão de cores) apresenta tela de erro:
![image](https://user-images.githubusercontent.com/60766925/80492058-e4069800-8939-11ea-8ac0-84db89bdc15b.png)

Obs. Estes erros constam apenas com o usuário "Cliente".
- [x] Exibir taxa
- [x] Dashboard

**Comment by fullcontent** [comment]
@castroli Foi efetuado os ajustes solicitados.
