### ISSUE TITLE
Erro vencimento licença

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#67]
Bruno,
Hoje quando tentamos lançar qualquer licença ao inserirmos a data de vencimento, depois de salvo ele muda automaticamente para 31/12/2059, peço corrigir, por favor.
 
![image](https://user-images.githubusercontent.com/60766925/80499618-998a1900-8943-11ea-951d-ece335283e09.png)

**Comment by fullcontent** [comment]
corrigido
