### ISSUE TITLE
Correções

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#68]
- [x] No Dashbord a caixa serviços em andamento esta sem vinculo (se clicar nela não apresenta a listagem dos serviços que estão em andamento e o numero que atualmente aparece não condiz com a realizada, creio que atualmente esta vinculada ao numero de pendências, o que estaria errado.
![image](https://user-images.githubusercontent.com/60766925/80533866-aa06b780-8974-11ea-83b8-3125a93f62aa.png)

- [x] No item "serviços", subitem "Em andamento" está apresentando não só os a listagem dos serviços em andamento como também dos serviços finalizados, peço corrigir.
![image](https://user-images.githubusercontent.com/60766925/80534315-69f40480-8975-11ea-9f16-d704484553dd.png)

- [x] No item "serviços", subitem "A vencer" não apresenta apenas a listagem dos serviços que estão a 60 dias para o vencimento, inclusive esta constando os serviços que não tem vencimento, peço corrigir.
![image](https://user-images.githubusercontent.com/60766925/80534690-03bbb180-8976-11ea-8799-b1a526ddaf78.png)

- [x] No item "serviços", subitem "Finalizados" não apresenta nenhuma listagem, o correto é apresentar todos os serviços com a situação finalizado, peço corrigir.
![image](https://user-images.githubusercontent.com/60766925/80534670-fdc5d080-8975-11ea-9a9a-ad6df2dd563b.png)

**Comment by fullcontent** [comment]
Finalizei os ajustes baseados nas permissões dos usuários.
