### ISSUE TITLE
Erro ao excluir unidade

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#69]
1. Conforme tela abaixo, tentamos excluir uma unidade (458 Florianópolis cancelada) e apresenta tela de erro. Creio eu que o Erro é devido a esta unidade já possuir serviços cadastrados, peço corrigir para que a exclusão da unidade assim como dos serviços vinculados a ela seja procedida.

![image](https://user-images.githubusercontent.com/60766925/80633043-80aa6200-8a2e-11ea-90e9-2abb274209cf.png)
![image](https://user-images.githubusercontent.com/60766925/80633065-89029d00-8a2e-11ea-8cda-7d1a09bae542.png)

**Comment by castroli** [comment]
Tentamos excluir a unidade e a tela de erro permanece, peço vrificar.
![image](https://user-images.githubusercontent.com/60766925/80711331-91a6b200-8ac6-11ea-9548-0eae0b3c8f7a.png)

**Comment by fullcontent** [comment]
@castroli O ajuste foi feito e a unidade 458 excluída.

Testaremos uma próxima vez quando houver necessidade de exclusão de nova unidade.
