### ISSUE TITLE
Inserir logo 

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#7]
Colocar a logo da empresa na pagina inical e demais paginas ao lado do texto sistema CELIC.

**Comment by fullcontent** [comment]
Colocar   a logo da empresa na pagina inical e demais paginas ao lado do texto sistema   CELIC.
--

**Comment by castroli** [comment]
![image](https://user-images.githubusercontent.com/60766925/74155439-5e553500-4bf3-11ea-8d4a-c854fd775216.png)

![image](https://user-images.githubusercontent.com/60766925/74155451-63b27f80-4bf3-11ea-9657-68b606e19b5b.png)

**Comment by castroli** [comment]
@castroli Enviar logo em formato PNG

**Comment by castroli** [comment]
![LogoCastro](https://user-images.githubusercontent.com/60766925/74380608-ae392500-4dc8-11ea-93cd-d2536770fdf1.png)
