### ISSUE TITLE
Ajustes visuais 

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#71]
- [x] Botão excluir serviço na listagem da unidade
- [x] mapa de navegação (breadcrumbs)

Inserir lista aqui dos detalhes visuais

**Comment by castroli** [comment]
Bruno, referente ao "mapa de navegação (breadcrumbs)" era exatamente isso que precisávamos, porém , peço um ajuste no hiperlink do botão com o nome da emrpesa, ao clicar neste, o ideal que seja direcionado para a tela "Listagem de unidades" desta empresa. Exemplo abaixo, estava em uma unidade da RENNER, quando clico direcionar para esta tela, e assim para as demais empresas.:
![image](https://user-images.githubusercontent.com/60766925/80968160-dc3d6c80-8ded-11ea-9144-d3f74b779858.png)

**Comment by fullcontent** [comment]
@castroli Alterado!
