### ISSUE TITLE
Correção campo taxa

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#72]
No campo taxa, quando incluímos o comprovante do pagamento automaticamente o campo "Data de Pagamento" atualiza com a data do dia, neste caso que usamos como exemplo, o pagamento foi realizado no dia 29/04/2020, neste caso colocamos esta data no campo, porém, após salvar automaticamente sistema altera para a data do dia novamente, peço corrigir.

![image](https://user-images.githubusercontent.com/60766925/81073203-a9fb4000-8ebd-11ea-971d-49752edc3489.png)

**Comment by fullcontent** [comment]
@castroli Corrigido. Pode efetuar testes por gentileza?
