### ISSUE TITLE
Página com Erro (O.S. SC0031)

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#73]
Bruno, estou tentando entrar no alvará sanitário (O.S. SC0031) porém esta aparecendo uma tela de erro. Isso esta acontecendo unicamente com esta O.S, peço verificar, por favor.

![image](https://user-images.githubusercontent.com/60766925/81218082-ffb21400-8fb3-11ea-855f-e3bf043537e6.png)

![image](https://user-images.githubusercontent.com/60766925/81218189-3425d000-8fb4-11ea-840f-5ef1c591290a.png)

**Comment by fullcontent** [comment]
@castroli Corrigido

Possivel problema ao concluir pendencia: Não registrou o usuário que fez a alteração na pendencia e isso gerou o erro.

**Comment by castroli** [comment]
Obrigado Bruno. Estava com a tela da pendência em aberto e após um bom tempo cliquei em concluir pendência, após apareceu a tela de acesso expirado, creio que foi isso mesmo então.
