### ISSUE TITLE
Criando nova O.S - Anexos

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#75]
Bruno, Ao criar uma nova O.S. hoje temos que primeiro preencher os campos escritos e depois de salvar/criar, voltar na O.S. para incluir os anexos, pois se incluir os anexos já quando estamos criando o sistema não salva com os anexos, peço corrigir por favor.

**Comment by fullcontent** [comment]
@castroli Corrigido. Pode testar por gentileza?
