### ISSUE TITLE
O.S. x Pendências

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#79]
Bom dia Bruno, 
Peço criar uma regra que faça o sistema exigir **sempre** que uma ordem de serviço estiver com a situação igual a "Andamento" obrigatóriamente deverá existir uma pendência.

**Comment by fullcontent** [comment]
@castroli 

Boa tarde Diego!
Tenho algumas dúvidas quanto a isso, vamos lá:

- Em qual momento essa regra deve ser acionada?

- Qual a forma de exigir isso? (Banner, Direcionar pra tela de pendência, etc)

- No momento em que é criado o serviço, qual ação devemos tomar? Pois cada serviço novo criado está como padrão "Em Andamento".

**Comment by castroli** [comment]
Bom dia Bruno,
Segue respostas:
**Em qual momento essa regra deve ser acionada?**
Desde a criação até que a situação esteja diferente de "andamento".

**Qual a forma de exigir isso? (Banner, Direcionar pra tela de pendência, etc)**
Imagino que seria legal abrir uma caixa informando da necessidade de incluir uma pendência para O.S em andamento e automaticamente direcionar para tela de pendência.

**No momento em que é criado o serviço, qual ação devemos tomar? Pois cada serviço novo criado está como padrão "Em Andamento".** 
Quando criado uma O.S obrigatoriamente deverá constar uma pendencia agendada. Em resumo a ideia é forçar a manter uma pendência agendada para todos os serviços em andamento, e com isso não correremos o risco de esquecer de nenhuma demanda (O.S) que encontra-se em andamento.

**Comment by fullcontent** [comment]
**- Desde a criação até que a situação esteja diferente de "andamento".**
Aqui enfrentamos um pequeno conflito. As situações que temos hoje para os serviços são: Andamento, Finalizado, Arquivado.

**Sugestão de aplicação dessa regra**
Ao criar um serviço, a situação padrão seria "Novo Serviço". E permanecerá assim até que se crie uma nova pendência.
O problema da criação da pendência quando o serviço ainda não foi criado é que a pendência está atrelada ao identificador do serviço, portanto quando não salvamos o serviço, não temos como linkar a pendência ao serviço.

Acha que funcionaria bem desta forma?

**Comment by castroli** [comment]
@fullcontent 
Voltando com este tema, não seria possivel criar uma regra que após criado a demanda o sistema direcione para página de "cadastrar pendência" (imagem 03). Com isso creio que já iremos minimizar um possivel esquecimento. 
Atualmente esta direcionando da imagem 01 para imagem 02.
**Imagem 01**
![image](https://user-images.githubusercontent.com/60766925/106676236-3fcf1300-6595-11eb-96ec-ea60e9d8c7d1.png)
**Imagem 02**
![image](https://user-images.githubusercontent.com/60766925/106676264-4bbad500-6595-11eb-8fae-b63569cc4966.png)
**Imagem 03**
![image](https://user-images.githubusercontent.com/60766925/106676318-69883a00-6595-11eb-9656-dd6d5253017a.png)
