### ISSUE TITLE
Listagem de unidades

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#8]
- Separar  em 2 módulos os serviços "primário" e "secundário", sendo   que o "primário" constará o campo de vigente e vencido (citado no   item X), já para o "secundário" não constará este campo, pois não   tem vencimento.

- Excluir   o campo "status"

- Criar   novo campo, "Situação" onde constará se o alvará está   "vigente" ( com data de vencimento = ou maior que hoje) ou   "vencido" (quando a data de vencimento é inferior a hoje). E outro   campo como "Andamento", sendo as opções "sim" ou   "não".

- Criar   novo campo "Andamento", sendo as opções "sim" ou   "não". O serviço passa automaticamente para "sim" quando   faltar 60 dias para vencimento da licença e manualmente será incluido como   não quando finalizado o processo de renovação.

- Onde   hoje consta o campo "telefone"    remover e inserir o campo de status das licenças primárias sendo   vigente ou vencido (imagem 2 em anexo).

**Comment by castroli** [comment]
- Para facilitar, montei uma tela com oq imagino referente ao subitem 1, 2, 3 e 4 desta item, peço verificar se ajuda.
![image](https://user-images.githubusercontent.com/60766925/74152008-272f5580-4bec-11ea-8560-d8c6770c1a92.png)

- Abaixo a imagem referente ao subitem 5 "inserir o campo de status das licenças primárias sendo vigente ou vencido (imagem 2 em anexo".
![image](https://user-images.githubusercontent.com/60766925/74152461-1c28f500-4bed-11ea-9398-dfef06daba92.png)

**Comment by castroli** [comment]
- Referente ao subitem 5, inserir a legenda das siglas das linceças.
