### ISSUE TITLE
Arquivos DWG

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#84]
Bruno, 
Notamos que quando carregamos no sistema arquivos no formato .dwg quando fazemos o download ele baixa como .bin, teria como corrigir isso?

Exemplo: BK Loja 003 Joinville Garten Shopping
Arquivo digital

http://sistemacelic.net/admin/unidades/3

![image](https://user-images.githubusercontent.com/60766925/88723393-24bfaa00-d0ff-11ea-94cb-37f5f3dcd8fb.png)

**Comment by fullcontent** [comment]
@castroli 

Fiz uns testes aqui e funcionou o download. 
Envia pra mim esse arquivo DWG por email pra eu avaliar se tem algo a ver com o tamanho dele ou alguma especificação.

Parece que ele não terminou de fazer o upload, por isso ficou a extensao .bin.

**Comment by castroli** [comment]
Bruno, 
Segue arquivo na pasta zipada.

[BK 003 Joinville Garten Shopping - PPCI Aprovado.zip](https://github.com/fullcontent/sistemacelic/files/5041531/BK.003.Joinville.Garten.Shopping.-.PPCI.Aprovado.zip)

**Comment by fullcontent** [comment]
@castroli 

Realmente esse arquivo tem alguma informação que por algum motivo está cadastrando errado.
Tem algum outro projeto DWG para teste ?

Uma solução paliativa é zipar o arquivo e fazer o upload. Mas vamos tentar resolver essa questão.

**Comment by fullcontent** [comment]
@castroli 

Essa pendência foi resolvida?
Pelos testes que fiz, havia algo com aquele arquivo especifico DWG.

**Comment by castroli** [comment]
@fullcontent 
Não, acabei de fazer o teste e o erro continua.

**Comment by fullcontent** [comment]
@castroli 

Corrigido e fechando o chamado.. caso o erro persista pode reabrir..
