### ISSUE TITLE
Tela Erro

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#86]
Bruno,
Quando vou entrar no serviço abaixo citado esta apresentando uma tela de Erro, peço verificar, por favor.

![image](https://user-images.githubusercontent.com/60766925/89451005-e8f59780-d731-11ea-9cd9-4df0466ab30d.png)

![image](https://user-images.githubusercontent.com/60766925/89451212-36720480-d732-11ea-8340-f62dfad37e66.png)

**Comment by fullcontent** [comment]
Alterado User_ID diretamente no banco de dados.
