### ISSUE TITLE
Tela de erro

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#88]
Bruno, o sistema está com erro ao abrir o serviço. Peço verificar.
Unidade: 088 Joinville Drive 2 R. Blumenau
Serviço: AC0231 | Autorização corte de árvore

![Tela serviço](https://user-images.githubusercontent.com/60766925/89560561-95488400-d7ed-11ea-9fb0-793c1d1c409e.png)
![erro](https://user-images.githubusercontent.com/60766925/89560563-98437480-d7ed-11ea-8c13-0322614c44b1.png)

**Comment by fullcontent** [comment]
Alterado user_id diretamente no banco de dados.
