### ISSUE TITLE
Melhorias no sistema

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#89]
Bruno,
Abaxo listo alguns itens para ajustar no sistema:

- [x] 1. Ao criar um novo serviço (O.S) ou uma nova pendência, o nome do “Responsável” deve puxar direto o do usuário logado, se for outro profissional, alteramos manualmente. Atualmente consta sempre o seu nome.

- [x] 2. Ao criar um novo serviço (O.S), se cliquei no botão “novo serviço” no quadro de “serviço secundário”, na tela de criação da O.S, o campo “tipo” já deve estar com a opção “secundário”, e assim fazer também para o primário.

- [x] 3. Fazer constar o código da unidade antes do nome na tela detalhes da unidade e detalhes do serviço.
![image](https://user-images.githubusercontent.com/60766925/89588508-29304500-d81a-11ea-9302-60512c90428c.png)

- [x] 4. Na tela da O.S quando o serviço está preenchido como “Definitivo”, fazer constar para o usuário “clientes” , na tela “detalhes do serviço” campo “Tipo de Licença: Definitivo” .  Atualmente para o usuário Adm. está correto, porém para o usuário cliente não aparece o campo “Tipo de Licença”  e aparece a data 31/12/2059, no qual não deve constar.
![image](https://user-images.githubusercontent.com/60766925/89588511-2b929f00-d81a-11ea-8291-06095207681c.png)

- [x] 5. Na tela da O.S quando o serviço está preenchido como “Não aplicado”, fazer constar (para todos os usuários) na tela “detalhes do serviço” o campo “Tipo de Licença: Não aplicada”, a exemplo de quando trata-se de uma licença Renovável ou Definitiva. Atualmente o campo fica oculto. 

- [x] 6. Fazer com que o usuário “cliente” tenha acesso a pendência do processo (apenas visualize, não altere), atualmente este campo esta oculto a eles.

- [x] 7. No campo "Tipo da Licença:" peço ajustar as palavras "renovavel", "definitiva" e "não aplicada" para "Renovável", "Definitiva" e "Não aplicada".

**Comment by fullcontent** [comment]
Observações

Item #3:
No cadastro está puxando esse nome automaticamente, ou tem que ser digitado?

**Comment by castroli** [comment]
Boa tarde Bruno,

Resposta item #3:

A idéia é que conste o codigo da unidade seguido do nome, abaixo envio uma tela como exemplo.
![image](https://user-images.githubusercontent.com/60766925/89669482-eae86380-d8b5-11ea-9a91-310c00a0def8.png)
