### ISSUE TITLE
Arquivo digital

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#9]
Incluir o campo de busca no local indicado na imagem anexa para facilitar a busca de documentos.

![image](https://user-images.githubusercontent.com/60766925/74063461-338a9700-49cf-11ea-8f49-d07949a6e017.png)

Incluir botão para excluir arquivo 

![image](https://user-images.githubusercontent.com/60766925/74479723-75638380-4e8e-11ea-8767-bcd6afe18acb.png)

**Comment by fullcontent** [comment]
To resolvendo isso hoje

**Comment by castroli** [comment]
oo

**Comment by fullcontent** [comment]
test
