### ISSUE TITLE
Ajustes novo contrato

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#91]
- [x] 1. Remover o quadro "taxa" hoje existente. A ideia é que estas informações constem apenas na próxima versão em formato de relatórios.
![image](https://user-images.githubusercontent.com/60766925/89655259-36901280-d8a0-11ea-9938-7365ba29dff2.png)

- [x] 2. Fazer com que ao acessar a página "Detalhes da unidade" todos os quadros (Serviços primários, Serviços secundários, taxa, Arquivo digital) fiquem minimizado inicialmente e somente o quadro de "detalhes da unidade" fique maximizado, conforme imagem abaixo.
![image](https://user-images.githubusercontent.com/60766925/89693405-c8ba0a00-d8e4-11ea-86c3-70633501e47d.png)

- [x] 3. Solicitamos algumas alterações nos quadros existentes na página "Detalhes da unidade", são eles:

 - [x] 3.1 Alterar o nome do quadro "Serviços primários" para  "Licenças de operação".

- [x]  3.2 Alterar o nome do quadro "Serviços secundários" para "Projetos/Licenças - não renováveis";

- [x] 3.3Incluir quadro "Controle de Certidões". Este quadro, assim como o "Licenças de operação" deverá nos avisar quanto a necessidade da renovação, porém, neste caso avisar há 15 dias do vencimento.
Verificar a possibilidade de tornar este quadro visível apenas quando tiver alguma O.S cadastrada para a unidade em questão, caso contrário, mantê-lo oculto.

- [x] 3.4 Incluir quadro "Controle de Taxas". Este quadro, assim como o "Licenças de operação" deverá nos avisar quanto a necessidade de emissão/pagamento da taxa lançada, porém, neste caso avisar há 30 dias do vencimento.
Verificar a possibilidade de tornar este quadro visível apenas quando tiver alguma O.S cadastrada para a unidade em questão, caso contrário, mantê-lo oculto.

- [x] 3.5 Incluir quadro "**Facilities/Real Estate**". Este quadro, assim como o "Licenças de operação" deverá nos avisar quanto a necessidade da manutenção/renovação, porém, neste caso avisar há 30 dias do vencimento.
Verificar a possibilidade de tornar este quadro visível apenas quando tiver alguma O.S cadastrada para a unidade em questão, caso contrário, mantê-lo oculto.

- [x] 3.6 No campo "Tipo" que existe para cadastrar uma nova O.S., fazer constar os seguintes nomes/opções:
- Licenças de operação
- Não renováveis
- Controle de Certidões
- Controle de taxas
- Facilities/RE

- [x] 4. Considerando as inclusões citadas no item anterior, o aviso dos vencimentos dos novos campos poderá ser no mesmo quadro hoje existente na Dashboard, apenas faço as seguintes solicitações:

- [x] 4.1 Renomear o quadro existente na Dashboard de "Licenças a vencer" para "Serviços a vencer". 

- [x] 4.2 Já na "listagem de serviços a vencer" incluir o campo "Tipo" (citado no item 3.6), pois ele que irá diferenciar os serviços.

**Comment by fullcontent** [comment]
Lista de tarefas

- [ ] Inserir opções no tipo de serviço (Licenças de operação, Projetos/Licenças não renováveis, Controle de Taxas, Controle de certidões, Facilities/RealState)

- [ ] Alterar os visuais (Alterar todos Serviços primários para Licenças)

- [ ] Alterar dados no Banco de dados, alterando todos os tipoServiço para os nomes novos.

- [ ]  incluir coluna de tipo de serviço nas listagens

- [ ] Remover o campo taxas no detalhe da unidade

**Comment by fullcontent** [comment]
- [ ] Ajustes visuais na tela do cliente

- [ ] Revisar

**Comment by fullcontent** [comment]
@castroli 

Foram feitas todas as alterações requisitadas aqui. Peço testar e, se tiver tudo ok, fechar esse chamado.

**Comment by castroli** [comment]
@fullcontent 
Estamos testando e até o momento identificamos dois erros, são eles:
- Ao editar algum serviço, ao salvar, esta gerando a tela de erro.
![image](https://user-images.githubusercontent.com/60766925/90401741-c722db80-e074-11ea-9a97-949be082947c.png)

- Ao incluir alguma interação, esta gerando uma outra tela de erro.
![image](https://user-images.githubusercontent.com/60766925/90401758-cb4ef900-e074-11ea-96f3-53d3b199b29b.png)

**Comment by castroli** [comment]
Bom dia @fullcontent 

Surgiu mais um problema, uma unidade que ainda não tem serviço cadastrado não aparece o botão de (novo serviço), peço ajustar.
![image](https://user-images.githubusercontent.com/60766925/90516551-8ab9b300-e13a-11ea-9fe5-95fdf6da6473.png)

**Comment by fullcontent** [comment]
@castroli Corrigido.
