### ISSUE TITLE
Melhorias de usabilidade

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#96]
- [ ] Inserir botões de cadastro de laudo, protocolo e licença diretamente na tela do serviço, sem precisar editar.

- [x] Tirar botão de editar unidade

- [x] Paginar arquivo digital

**Comment by castroli** [comment]
- [ ] Incluir quadro com o valor em aberto.
![image](https://user-images.githubusercontent.com/60766925/92663086-a85fdf80-f2d6-11ea-9dca-b242b72cceb9.png)

**Comment by castroli** [comment]
- [ ] Incluir quadro com a informação da NF (campo aberto para ser editado) 
![image](https://user-images.githubusercontent.com/60766925/92663146-d8a77e00-f2d6-11ea-9eba-c0a2f6231288.png)

**Comment by castroli** [comment]
- [ ] **Incluir botão voltar na tela de interações:**
Quando clicamos em "visualizar todas as interações", não possui botão para voltar, peço incluir na parte superior e inferior da tela.

**_Parte superior da tela:_**
![image](https://user-images.githubusercontent.com/60766925/94466728-476e4d80-0198-11eb-8727-61c193642a6c.png)

**_Parte inferior da tela:_**
![image](https://user-images.githubusercontent.com/60766925/94466772-56ed9680-0198-11eb-8554-f2bac3a71f6d.png)

**Comment by castroli** [comment]
- [ ] Incluir "lista suspensa":
Quando o tipo de serviço for "Licença de operação", no campo "serviço" incluir lista suspensa com as licenças abaixo descritas:

AVCB
Alvará Sanitário
Alvará de Funcionamento
Alvará de Publicidade
Alvará da Polícia Civil
Licença Ambiental
Licença de Elevador
AMLURB

![image](https://user-images.githubusercontent.com/60766925/94469998-64594f80-019d-11eb-90db-32a6807005a8.png)

**Comment by castroli** [comment]
- [ ]  Faturamento: Ao clicar em "Cadastrar" NF, fazer com que o cursor ja fique no campo N.F., assim ficará mais prático e ganhamos tempo.

![image](https://user-images.githubusercontent.com/60766925/95132328-fe893c80-0735-11eb-9ba8-071b22319ef8.png)

![image](https://user-images.githubusercontent.com/60766925/95132608-70618600-0736-11eb-8272-190b838b1536.png)

**Comment by castroli** [comment]
- [ ] Faturamento: Quando clicamos no botão "Faturar" diretamente no serviço após gerado o relatório, incluir um botão "Voltar" 
 na tela da imagem 03 e fazer voltar pra dento da unidade que estávamos tratando.

Imagem 01:

![image](https://user-images.githubusercontent.com/60766925/95135625-18794e00-073b-11eb-95a6-76c4a650b948.png)

Imagem 02:

![image](https://user-images.githubusercontent.com/60766925/95135645-1dd69880-073b-11eb-98ea-e3b302cd01d5.png)

Imagem 03:
![image](https://user-images.githubusercontent.com/60766925/95135658-25963d00-073b-11eb-98a2-582afd6de968.png)

**Comment by castroli** [comment]
- [ ]  Nomear arquivos:
@fullcontent lembro que no inicio do CELIC quando iamos salvar um arquivo do sistema, ele ja vinha com uma nomenclatura padrão, hoje está vindo uma numeração, seria possivel ajustar isso. O ideal seria se seguisse a seguinte lógica:
"Código da unidade" "Nome da unidade" - "Nome da O.S" Vencimento licença".

**Exemplo:**
001 Aquário BC -  Alvará Sanitário 31-12-2020

![image](https://user-images.githubusercontent.com/60766925/95451558-56928f80-093e-11eb-83d3-cf668635bd1a.png)

**Comment by castroli** [comment]
- [ ] Incluir pesquisa de serviço via:
1. Nome do solicitante
2. Número do Protocolo

**Comment by castroli** [comment]
- [ ] Incluir pesquisa de **unidade** via:
1. Endereço
2. Bairro

**Comment by castroli** [comment]
- [ ] Ao excluir algum serviço, fazer com que o sistema permaneça na mesma página. Atualmente após excluído é direcionado para página "Listagem de serviços".

![image](https://user-images.githubusercontent.com/60766925/103660159-0c747680-4f4c-11eb-89f3-afd8c23594ea.png)

![image](https://user-images.githubusercontent.com/60766925/103660218-1b5b2900-4f4c-11eb-884d-5ecba5e087c7.png)

**Comment by castroli** [comment]
- [ ] Incluir na tela de "Serviços a vencer" a coluna com o a data de "Vencimento Licença". Abaixo segue iamgem indicando o local.

![image](https://user-images.githubusercontent.com/60766925/103699411-a276c400-4f81-11eb-8507-cfe6d3dbd053.png)
![image](https://user-images.githubusercontent.com/60766925/103699735-2335c000-4f82-11eb-9b2c-8eb4c2176511.png)

**Comment by castroli** [comment]
- [ ] Incluir botão para visualizar tambem o boleto.
Atualmente quando anexamos o boleto e o comprovante no campo "taxa", não tem a opção de visualizar o boleto, necessário incluir um botão.
![image](https://user-images.githubusercontent.com/60766925/103820167-999df500-504a-11eb-88cc-8bf16fc54c62.png)

**Comment by castroli** [comment]
- [ ] Incluir campo "pesquisa" dentro do quadro de pendências na dashboad.

![image](https://user-images.githubusercontent.com/60766925/103820829-c1418d00-504b-11eb-9c3b-18e001d55c67.png)

**Comment by castroli** [comment]
- [ ] Após criar ou editar uma pendência, redirecionar para página de "Detalhes do serviço" (imagem 02). Atualmente é direcionado para página citada na imagem 03.
**Imagem 01**
![image](https://user-images.githubusercontent.com/60766925/106614260-dd9cf080-6549-11eb-8e06-38fd8b11d893.png)
**Imagem 02**
![image](https://user-images.githubusercontent.com/60766925/106614435-19d05100-654a-11eb-8571-c429cc5e41b9.png)

**Imagem 03**
![image](https://user-images.githubusercontent.com/60766925/106614342-fd341900-6549-11eb-9407-14d2d00cd826.png)

**Comment by castroli** [comment]
- [ ] Incluir "lista suspensa":
Quando o tipo de serviço for "Licença de operação", no campo "serviço" incluir lista suspensa com as licenças abaixo descritas:
- [ ] Incluir as licenças faltantes no campo de legenda.

AVCB - Sigla CB
Alvará Sanitário - Sigla AS
Alvará de Funcionamento - Sigla AF
Alvará de Publicidade - Sigla AP
Alvará da Polícia Civil - Sigla PC
AMLURB - Sigla AL
CREFITO - Sigla CR
Licença Ambiental - Sigla LA
Licença de Elevador - Sigla LE

![image](https://user-images.githubusercontent.com/60766925/108716712-39c8b400-74fb-11eb-8334-1431c7a131b2.png)
![image](https://user-images.githubusercontent.com/60766925/108717394-ff134b80-74fb-11eb-99ee-59eb6daceacb.png)

**Comment by castroli** [comment]
@fullcontent bom dia!
**INTERAÇÕES**
- [ ] Conforme tela abaixo, atualmente o histórico das interações estão desorganizadas, peço organizá-las de forma que a ultima interação fique no topo.

![image](https://user-images.githubusercontent.com/60766925/109012722-15064500-7691-11eb-8eb5-83f941b67734.png)

**Comment by castroli** [comment]
@fullcontent 
DETALHES DO SERVIÇO:

Tela "**Detalhes do serviço**" peço, quando o "Tipo da licença" for "Não aplicado", remover tambem o campo "Emissão da licença", atualmente está aparecendo.
![image](https://user-images.githubusercontent.com/60766925/109873111-12d15700-7c4c-11eb-8c3b-c63f61450fec.png)

**Comment by fullcontent** [comment]
@castroli 

Peço testar por gentileza.

Alguns itens de maior complexidade foram movidos para novos chamados 

#141 
#140 
#139
