### ISSUE TITLE
Interações/Histórico

### ISSUE THREAD

**Issue by fullcontent** [fullcontent/sistemacelic#97]
- [x] Na tela do serviço, filtrar somente as interações dos usuários.

- [ ] Atribuir ao usuário Robot as interações automáticas.

- [ ] Enviar notificação em forma de chat para o responsável do serviço quando houver interação do cliente [Implementar no dashboard]

**Comment by castroli** [comment]
@fullcontent boa tarde!

- [ ] Precisamos diferenciar no campo de interações as feitas pelos usuários e pelo Robot. Atualmente está bem difícil de conseguir identificar as atualizações dos usuários, pois acaba tendo muitas do Robot. O ideal seria deixar as interações do Robot de forma oculta, se o usuário desejar vê-la, selecionar em algum lugar para aparecer, caso contrário, manter visível apenas as interações dos usuários.
![image](https://user-images.githubusercontent.com/60766925/106664993-88ca9b80-6584-11eb-958d-6530d1cb360e.png)
